### ISSUE TITLE
Mapping : Error depending on order of Required/ForeignKey

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1286]
Consider the following:

```
public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public House SummerHouse { get; set; }
        public int? SummerHouseId { get; set; }
    }

    public class House
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Person Owner { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }

        public DbSet<House> Houses { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<House>().Property(h => h.Id);
            modelBuilder.Entity<Person>().Property(h => h.Id);
            modelBuilder.Entity<Person>().OneToOne(p => p.SummerHouse, h => h.Owner).Required(false).ForeignKey<Person>(h => h.SummerHouseId);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "NullableOneToOne", IntegratedSecurity = true }.ToString());
        }
    }
```

this throws the following:

Unhandled Exception: System.InvalidOperationException: The property 'Id' on entity type 'House' cannot be marked as nullable/optional because the type of the property is 'Int32' which is not a nullable type. Any property can be marked as non-nullable/required, but only properties of nullable types can be marked as nullable/optional.
   at Microsoft.Data.Entity.Metadata.Property.set_IsNullable(Nullable`1 value)
   at Microsoft.Data.Entity.Metadata.ForeignKey.set_IsRequired(Nullable`1 value)

   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.Requir
ed(Boolean required)
   at Microsoft.Data.Entity.Metadata.ModelBuilder.EntityBuilder.OneToOneBuilder.
Required(Boolean required)
   at NullableOneToOne.MyContext.OnModelCreating(ModelBuilder modelBuilder) in D
:\Projects\NullableOneToOne\NullableOneToOne\Program.cs:line 41
   at Microsoft.Data.Entity.Infrastructure.ModelSourceHelpers.OnModelCreating(Db
Context context, ModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.CreateModel(DbCont
ext context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.<>c__DisplayClass0
.<GetModel>b__1(Type k)
   at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey
key, Func`2 factory)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.GetModel(DbContext
 context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Infrastructure.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Infrastructure.DbContextServices.get_Model()
   at Microsoft.Data.Entity.Infrastructure.DbContextServices.<>c__DisplayClass7.
<get_ModelFactory>b__9()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Infrastructure.DbContextService`1.get_Service()
   at Microsoft.Data.Entity.Infrastructure.Database.get_Model()
   at Microsoft.Data.Entity.Infrastructure.Database.EnsureDeleted()
   at NullableOneToOne.Program.Main(String[] args) in D:\Projects\NullableOneToO
ne\NullableOneToOne\Program.cs:line 57

**Comment by mikary** [comment]
The exception is not thrown if the Required call follows the ForeignKey, rather than preceding it. Clearing labels to run back through triage.

**Comment by mikary** [comment]
Related: #1314 and #1285

**Comment by rowanmiller** [comment]
Triage: Order of these API calls should not matter
