### ISSUE TITLE
Mapping :: exception (can't find shadow key) for model with One to One mapping using shadow key and self referencing One to One mapping using regular property as FK

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1287]
```
    public class Soldier
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Weapon PrimaryWeapon { get; set; }
    }

    public class Weapon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Damage { get; set; }
        public Weapon SynergyWith { get; set; }
        public int? SynergyWithId { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Soldier> Soldiers{ get; set; }
        public DbSet<Weapon> Weapons { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Weapon>().Property(typeof(int), "ShadowKey");
            modelBuilder.Entity<Weapon>().OneToOne(w => w.SynergyWith).ForeignKey<Weapon>(w => w.SynergyWithId).Required(false);
            modelBuilder.Entity<Soldier>(m =>
            {
                m.OneToOne(s => s.PrimaryWeapon).ForeignKey(typeof(Weapon), "ShadowKey");
            });

            modelBuilder.Entity<Weapon>().Key(w => w.Id);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "IncludeBash", IntegratedSecurity = true }.ToString());
        }
    }
```

Unhandled Exception: Microsoft.Data.Entity.Metadata.ModelItemNotFoundException:
The property 'ShadowKey' on entity type 'IncludeBashing.Weapon' could not be found. Ensure that the property exists and has been included in the model.
   at Microsoft.Data.Entity.Metadata.EntityType.GetProperty(String propertyName)

   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.<Forei
gnKey>b__1(String p)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.Foreig
nKey(IEnumerable`1 properties, ConfigurationSource configurationSource)
   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.Foreig
nKey(IReadOnlyList`1 propertyNames, ConfigurationSource configurationSource)
   at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.OneToO
neForeignKey(Type specifiedDependentType, IReadOnlyList`1 propertyNames, Configu
rationSource configurationSource)
   at Microsoft.Data.Entity.Metadata.ModelBuilder.EntityBuilder.OneToOneBuilder.
ForeignKey(Type dependentEntityType, String[] foreignKeyPropertyNames)
   at IncludeBashing.MyContext.<>c__DisplayClass0.<OnModelCreating>b__1(EntityBu
ilder`1 m) in D:\Projects\IncludeBashing\IncludeBashing\Program.cs:line 83
   at Microsoft.Data.Entity.Metadata.ModelBuilder.Entity[T](Action`1 entityBuild
er)
   at IncludeBashing.MyContext.OnModelCreating(ModelBuilder modelBuilder) in D:\
Projects\IncludeBashing\IncludeBashing\Program.cs:line 80
   at Microsoft.Data.Entity.Infrastructure.ModelSourceHelpers.OnModelCreating(Db
Context context, ModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.CreateModel(DbCont
ext context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.<>c__DisplayClass0
.<GetModel>b__1(Type k)
   at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey
key, Func`2 factory)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.GetModel(DbContext
 context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Infrastructure.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Infrastructure.DbContextServices.get_Model()
   at Microsoft.Data.Entity.Infrastructure.DbContextServices.<>c__DisplayClass7.
<get_ModelFactory>b__9()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Infrastructure.DbContextService`1.get_Service()
   at Microsoft.Data.Entity.Infrastructure.Database.get_Model()
   at Microsoft.Data.Entity.Infrastructure.Database.EnsureDeleted()
   at IncludeBashing.Program.Main(String[] args) in D:\Projects\IncludeBashing\I
ncludeBashing\Program.cs:line 104

**Comment by mikary** [comment]
There is a problem with the provided reproduction related to #1372, may be relevant to issue.
