### ISSUE TITLE
Query :: Aliases are not uniquified for some queries with SelectMany - may produce invalid sql

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1294]
```
    public class Soldier
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Soldier Officer { get; set; }
        public ICollection<Soldier> Reports { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Soldier> Soldiers{ get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Soldier>(m =>
            {
                m.OneToMany(s => s.Reports, s => s.Officer);
            });
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "IncludeBash", IntegratedSecurity = true, MultipleActiveResultSets = true}.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var infantry1 = new Soldier
                {
                    Name = "Infantry1",
                };

                var infantry2 = new Soldier
                {
                    Name = "Infantry2",
                };

                var vanDoorn = new Soldier
                {
                    Name = "Peter Van Doorn",
                };

                ctx.Soldiers.Add(infantry1, infantry2, vanDoorn);

                ctx.SaveChanges();

                vanDoorn.Reports = new List<Soldier> { infantry1, infantry2 };
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var result = ctx.Soldiers.Include(s => s.Officer).SelectMany(a => ctx.Soldiers).ToList();
                Console.WriteLine(result);
            }
        }
    }
```

produces the following sql:

```
SELECT [s].[Id], [s].[Name], [s].[OfficerId]
FROM [Soldier] AS [s]
CROSS JOIN [Soldier] AS [s]
```

which throws:

Unhandled Exception: System.Data.SqlClient.SqlException: The correlation name 's' is specified multiple times in a FROM clause.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolea
n breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception
, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObj
ect stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand
 cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler,
TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, Run
Behavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBe
havior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 time
out, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletio
nSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, S
tring method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behav
ior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable`1.Enumerator.Mov
eNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.<_TrackEntities>d__1`2.Mo
veNext()
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.EnumerableExceptionInterce
ptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at IncludeInvalidQuery.Program.Main(String[] args) in D:\Projects\IncludeInva
lidQuery\IncludeInvalidQuery\Program.cs:line 73

**Comment by maumar** [comment]
this is now fixed, closing
