### ISSUE TITLE
Enable EF6 Perf Tests in CI

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#1323]
Currently disabled due to failure on CI machine

```
[13:14:21]Step 3/6: Build project (Command Line) (5m:31s)

[13:16:12][Step 3/6] xunit-test (3m:39s)

[13:19:51][xunit-test] Exit code 1 from cmd

[13:19:51][xunit-test] Stack trace: 

   at Viewdd99d4e25e05422893a7121d65b6a3cd.K(String command, String workingdir, String kvmUse) in c:\BuildAgent\temp\buildTmp\951c03735a1048fc8343e510c6795111-1.cs:line 640

   at Viewdd99d4e25e05422893a7121d65b6a3cd.<RenderViewLevel0>b__4b() in c:\BuildAgent\temp\buildTmp\951c03735a1048fc8343e510c6795111-1.cs:line 2614

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)

   at Viewdd99d4e25e05422893a7121d65b6a3cd.<RenderViewLevel0>b__3b() in c:\BuildAgent\temp\buildTmp\951c03735a1048fc8343e510c6795111-1.cs:line 1331

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)

   at Viewdd99d4e25e05422893a7121d65b6a3cd.<RenderViewLevel0>b__41() in c:\BuildAgent\temp\buildTmp\951c03735a1048fc8343e510c6795111-1.cs:line 1436

   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)

   at Sake.Engine.SakeEngine.Execute(Options options)

   at Sake.Engine.SakeEngine.Execute(String[] args)

   at Sake.Program.Main(String[] args)

[13:19:52][xunit-test] Step Build project (Command Line) failed

```

**Comment by rowanmiller** [comment]
Done https://github.com/aspnet/EntityFramework/commit/9a9293d1a1d029c379bc315acc3abeed5a82dfb8
