### ISSUE TITLE
Adding migrations to rename tables throws error

### ISSUE THREAD

**Issue by suhasj** [aspnet/EntityFramework#1346]
I was repro this bug with EF 7.0.0-rc1-11882

Create a new starter web project and add the following code to rename the Identity tables
```C#
    foreach (var entityType in builder.Model.EntityTypes)
    {
        var table = entityType.Relational().Table;
        if (table.StartsWith("AspNet"))
            entityType.Relational().Table = table.Substring(6);
    }
```
Now running `k ef migration add RenameTables` gives the following error

```
k : System.InvalidOperationException: Sequence contains no matching element
At line:1 char:1
    + k ef migration add RenameTables
    + CategoryInfo          : NotSpecified: (System.InvalidO...atching element:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.Linq.Enumerable.Single {TSource} (IEnumerable<sourc>, Func<predicate>)
   at Microsoft.Data.Entity.SqlServer.SqlServerMigrationOperationProcessor.Process(AlterColumnOpe
ration alterColumnOperation, Context context)
   at Microsoft.Data.Entity.SqlServer.SqlServerMigrationOperationProcessor.Process(MigrationOperationCollection operations, IModel sourceModel, 
IModel targetModel)
   at Microsoft.Data.Entity.Migrations.Model
Differ.Diff(IModel sourceModel, IModel targetModel)
   at Microsoft.Data.Entity.Commands.Migrations.MigrationScaffolder.CreateMigration(String migrationName)
   at Microsoft.Data.Entity.Commands.Migrations.MigrationScaffolder.ScaffoldMigration(String mig
rationName, String rootNamespace)
   at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String rootNamespace, String 
projectDir)
   at Microsoft.Data.Entity.Commands.Program.AddMigration(String name
, String context)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass4.<Main>b__17()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[]
 args)

```

**Comment by bricelam** [comment]
This is mostly fixed. The remaining issues are tracked by #1907 & #1912
