### ISSUE TITLE
ChangeTracker :: NRE during SaveChanges - trying to set int Id to null value in some cases

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1371]
Consider the following model:

```
   public class Customer
    {
        public string Id { get; set; }
        public string Name { get; set; }

        public Order Order { get; set; }
    }

    public class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<OrderDetail> OrderDetails { get; set; }
    }

    public class OrderDetail
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Order Order { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderDetail> OrderDetails { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>().OneToOne(c => c.Order);
            modelBuilder.Entity<Order>().OneToMany(o => o.OrderDetails);
            modelBuilder.Entity<Customer>().Property(o => o.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Order>().Property(o => o.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<OrderDetail>().Property(o => o.Id).GenerateValueOnAdd(false);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "MultiLevelInclude2", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();


                var c1 = new Customer
                {
                    Id = "1",
                    Name = "Customer1"
                };

                var o1 = new Order
                {
                    Id = 1,
                    Name = "Order1"
                };

                var od10 = new OrderDetail
                {
                    Id = 10,
                    Name = "OrderDetail 1 0"
                };

                ctx.Customers.Add(c1);
                ctx.Orders.Add(o1);
                c1.Order = o1;

                ctx.SaveChanges();
            }
        }
    }
```

throws:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Entity.Metadata.ClrPropertySetter`2.SetClrValue(Object instance, Object value) in D:\k\EntityFramework\src\EntityFramework.Core\Metadata\ClrPropertySetter.cs:line 25
   at Microsoft.Data.Entity.ChangeTracking.StateEntryMetadataServices.WriteValue(Object entity, IPropertyBase propertyBase, Object value) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\StateEntryMetadataServices.cs:line 56
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.WritePropertyValue(IPropertyBase propertyBase, Object value) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\StateEntry.cs:line 329
   at Microsoft.Data.Entity.ChangeTracking.StateEntry.set_Item(IPropertyBase property, Object value) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\StateEntry.cs:line 384
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.SetForeignKeyValue(IForeignKey foreignKey, StateEntry dependentEntry, IReadOnlyList`1 principalValues) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\NavigationFixer.cs:line 454
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.SetForeignKeyValue(IForeignKey foreignKey, StateEntry dependentEntry, StateEntry principalEntry) in D
:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\NavigationFixer.cs:l
ine 441
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.NavigationReferenceChangedAction(StateEntry entry, INavigation navigation, Object oldValue, Object newValue) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\NavigationFixer.cs:line 123
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.<>c__DisplayClass7.<NavigationReferenceChanged>b__8() in D:\k\EntityFramework\src\EntityFramework.Cor
e\ChangeTracking\NavigationFixer.cs:line 95
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.PerformFixup(Action fixupAction) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\NavigationFixer.cs:line 330
   at Microsoft.Data.Entity.ChangeTracking.NavigationFixer.NavigationReferenceChanged(StateEntry entry, INavigation navigation, Object oldValue, Object newValue) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\NavigationFixer.cs:line 95
   at Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.<>c__DisplayClass6.<NavigationReferenceChanged>b__7(IRelationshipListener l) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\StateEntryNotifier.cs:line 83
   at Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.Dispatch(Action`1 action) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\StateEntryNotifier.cs:line 173
   at Microsoft.Data.Entity.ChangeTracking.StateEntryNotifier.NavigationReferenceChanged(StateEntry entry, INavigation navigation, Object oldValue, Object newValue) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\StateEntryNotifier.cs:line 83
   at Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectNavigationChange(StateEntry entry, INavigation navigation) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\ChangeDetector.cs:line 230
   at Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectChanges(StateEntry entry) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\ChangeDetector.cs:line 159
   at Microsoft.Data.Entity.ChangeTracking.ChangeDetector.DetectChanges(StateManager stateManager) in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\ChangeDetector.cs:line 110
   at Microsoft.Data.Entity.DbContext.SaveChanges() in D:\k\EntityFramework\src\EntityFramework.Core\DbContext.cs:line 203
   at MultiInclude2.Program.Main(String[] args) in D:\Projects\MultiInclude2\MultiInclude2\Program.cs:line 142

**Comment by smitpatel** [comment]
Unable to repro. Works perfect for me. Probably got fixed in some recent changes.

**Comment by rowanmiller** [comment]
@maumar - are you happy if we just close this one?

**Comment by maumar** [comment]
sounds good
