### ISSUE TITLE
OneToOne.ForeignKey throws if PK type is different from FK type even when PK is not used as principal key

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#1398]
With the entities and builder code below, the Guid PK on Product is not used in the relationship between Product and ProductTag. However, in the ForeignKey call the intermediate state of the model has this Guid PK as the principal key, which then results in the exception below. The model is built correctly if the ReferencedKey call is made first.

```
private class Product
{
    public Guid Id { get; set; }
    public int TagId { get; set; }
    public ProductTag Tag { get; set; }
}

private class ProductTag
{
    public int Id { get; set; }

    public int ProductId { get; set; }
    public Product Product { get; set; }
}

var builder = new ModelBuilder();

builder.Entity<Product>(b =>
    {
        b.OneToOne(e => e.Tag, e => e.Product)
            .ForeignKey<ProductTag>(e => e.ProductId)
            .ReferencedKey<Product>(e => e.TagId);
    });
```

Stack trace:
```
Test 'Microsoft.Data.Entity.Tests.ChangeTracking.ChangeDetectorTest.Brings_in_single_new_entity_set_on_collection_navigation' failed:
	System.InvalidOperationException : The types of the properties specified for the foreign key 'ProductId' on entity type 'Microsoft.Data.Entity.Tests.ChangeTracking.ChangeDetectorTest+ProductTag' do not match the types of the properties in the referenced key on entity type 'Microsoft.Data.Entity.Tests.ChangeTracking.ChangeDetectorTest+Product'.
	Metadata\Internal\InternalRelationshipBuilder.cs(387,0): at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(EntityType principalType, EntityType dependentType, IReadOnlyList`1 foreignKeyProperties, IReadOnlyList`1 referencedProperties, String navigationToPrincipalName, String navigationToDependentName, Boolean oneToOne, ConfigurationSource configurationSource)
	Metadata\Internal\InternalRelationshipBuilder.cs(302,0): at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ReplaceForeignKey(ConfigurationSource configurationSource, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalProperties)
	Metadata\Internal\InternalRelationshipBuilder.cs(157,0): at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ForeignKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
	Metadata\Internal\InternalRelationshipBuilder.cs(122,0): at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ForeignKey(IReadOnlyList`1 properties, ConfigurationSource configurationSource)
	Metadata\Internal\InternalRelationshipBuilder.cs(168,0): at Microsoft.Data.Entity.Metadata.Internal.InternalRelationshipBuilder.ForeignKey(Type specifiedDependentType, IReadOnlyList`1 properties, ConfigurationSource configurationSource)
	Metadata\ModelBuilder.cs(708,0): at Microsoft.Data.Entity.Metadata.ModelBuilder.EntityBuilder.OneToOneBuilder.ForeignKey[TDependentEntity](Expression`1 foreignKeyExpression)
	ChangeTracking\ChangeDetectorTest.cs(1182,0): at Microsoft.Data.Entity.Tests.ChangeTracking.ChangeDetectorTest.<>c__DisplayClass18.<BuildModel>b__19(EntityBuilder`1 b)
	Metadata\ModelBuilder.cs(122,0): at Microsoft.Data.Entity.Metadata.ModelBuilder.Entity[TEntity](Action`1 entityBuilder)
	ChangeTracking\ChangeDetectorTest.cs(1180,0): at Microsoft.Data.Entity.Tests.ChangeTracking.ChangeDetectorTest.BuildModel()
	ChangeTracking\ChangeDetectorTest.cs(1106,0): at Microsoft.Data.Entity.Tests.ChangeTracking.ChangeDetectorTest.Brings_in_single_new_entity_set_on_collection_navigation()
```

**Comment by AndriySvyryd** [comment]
We should create a shadow PK for the intermediate state to make this work.
If the shadow PK isn't replaced then we will throw/log a warning in Model Validation #1205.
