### ISSUE TITLE
Query : "ExecuteReader requires an  open and available Connection" thrown when trying to execute a query after a failed query executed before

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1457]
Repro:

```
namespace Repro1457
{
    public class Level1
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public ICollection<Level2> OneToMany_Required { get; set; }
        public ICollection<Level2> OneToMany_Optional { get; set; }
    }

    public class Level2
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Level1_Required_Id { get; set; }
        public int? Level1_Optional_Id { get; set; }

        public ICollection<Level3> OneToMany_Required { get; set; }
        public ICollection<Level3> OneToMany_Optional { get; set; }

        public Level1 OneToMany_Required_Inverse { get; set; }
        public Level1 OneToMany_Optional_Inverse { get; set; }
    }

    public class Level3
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public int Level2_Required_Id { get; set; }
        public int? Level2_Optional_Id { get; set; }

        public Level2 OneToMany_Required_Inverse { get; set; }
        public Level2 OneToMany_Optional_Inverse { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Level1> LevelOne { get; set; }
        public DbSet<Level2> LevelTwo { get; set; }
        public DbSet<Level3> LevelThree { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Level1>().Property(e => e.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id).GenerateValueOnAdd(false);

            modelBuilder.Entity<Level1>().HasMany(e => e.OneToMany_Required).WithOne(e => e.OneToMany_Required_Inverse).Required(true);
            modelBuilder.Entity<Level1>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level2>().Property(e => e.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level2>().Property(e => e.Id).GenerateValueOnAdd(false);

            modelBuilder.Entity<Level2>().HasMany(e => e.OneToMany_Required).WithOne(e => e.OneToMany_Required_Inverse).Required(true);
            modelBuilder.Entity<Level2>().HasMany(e => e.OneToMany_Optional).WithOne(e => e.OneToMany_Optional_Inverse).Required(false);

            modelBuilder.Entity<Level3>().Property(e => e.Id).GenerateValueOnAdd(false);
            modelBuilder.Entity<Level3>().Property(e => e.Id).GenerateValueOnAdd(false);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "IncludeComplexTests", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
                var l1_01 = new Level1 { Id = 1, Name = "L1 01", };
                var l1_02 = new Level1 { Id = 2, Name = "L1 02", };
                var l1_03 = new Level1 { Id = 3, Name = "L1 03", };

                var l2_01 = new Level2 { Id = 1, Name = "L2 01", };
                var l2_02 = new Level2 { Id = 2, Name = "L2 02", };
                var l2_03 = new Level2 { Id = 3, Name = "L2 03", };

                var l3_01 = new Level3 { Id = 1, Name = "L3 01", };
                var l3_02 = new Level3 { Id = 2, Name = "L3 02", };
                var l3_03 = new Level3 { Id = 3, Name = "L3 03", };

                var l1s = new[] { l1_01, l1_02, l1_03, }.ToArray();
                var l2s = new[] { l2_01, l2_02, l2_03, }.ToArray();
                var l3s = new[] { l3_01, l3_02, l3_03, }.ToArray();

                ctx.LevelOne.Add(l1s);
                ctx.LevelTwo.Add(l2s);
                ctx.LevelThree.Add(l3s);

                l1s[0].OneToMany_Required = new List<Level2> { l2s[0], l2s[1], l2s[2], };
                l2s[0].OneToMany_Required = new List<Level3> { l3s[0], l3s[1], l3s[2], };

                ctx.SaveChanges();

                l1s[0].OneToMany_Optional = new List<Level2> { l2s[1] };
                l2s[0].OneToMany_Optional = new List<Level3> { l3s[1] };

                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                try
                {
                    var result1 = ctx.LevelOne.Include(e => e.OneToMany_Optional).ThenInclude(e => e.OneToMany_Optional).ToList();
                }
                catch
                {

                }

                var result2 = ctx.LevelOne.Include(e => e.OneToMany_Optional).ThenInclude(e => e.OneToMany_Optional).ToList();
            }
        }
    }
}
```

throws:

Unhandled Exception: System.InvalidOperationException: ExecuteReader requires an
 open and available Connection. The connection's current state is closed.
   at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean as
ync)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletio
nSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehav
ior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, S
tring method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behav
ior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable`1.Enumerator.Mov
eNext() in D:\k\EntityFramework\src\EntityFramework.Relational\Query\QueryingEnu
merable.cs:line 72
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.<Finally>d
__0`1.MoveNext() in D:\k\EntityFramework\src\EntityFramework.Relational\Utilitie
s\EnumerableExtensions.cs:line 15
   at System.Linq.Enumerable.<SelectManyIterator>d__8`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.EnumerableExceptionInterce
ptor`1.EnumeratorExceptionInterceptor.MoveNext() in D:\k\EntityFramework\src\Ent
ityFramework.Core\Query\EntityQueryExecutor.cs:line 179
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Repro1457.Program.Main(String[] args) in D:\Projects\Repro1457\Repro1457\P
rogram.cs:line 127

**Comment by maumar** [comment]
fixed with c64f9e2938d8464b383b59067e06c6b3dde8e070

**Comment by maumar** [comment]
reopening to keep track work of adding tests

**Comment by maumar** [comment]
tests are now unblocked by c12501a2d884d240f83de7a6b236c9a37af28db2, closing
