### ISSUE TITLE
.Include() throws error if base record does not exist

### ISSUE THREAD

**Issue by mperiannan** [aspnet/EntityFramework#1511]
```c#
var dinner = await _database.Dinners
                    .Include(d => d.Rsvps)
                    .SingleOrDefaultAsync(d => d.DinnerID == dinnerId);
```

will fail if the dinnerId does not exist in the table.

```
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, INavigation navigation, Func`3 relatedValueReaders)
   at Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.<_IncludeCollection>d__0`1.MoveNext()
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.<_TrackEntities>d__0`2.MoveNext()
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.EnumerableExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteSingle[T](QueryModel queryModel, Boolean _)
   at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteSingleQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.Clauses.StreamedData.StreamedSingleValueInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
   at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
   at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
   at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at NerdDinner.Web.Persistence.NerdDinnerRepository.GetDinnerAsync(Int32 dinnerId) in C:\Workspace\NerdDinner\NerdDinner\src\NerdDinner.Web\Persistence\NerdDinnerRepository.cs:line 55
```

**Comment by Eilon** [comment]
@mperiannan in GitHub use Markdown delimiters such as triple-backtick (three of `) to denote a multiline code block. See the "edit" view of your post above for how I updated it. You can optionally follow the code block delimiter with a language.

**Comment by maumar** [comment]
I'm having hard time reproducing the issue. 
I'm trying with the following code:

```
namespace Repro1511
{
    public class Dinner
    {
        public int DinnerId { get; set; }
        public string Name { get; set; }

        public List<Rsvp> Rsvps { get; set; }
    }

    public class Rsvp
    {
        public int RsvpId { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {

        public DbSet<Dinner> Dinners { get; set; }
        public DbSet<Rsvp> Rsvps { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Dinner>().HasMany(d => d.Rsvps);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Repro1511", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }
    }

    public class Test
    {
        public async Task Run()
        {
            using (var ctx = new MyContext())
            {
                var dinnerId = 10;

                var result = await ctx.Dinners
                    .Include(d => d.Rsvps).SingleOrDefaultAsync(d => d.DinnerId == dinnerId);

                Console.WriteLine(result?.Name);
            }
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var rob = new Rsvp { Name = "Rob" };
                var catelyn = new Rsvp { Name = "Catelyn" };
                var joffrey = new Rsvp { Name = "Joffrey" };

                var redWedding = new Dinner { Name = "Red Wedding", Rsvps = new List<Rsvp> { rob, catelyn } };
                var purpleWedding = new Dinner { Name = "Purple Wedding", Rsvps = new List<Rsvp> { joffrey } };

                ctx.Dinners.Add(redWedding, purpleWedding);
                ctx.Rsvps.Add(rob, catelyn, joffrey);
                ctx.SaveChanges();
            }

            var test = new Test();
            test.Run().Wait();
        }
    }
}
```

This works as expected. Which build of EF are you using? Does it still repro with the latest bits? If so, would it be possible for you to provide a small sample that would reproduce it?

**Comment by maumar** [comment]
No response from the customer and the best-guess for the repro (based on the query provided) works as expected - closing
