### ISSUE TITLE
Query: Calling ICollection<>.Contains() with a sub query with navigations gives incorrect results

### ISSUE THREAD

**Issue by DavidObando** [aspnet/EntityFramework#153]
Have a query of this shape:
```C#
from p in context.Products
where p.OrderDetails.Contains(context.OrderDetails.FirstOrDefault(orderDetail => orderDetail.Discount == 0.1))
select p;
```
EF will throw an Argument Exception:

System.ArgumentException : The item expression ('{from OrderDetail orderDetail in value(Microsoft.Data.Entity.Query.EntityQueryable`1[Northwind.OrderDetail]) where (Convert([orderDetail].Discount) == 0.1) select [orderDetail] => FirstOrDefault()}') is no ConstantExpression, it is a SubQueryExpression.
Parameter name: expression
	at Remotion.Linq.Clauses.ResultOperatorBase.InvokeExecuteMethod(MethodInfo method, Object input)
	at Remotion.Linq.Clauses.ResultOperatorBase.InvokeGenericExecuteMethod[TInput,TResult](IStreamedData input, Func`2 genericExecuteCaller)
	at Remotion.Linq.Clauses.ResultOperators.ValueFromSequenceResultOperatorBase.ExecuteInMemory(IStreamedData input)
	Query\EntityQueryModelVisitor.cs(430,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ExecuteResultOperator[TSource,TResult](IEnumerable`1 source, ResultOperatorBase resultOperator, StreamedSequenceInfo streamedSequenceInfo)
	at lambda_method(Closure , QuerySourceScope )

**Comment by rowanmiller** [comment]
Tried this on latest build and it no longer throws, but it does return the incorrect results.

Full code I used is

```c#
using System;
using System.Collections.Generic;
using Microsoft.Data.Entity;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new ProductContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                db.Products.Add(new Product
                {
                    Name = "Crackers",
                    OrderDetails = new List<OrderDetail>
                    {
                        new OrderDetail
                        {
                            Discount = 0.1
                        }
                    }
                });

                db.Products.Add(new Product
                {
                    Name = "Cheese",
                    OrderDetails = new List<OrderDetail>
                    {
                        new OrderDetail
                        {
                            Discount = 0.2
                        }
                    }
                });

                db.SaveChanges();

                var query = from p in db.Products
                where p.OrderDetails.Contains(db.OrderDetails.FirstOrDefault(orderDetail => orderDetail.Discount == 0.1))
                select p;

                foreach (var item in query)
                {
                    Console.WriteLine(item.Name);
                }
            }
        }
    }

    public class ProductContext : DbContext
    {
        public DbSet<OrderDetail> OrderDetails { get; set; }
        public DbSet<Product> Products { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=Products;Trusted_Connection=True;");
        }
    }

    public class OrderDetail
    {
        public int OrderDetailId { get; set; }
        public double Discount { get; set; }
        public int ProductId { get; set; }
        public Product Product { get; set; }
    }

    public class Product
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public List<OrderDetail> OrderDetails { get; set; }
    }
}
```

Generated SQL is

```SQL
SELECT [p].[ProductId], [p].[Name]
FROM [Product] AS [p]
WHERE (
    SELECT 1
    FROM [OrderDetail] AS [o]
    WHERE [p].[ProductId] = [o].[ProductId]
) = 1
```

And all products are returned from the query (i.e. the filter is not applied in-memory either).

**Comment by mikary** [comment]
In #4297 queries with `Contains` were updated to generate SQL with the `IN` syntax. This works for scalar values, but navigations may involve composite keys.

The provided query tests equality on a floating point value, which tends to have unexpected results, so a better example could be something like this:
```cs
    from p in context.Products
    where p.OrderDetails.Contains(context.OrderDetails.FirstOrDefault(orderDetail => orderDetail.Quantity == 1))
    select p;
```

The current implementation generates the following SQL:
```sql
SELECT [p].[ProductID], [p].[Discontinued], [p].[ProductName], [p].[UnitsInStock]
FROM [Products] AS [p]
WHERE (
    SELECT CASE
        WHEN (
            SELECT TOP(1) 1
            FROM [Order Details] AS [orderDetail]
            WHERE [orderDetail].[Quantity] = 1
        ) IN (
            SELECT 1
            FROM [Order Details] AS [o]
            WHERE [p].[ProductID] = [o].[ProductID]
        )
        THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
    END
) = 1
```
This generates incorrect results because the `IN` does not correlate the data between the two subqueries.

To correlate these subqueries, the keys of boths `Order Details` rows must match, but this table has a complex key and a subquery in an `IN` cannot select more than one column, which means continuing without restructuring the query would require some kind of work-around for navigations like
```sql
SELECT [p].[ProductID], [p].[Discontinued], [p].[ProductName], [p].[UnitsInStock]
FROM [Products] AS [p]
WHERE (
    SELECT CASE
        WHEN (
            SELECT TOP(1) CONCAT([o].[OrderID], '_',  [o].[ProductID])
            FROM [Order Details] AS [o]
            WHERE [o].[Quantity] = 1
        ) IN (
            SELECT CONCAT([orderDetail].[OrderID], '_', [orderDetail].[ProductID])
            FROM [Order Details] AS [orderDetail]
            WHERE [p].[ProductID] = [orderDetail].[ProductID]
        )
        THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
    END
) = 1
```

An alternative implementation would be to switch from using `IN` to `EXISTS` which would allow for a query more like:
```sql
SELECT [p].[ProductID], [p].[Discontinued], [p].[ProductName], [p].[UnitsInStock]
FROM [Products] AS [p]
WHERE (
    SELECT CASE
        WHEN (
            Exists(
	            select 1 from (
				    SELECT TOP (1) [o].[OrderID], [o].[ProductID]
                    FROM [Order Details] AS [o]
			        WHERE [o].[Quantity] = 1
			    ) as [t0] INNER JOIN (
				    SELECT [orderDetails].[OrderID], [orderDetails].[ProductID]
			        FROM [Order Details] AS [orderDetails]
                    WHERE [p].[ProductID] = [orderDetails].[ProductID]
				) as [t1]  on [t0].[OrderID] = [t1].[OrderID] AND [t0].[ProductID] = [t1].[ProductID]
            )
        )
        THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
    END
) = 1
```

**Comment by divega** [comment]
I suspect that IN is a non-starter for composite keys. The concatenation will most likely make the query non-sargable.

Also, the CASE should be unnecessary and it should be possible to avoid the JOIN in the subquery, e.g. something like this:

``` SQL
SELECT [p].[ProductID], [p].[Discontinued], [p].[ProductName], [p].[UnitsInStock]
FROM [Products] AS [p]
WHERE EXISTS (
        SELECT NULL
        FROM (
                SELECT TOP (1) [o].[OrderID], [o].[ProductID]
                FROM [Order Details] AS [o]
                WHERE [o].[Quantity] = 1) as [t1]
         WHERE   on [p].[OrderID] = [t1].[OrderID] AND [p].[ProductID] = [t1].[ProductID])
```
I think we could also use a query based on JOIN instead of EXISTS:

``` SQL
SELECT [p].[ProductID], [p].[Discontinued], [p].[ProductName], [p].[UnitsInStock]
FROM [Products] AS [p]
        INNER JOIN (
                SELECT TOP (1) [o].[OrderID], [o].[ProductID]
                FROM [Order Details] AS [o]
                WHERE [o].[Quantity] = 1) as [t1] ON
                        [p].[ProductID] = [t1].[ProductID]
```

**Comment by divega** [comment]
This should also work:

``` SQL
SELECT [p].[ProductId], [p].[Discontinued], [p].[ProductName], [p].[UnitsInStock]
FROM [Products] AS [p]
WHERE (
        SELECT 1 
        FROM (
                SELECT TOP (1) [o].[ProductID]
                FROM [Order Details] AS [o]
                WHERE [o].[Quantity] = 1) AS [t1]
         WHERE  [p].[ProductID] = [t1].[ProductID]) = 1;
```

**Comment by mikary** [comment]
Had a discussion with @divega on the implementation for this issue. The eventual goal is to have simple SQL (i.e. the single join between `Products` and `Order Details`). To get to the final implementation, there are a few intermediate steps that need to be taken:
 - Implement a solution that produces correct output (i.e. the exists with inner join example I proposed) - This should be sufficient to address the high priority data corruption issue.
 - Resolve #4304 - Optimization to remove extra casting logic from the query
 - Open a new issue to eliminate the inner join - Both inner select statements are on the same table, should be able to combine the clauses into a single subquery.

**Comment by mikary** [comment]
Created #4389 to track inner join optimization
