### ISSUE TITLE
Conventions: Make key properties required

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#1978]
Problem seems to be that upon rename we create nullable column which then can't be made a Primary key.

Configuration before:

```

    public class GearsOfWarContext : DbContext
    {
        public GearsOfWarContext()
        {
        }

        public DbSet<City> Cities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Beta4Bash_Migrations", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>().Key(e => e.Name).ForRelational().Name("Foobar");
            modelBuilder.Entity<City>().Property(e => e.LocationChange);
            modelBuilder.Entity<City>().Property(e => e.LocationChange).MaxLength(40);

            modelBuilder.Entity<City>().Property<DateTime>("Shadow");
        }
    }

    public class City
    {
        public string Name { get; set; }
        public int LocationChange { get; set; }
    }
```

Configuration after:

```

    public class GearsOfWarContext : DbContext
    {
        public GearsOfWarContext()
        {
        }

        public DbSet<City> Cities { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Beta4Bash_Migrations", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<City>().Key(e => e.NameId).ForRelational().Name("Foobar");
            modelBuilder.Entity<City>().Property(e => e.LocationChange);
            modelBuilder.Entity<City>().Property(e => e.LocationChange).MaxLength(40);

            modelBuilder.Entity<City>().Property<DateTime>("Shadow");
        }
    }

    public class City
    {
        public string NameId { get; set; }
        public int LocationChange { get; set; }
    }
```

Migration:

```
        public override void Up(MigrationBuilder migration)
        {
            migration.DropPrimaryKey(name: "Foobar", table: "City");
            migration.DropColumn(name: "Name", table: "City");
            migration.AddColumn(
                name: "NameId",
                table: "City",
                type: "nvarchar(450)",
                nullable: true);
            migration.AddPrimaryKey(
                name: "Foobar",
                table: "City",
                column: "NameId");
        }
        
        public override void Down(MigrationBuilder migration)
        {
            migration.DropPrimaryKey(name: "Foobar", table: "City");
            migration.DropColumn(name: "NameId", table: "City");
            migration.AddColumn(
                name: "Name",
                table: "City",
                type: "nvarchar(450)",
                nullable: true);
            migration.AddPrimaryKey(
                name: "Foobar",
                table: "City",
                column: "Name");
        }
```

Exception:

System.Data.SqlClient.SqlException (0x80131904): Cannot define PRIMARY KEY constraint on nullable column in table 'City'.
At line:1 char:1
+ dnx . ef migration apply
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.Data.Sql...n table 'City'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Could not create constraint. See previous errors.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean 
breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.<>c__DisplayClass7_0.<ExecuteNonQuery>b__0()
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.Execute(IRelationalConnection connection, Func`1 action)
   at Microsoft.Data.Entity.Relational.SqlStatementExecutor.ExecuteNonQuery(IRelationalConnection connection, DbTransaction transaction, IEnumerable`1 sqlBatches)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.Execute(IEnumerable`1 sqlBatches, Boolean ensureDatabase)
   at Microsoft.Data.Entity.Relational.Migrations.Migrator.ApplyMigrations(String targetMigration)
   at Microsoft.Data.Entity.Commands.MigrationTool.ApplyMigration(String migrationName, String contextTypeName)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass10_0.<ApplyMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func`1 invoke)
   at Microsoft.Data.Entity.Commands.Program.ApplyMigration(String migration, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_2.<Main>b__8()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
ClientConnectionId:73c919fd-63dc-4c08-8b6d-ed1f32af40dc

**Comment by bricelam** [comment]
It looks like this is a model snapshot bug. `.Required()` is not being scaffolded.

**Comment by smitpatel** [comment]
Sql generated before rename
```sql
CREATE TABLE [City] (
    [Name] nvarchar(450),
    [LocationChange] int NOT NULL,
    [Shadow] datetime2 NOT NULL,
    CONSTRAINT [Foobar] PRIMARY KEY ([Name])
);
```

Sql generated after rename
```sql
ALTER TABLE [City] DROP CONSTRAINT [Foobar];
ALTER TABLE [City] DROP COLUMN [Name];
ALTER TABLE [City] ADD [NameId] nvarchar(450);
ALTER TABLE [City] ADD CONSTRAINT [Foobar] PRIMARY KEY ([NameId]);
```
In neither case the column `Name` is marked as `NOT NULL`. But SqlServer does following during Create Table. 
>All columns defined within a PRIMARY KEY constraint must be defined as NOT NULL. If nullability is not specified, all columns participating in a PRIMARY KEY constraint have their nullability set to NOT NULL.

Though above doesn't happen during Alter Table operation so migration apply fails only after rename and not before.

**Comment by smitpatel** [comment]
When we set PK we don't mark underlying properties to be non-nullable. so model snapshot does not scaffold `Required()` for them. That should be changed.

**Comment by bricelam** [comment]
@smitpatel Ah, yes. We use to have that convention--marking PKs as non-nullable--in EF6. I'll update the title.
