### ISSUE TITLE
Using a DB Context that Extends IdentityDbContext<TUser, TRole, TKey> where TKey: Guid causes an error on add migration

### ISSUE THREAD

**Issue by mgolus** [aspnet/EntityFramework#2099]
If using a DB Context that extends IdentityDbContext<TUser, TRole, TKey> and TKey is a Guid or an int, the following error happens on add migration:

"No data stores are configured. Configure a data store by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services."

This can be repeated by starting with a ASP.Net 5 web project created with Visual Studio 2015 RC and using the ApplicationUser and Role models and the ApplicationDbContext shown below:

    public class ApplicationUser : IdentityUser<Guid>
    {
        public ApplicationUser()
        {
        }
    }

    public class ApplicationRole : IdentityRole<Guid>
    {
        public ApplicationRole()
        {
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser, ApplicationRole, Guid>
    {
      ...
    }

And initializing the service in the Startup.cs file by using
    
    services.AddEntityFramework()
                .AddSqlServer()
                .AddDbContext<ApplicationDbContext>(options =>
                    options.UseSqlServer(Configuration["Data:DefaultConnection:ConnectionString"]));

**Comment by rowanmiller** [comment]
**Note for Triage** Verified that this is a legitimate issue and does not have anything to do with database initialization logic. The error starts showing up when you swap to the Guid key type. Note that if you replace the `Guid` types with `string` the migrations succeed.

Here is the full exception details:

> System.InvalidOperationException: No data stores are configured. Configure a data store by overriding OnConfiguring in your DbContext class or in the AddDbContext method when setting up services.
   at Microsoft.Data.Entity.Storage.DataStoreSelector.SelectDataStore(ServiceProviderSource providerSource)
   at Microsoft.Data.Entity.Internal.DbContextServices.<>c__DisplayClass6_0.<Initialize>b__0()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Framework.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Framework.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.<>c__DisplayClass8_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Data.Entity.Commands.DesignTimeServices.GetService(Type serviceType)
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Data.Entity.Commands.MigrationTool.CreateScaffolder(IServiceProvider services)
   at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String rootNamespace, String projectDir)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass9_0.<AddMigration>b__1()
   at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func`1 invoke)
   at Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_1.<Main>b__6()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)

**Comment by bricelam** [comment]
I think this is an Identity bug. Taking Migrations completely out of the picture, I'm getting the following exception at runtime:
```
System.ArgumentException: GenericArguments[0], 'WebApplication1.Models.ApplicationUser', on 'Microsoft.AspNet.Identity.EntityFramework.UserStore`3[TUser,TRole,TContext]' violates the constraint of type 'TUser'. ---> System.TypeLoadException: GenericArguments[0], 'WebApplication1.Models.ApplicationUser', on 'Microsoft.AspNet.Identity.EntityFramework.UserStore`4[TUser,TRole,TContext,TKey]' violates the constraint of type parameter 'TUser'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   --- End of inner exception stack trace ---
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.AspNet.Identity.IdentityEntityFrameworkServices.GetDefaultServices(Type userType, Type roleType, Type contextType, Type keyType)
   at Microsoft.Framework.DependencyInjection.IdentityEntityFrameworkBuilderExtensions.AddEntityFrameworkStores[TContext](IdentityBuilder builder)
   at WebApplication1.Startup.ConfigureServices(IServiceCollection services) in C:\Users\bricelam\Documents\Visual Studio 2015\Projects\WebApplication1\src\WebApplication1\Startup.cs:line 60
System.TypeLoadException: GenericArguments[0], 'WebApplication1.Models.ApplicationUser', on 'Microsoft.AspNet.Identity.EntityFramework.UserStore`4[TUser,TRole,TContext,TKey]' violates the constraint of type parameter 'TUser'.
   at System.RuntimeTypeHandle.Instantiate(RuntimeTypeHandle handle, IntPtr* pInst, Int32 numGenericArgs, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.Instantiate(Type[] inst)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
```

`IdentityEntityFrameworkServices` seems to be doing something wrong.

**Comment by bricelam** [comment]
This appears to be fixed in the latest builds. I had to add the following to my `Startup.cs` to get Identity to work properly.
```C#
services.AddIdentity<ApplicationUser, ApplicationRole>()
    .AddEntityFrameworkStores<ApplicationDbContext, Guid>()
    .AddDefaultTokenProviders();
```
