### ISSUE TITLE
A better error message when the a duplicate table name is used would be an improvement

### ISSUE THREAD

**Issue by vossad01** [aspnet/EntityFramework#2170]
Right now if you accidentally set two entities to point to the same table, adding a migration indicates:

```
modelBuilder.Entity<Something>( c => c.Table( "Something" ) );
modelBuilder.Entity<Sommat>( c => c.Table( "Something" ) );
```

> PM> Add-Migration Test
> An item with the same key has already been added.

This is not very descriptive of what is wrong.  A better error might at least indicate the key to help identify what the duplication is.  Better still would be to indicate the issue has to do with table names.

Stack trace from running with -Verbose:

> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.ModelDiffer.Sort(IEnumerable`1 operations)
   at Microsoft.Data.Entity.Relational.Migrations.Infrastructure.ModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.Data.Entity.Commands.Migrations.MigrationScaffolder.ScaffoldMigration(String migrationName, String rootNamespace)
   at Microsoft.Data.Entity.Commands.MigrationTool.AddMigration(String migrationName, String contextTypeName, String rootNamespace, String projectDir)
   at Microsoft.Data.Entity.Commands.Executor.<AddMigrationImpl>d__8.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Commands.Executor.OperationBase.<>c__DisplayClass6_0`1.<Execute>b__0()
   at Microsoft.Data.Entity.Commands.Executor.OperationBase.Execute(Action action)

EF 7.0.0-beta5-13171

**Comment by rowanmiller** [comment]
@smitpatel we should handle this in validation
