### ISSUE TITLE
Include tries to use PK rather than alternate key

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2181]
In a model that uses an alternate key Include still tries to join to the PK. This either results in incorrect SQL or an exception if the types don't match.

```csharp
using System.Collections.Generic;
using System.Linq;
using Microsoft.Data.Entity;

namespace ConsoleApp1
{
    public class Program
    {
        public void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                db.Database.EnsureCreated();
                db.TaxReturns.Include(r => r.Person).ToList();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        public DbSet<TaxReturn> TaxReturns { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder builder)
        {
            builder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;Trusted_Connection=True;MultipleActiveResultSets=True;");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.Entity<Person>()
                .Collection(p => p.TaxReturns)
                .InverseReference(r => r.Person)
                .ForeignKey(r => r.SSN)
                .PrincipalKey(p => p.SSN);
        }
    }

    public class Person
    {
        public int PersonId { get; set; }
        public string Name { get; set; }
        public string SSN { get; set; }

        public List<TaxReturn> TaxReturns { get; set; }
    }

    public class TaxReturn
    {
        public int TaxReturnId { get; set; }

        public string SSN { get; set; }
        public Person Person { get; set; }
    }
}
```

> System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=No coercion operator is defined between types 'System.Int32' and 'System.String'.
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
       at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
       at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpressionTreeVisitor.BuildJoinEqualityExpression(INavigation navigation, IReadOnlyList`1 primaryKeyProperties, TableExpressionBase targetTableExpression, TableExpressionBase joinExpression)
       at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpressionTreeVisitor.<CreateIncludeRelatedValuesStrategyFactories>d__7.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
       at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
       at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
       at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitLambdaExpression(LambdaExpression expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
       at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
       at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
       at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
       at Microsoft.Data.Entity.Relational.Query.ExpressionTreeVisitors.IncludeExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
       at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
       at Microsoft.Data.Entity.Query.ExpressionTreeVisitors.ExpressionTreeVisitorBase.VisitExpression(Expression expression)
       at Microsoft.Data.Entity.Relational.Query.RelationalQueryModelVisitor.IncludeNavigations(IQuerySource querySource, Type resultType, LambdaExpression accessorLambda, IReadOnlyList`1 navigationPath, Boolean querySourceRequiresTracking)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
       at Microsoft.Data.Entity.Relational.RelationalDataStore.CompileQuery[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDataStore dataStore, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__4`1.<Execute>b__4_0(Expression q, IDataStore ds)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__DisplayClass7_0.<GetOrAdd>b__0(ICacheSetContext c)
       at Microsoft.Framework.Caching.Memory.CacheExtensions.<>c__DisplayClass7_0`1.<Set>b__0(ICacheSetContext context)
       at Microsoft.Framework.Caching.Memory.MemoryCache.Set(String key, IEntryLink link, Object state, Func`2 create)
       at Microsoft.Framework.Caching.Memory.CacheExtensions.Set[T](IMemoryCache cache, String key, Object state, Func`2 create)
       at Microsoft.Framework.Caching.Memory.CacheExtensions.GetOrSet[T](IMemoryCache cache, String key, Object state, Func`2 create)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDataStore dataStore, Boolean isAsync, Func`3 compiler)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDataStore dataStore, QueryContext queryContext)
       at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at ConsoleApp1.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 14\Projects\ConsoleApp1\src\ConsoleApp1\Program.cs:line 14
  InnerException:

**Comment by maumar** [comment]
fixed in 1abc91f49680cc2bb6d3c6b7bad5854091e2b6d7
