### ISSUE TITLE
SQLite DDL fails on Windows 10 UAP

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#2184]
SQL Generation throws InvalidOperationException (full details below) for a simple model on Windows 10 UAP. Using CreateTables is the easiest way to repro this.

## Model
```csharp
public class OrdersContext : DbContext
{
    public DbSet<Order> Orders { get; set; }
    public DbSet<OrderLine> OrderLines { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var file = Path.Combine(ApplicationData.Current.LocalFolder.Path, "Orders.db");
        optionsBuilder.UseSqlite("Data Source=" + file);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<OrderLine>()
            .Key(l => new { l.OrderId, l.ProductId });
    }
}

public class Order
{
    public bool IsShipped { get; set; }
    public bool IsShippingSynced { get; set; }
    public int OrderId { get; set; }
    public string Addressee { get; set; }
    public string LineOne { get; set; }
    public string LineTwo { get; set; }
    public string CityOrTown { get; set; }
    public string StateOrProvince { get; set; }
    public string ZipOrPostalCode { get; set; }
    public string Country { get; set; }

    public List<OrderLine> Lines { get; set; }
}

public class OrderLine
{
    public bool IsPacked { get; set; }
    public int OrderId { get; set; }
    public int ProductId { get; set; }
    public string ProductName { get; set; }
    public int Quantity { get; set; }
}
```
## Error
> System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=The API 'System.Reflection.MemberInfo.get_MetadataToken()' cannot be used on the current platform. See http://go.microsoft.com/fwlink/?LinkId=248273 for more information.
  Source=mscorlib
  StackTrace:
       at System.Reflection.Emit.DynamicILGenerator.GetTokenFor(RuntimeMethodInfo rtMeth)
       at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, MethodInfo meth)
       at System.Linq.Expressions.Compiler.LambdaCompiler.EmitCall(Type objectType, MethodInfo method)
       at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberGet(MemberInfo member, Type objectType)
       at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberExpression(Expression expr)
       at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
       at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
       at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody()
       at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
       at Microsoft.CSharp.RuntimeBinder.RuntimeBinderExtensions.HasSameMetadataDefinitionAs(MemberInfo mi1, MemberInfo mi2)
       at Microsoft.CSharp.RuntimeBinder.SymbolTable.<>c__DisplayClass4.<BuildDeclarationChain>b__5(MethodInfo m)
       at System.Linq.Enumerable.WhereArrayIterator`1.MoveNext()
       at Microsoft.CSharp.RuntimeBinder.SymbolTable.BuildDeclarationChain(Type callingType)
       at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
       at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(Type type, AggregateSymbol agg)
       at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
       at Microsoft.CSharp.RuntimeBinder.SymbolTable.AddMethodToSymbolTable(MemberInfo member, AggregateSymbol callingAggregate, MethodKindEnum kind)
       at Microsoft.CSharp.RuntimeBinder.SymbolTable.AddPredefinedMethodToSymbolTable(AggregateSymbol type, Name methodName)
       at Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.LoadMethod(AggregateSymbol type, Int32[] signature, Int32 cMethodTyVars, Name methodName, ACCESS methodAccess, Boolean isStatic, Boolean isVirtual)
       at Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.LoadMethod(PREDEFMETH method)
       at Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.EnsureMethod(PREDEFMETH method)
       at Microsoft.CSharp.RuntimeBinder.Semantics.PredefinedMembers.GetMethod(PREDEFMETH method)
       at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.GetPreDefMethod(PREDEFMETH pdm)
       at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.VisitBOUNDLAMBDA(EXPRBOUNDLAMBDA anonmeth)
       at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Dispatch(EXPR pExpr)
       at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.Dispatch(EXPR expr)
       at Microsoft.CSharp.RuntimeBinder.Semantics.ExprVisitorBase.Visit(EXPR pExpr)
       at Microsoft.CSharp.RuntimeBinder.Semantics.ExpressionTreeRewriter.Rewrite(EXPR expr, ExprFactory expressionFactory, SymbolLoader symbolLoader)
       at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateExpressionTreeFromResult(IEnumerable`1 parameters, ArgumentObject[] arguments, Scope pScope, EXPR pResult)
       at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
       at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, IEnumerable`1 parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
       at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, IEnumerable`1 args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
       at Microsoft.CSharp.RuntimeBinder.CSharpInvokeMemberBinder.FallbackInvokeMember(DynamicMetaObject target, DynamicMetaObject[] args, DynamicMetaObject errorSuggestion)
       at System.Dynamic.DynamicMetaObject.BindInvokeMember(InvokeMemberBinder binder, DynamicMetaObject[] args)
       at System.Dynamic.InvokeMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
       at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
       at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
       at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
       at Microsoft.Data.Entity.Relational.Migrations.Sql.MigrationSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
       at Microsoft.Data.Entity.Sqlite.SqliteDataStoreCreator.CreateTables(IModel model)
       at Microsoft.Data.Entity.Relational.RelationalDatabase.CreateTables()
       at UnicornPacker.App.OnLaunched(LaunchActivatedEventArgs e)
  InnerException:

**Comment by bricelam** [comment]
I suspect this is due to my gratuitous use of `dynamic`.

**Comment by bricelam** [comment]
This appears to be fixed on the latest builds of the Windows 10 Tools.
