### ISSUE TITLE
FromSql: Crash when composing multiple calls

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#2185]
```c#
// FromSqlQueryTestBase.cs
public virtual void From_sql_queryable_multiple_composed()
{
	using (var context = CreateContext())
	{
		var actual
			= (from c in context.Set<Customer>().FromSql("SELECT * FROM Customers")
				from o in context.Set<Order>().FromSql("SELECT * FROM Orders")
				where c.CustomerID == o.CustomerID
				select new { c, o })
				.ToArray();
	}
}
```

Results in:

Test 'Microsoft.Data.Entity.SqlServer.FunctionalTests.FromSqlQuerySqlServerTest.From_sql_queryable_multiple_composed' failed:
	System.ArgumentException : Expression of type 'Microsoft.Data.Entity.Query.EntityQueryable`1[Microsoft.Data.Entity.FunctionalTests.TestModels.Northwind.Order]' cannot be used for parameter of type 'Microsoft.Data.Entity.DbSet`1[Microsoft.Data.Entity.FunctionalTests.TestModels.Northwind.Order]' of method 'System.Linq.IQueryable`1[Microsoft.Data.Entity.FunctionalTests.TestModels.Northwind.Order] FromSql[Order](Microsoft.Data.Entity.DbSet`1[Microsoft.Data.Entity.FunctionalTests.TestModels.Northwind.Order], System.String)'
	at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
	at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
	at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitors.PartialEvaluatingExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitLambdaExpression(LambdaExpression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitors.PartialEvaluatingExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitUnaryExpression(UnaryExpression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitors.PartialEvaluatingExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitors.PartialEvaluatingExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitors.PartialEvaluatingExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](T expression, String methodName)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.<>c__DisplayClass6`1.<VisitAndConvert>b__5(T expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitList[T](ReadOnlyCollection`1 list, Func`2 visitMethod)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitAndConvert[T](ReadOnlyCollection`1 expressions, String callerName)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitMethodCallExpression(MethodCallExpression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitors.PartialEvaluatingExpressionTreeVisitor.VisitExpression(Expression expression)
	at Remotion.Linq.Parsing.ExpressionTreeVisitors.PartialEvaluatingExpressionTreeVisitor.EvaluateIndependentSubtrees(Expression expressionTree)
	at Remotion.Linq.Parsing.Structure.ExpressionTreeProcessors.PartialEvaluatingExpressionTreeProcessor.Process(Expression expressionTree)
	at Remotion.Linq.Parsing.Structure.ExpressionTreeProcessors.CompoundExpressionTreeProcessor.<Process>b__0(Expression expr, IExpressionTreeProcessor processor)
	at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
	at Remotion.Linq.Parsing.Structure.ExpressionTreeProcessors.CompoundExpressionTreeProcessor.Process(Expression expressionTree)
	at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
	at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
	Query\CompiledQueryCache.cs(58,0): at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__4`1.<Execute>b__4_0(Expression q, IDataStore ds)
	Query\CompiledQueryCache.cs(158,0): at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__DisplayClass7_0.<GetOrAdd>b__0(ICacheSetContext c)
	at Microsoft.Framework.Caching.Memory.CacheExtensions.<>c__DisplayClass7_0`1.<Set>b__0(ICacheSetContext context)
	at Microsoft.Framework.Caching.Memory.MemoryCache.Set(String key, IEntryLink link, Object state, Func`2 create)
	at Microsoft.Framework.Caching.Memory.CacheExtensions.Set[T](IMemoryCache cache, String key, Object state, Func`2 create)
	at Microsoft.Framework.Caching.Memory.CacheExtensions.GetOrSet[T](IMemoryCache cache, String key, Object state, Func`2 create)
	Query\CompiledQueryCache.cs(150,0): at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDataStore dataStore, Boolean isAsync, Func`3 compiler)
	Query\CompiledQueryCache.cs(55,0): at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDataStore dataStore, QueryContext queryContext)
	Query\EntityQueryProvider.cs(71,0): at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	FromSqlQueryTestBase.cs(34,0): at Microsoft.Data.Entity.Relational.FunctionalTests.FromSqlQueryTestBase`1.From_sql_queryable_multiple_composed()
	FromSqlQuerySqlServerTest.cs(44,0): at Microsoft.Data.Entity.SqlServer.FunctionalTests.FromSqlQuerySqlServerTest.From_sql_queryable_multiple_composed()

**Comment by mikary** [comment]
It looks like the root cause here is that ```AsNoTracking``` and ```FromSql``` are now implemented by calling ```AnnotateQuery``` and not actually being registered as supported methods in the expression node. As a result, when these annotations are used in a closure, the parser is unable to resolve them.

We should be able to continue using the same ```ResultOperator``` for all of the query annotations, but the simple solution (explicitly supporting each of these operators in the node) would mean there cannot be provider-specific query annotation operators at this time
