### ISSUE TITLE
No value generator is available for properties of type 'char'

### ISSUE THREAD

**Issue by GetoXs** [aspnet/EntityFramework#2217]
I am working on EF '7.0.0-beta4', and during insert data into database, I'm getting error as below.
My question is, How should I configure a value generator for properties of type 'char' or when do you plan to implement this functionality.

```C#
System.NotSupportedException occurred
  HResult=-2146233067
  Message=The 'Letter' on entity type 'GameSessionLetter' does not have a value set and no value generator is available for properties of type 'Char'. Either set a value for the property before adding the entity or configure a value generator for properties of type 'Char'.
  Source=EntityFramework.Core
  StackTrace:
       at Microsoft.Data.Entity.ValueGeneration.ValueGeneratorSelector.Create(IProperty property)
       at Microsoft.Data.Entity.SqlServer.SqlServerValueGeneratorSelector.Create(IProperty property)
       at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKey key, Func`2 factory)
       at Microsoft.Data.Entity.ValueGeneration.ValueGeneratorCache.GetOrAdd(IProperty property, Func`2 factory)
       at Microsoft.Data.Entity.SqlServer.SqlServerValueGeneratorSelector.Select(IProperty property)
       at Microsoft.Data.Entity.ChangeTracking.Internal.ValueGenerationManager.MayGetTemporaryValue(IProperty property)
       at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.MayGetStoreValue(IProperty property)
       at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.MayGetStoreValue()
       at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.PrepareToSave()
       at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__27_1(InternalEntityEntry e)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges()
       at Microsoft.Data.Entity.DbContext.SaveChanges()
       at WordServer.Controllers.Controllers.GameController.AddGameSession(GameSession gs) in Z:\Projekty\Word_Circle\WordServer\src\WordServer\Controllers\GameController.cs:line 236
  InnerException: 
```

My model:
```C#
    public class GameSessionLetter
	{
		public long Id { get; set; }

		[Required]
        public char Letter { get; set; }

		[Required]
		public long GameSessionId { get; set; }

		public GameSession GameSession { get; set; }
	}
```

Generated migration:
```C#
            migration.CreateTable(
                name: "GameSessionLetter",
                columns: table => new
                {
                    GameSessionId = table.Column(type: "bigint", nullable: false),
                    Id = table.Column(type: "bigint", nullable: false),
                    Letter = table.Column(type: "nchar", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_GameSessionLetter", x => new { x.Letter, x.GameSessionId });
                    table.ForeignKey(
                        name: "FK_GameSessionLetter_GameSession_GameSessionId",
                        columns: x => x.GameSessionId,
                        referencedTable: "GameSession",
                        referencedColumn: "Id");
                });
```

**Comment by rowanmiller** [comment]
Should already be fixed in Beta5 code base, @ajcvickers to double check

**Comment by ajcvickers** [comment]
Looks like "char" got missed. I will add it, but note that we don't yet support "char" properties when mapping to SQL Server anyway. It should work if you use a string property.
