### ISSUE TITLE
Use start-up project for  ConfigureServices 

### ISSUE THREAD

**Issue by moozzyk** [aspnet/EntityFramework#2219]
I am trying to set up a project where the business logic (including data model) is separated from UI/web. The context has only a ctor that takes only `DbContextOptions` because I want to use `InMemoryStore` for tests and SqlServer when actually running the app. I am trying to add a migration from the "engine" project and provide the web project as the start up project since this is where I configure EF to use SqlServer (in the `ConfigureServices` method). This is on Beta4 bits.

`dnx . ef migration add initial -s StarTrader`

```
Information: [LoaderContainer]: Load name=EntityFramework.Relational
Information: [NuGetAssemblyLoader]: Loaded name=EntityFramework.Relational in 3ms
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Entity.Commands.Program.GetProjectPath(String projectName)
   at Microsoft.Data.Entity.Commands.Program.ExecuteInDirectory(String startupProject, Func`1 invoke)
   at Microsoft.Data.Entity.Commands.Program.AddMigration(String name, String context, String startupProject)
   at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass7_1.<Main>b__6()
   at Microsoft.Framework.Runtime.Common.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.Data.Entity.Commands.Program.Main(String[] args)
```

There is a recent [change](#f3749bd69672d1bcb0e2d977f5509471b0faf4d9) that touched this code so it might be already fixed in beta5

**Comment by bricelam** [comment]
The start-up project still isn't used for `ConfigureServices`. This work is part of #639
