### ISSUE TITLE
Chaining multiple Include with ThenInclude throws System.InvalidOperationException

### ISSUE THREAD

**Issue by nicbourgoin** [aspnet/EntityFramework#2274]
Summary:

var field = context.Fields
   .Include(x => x.Label.Globalizations)
   .ThenInclude(x => x.Language)
   .Include(x => x.Placeholder.Globalizations)
   .ThenInclude(x => x.Language)
   .ToList();

I get the following exception thrown:

System.InvalidOperationException Invalid attempt to read when no data is present.

I asked the question on stackoverflow @
http://stackoverflow.com/questions/30407829/chaining-multiple-include-with-theninclude-throws-system-invalidoperationexcepti

**Comment by anpete** [comment]
Hi @nicbourgoin, can you post the full stack trace?

**Comment by nicbourgoin** [comment]
@anpete 

InvalidOperationException: Invalid attempt to read when no data is present.

System.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn, Boolean permitAsync, String methodName)


System.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)


System.Data.SqlClient.SqlDataReader.GetValues(Object[] values)


Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReader..ctor(DbDataReader dataReader)


Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReaderFactory.Create(DbDataReader dataReader)


Microsoft.Data.Entity.Relational.Query.RelationalQueryContext.CreateValueReader(Int32 readerIndex)


Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.ReferenceIncludeRelatedValuesStrategy.<GetRelatedValues>d__5.MoveNext()


System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()


System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()


System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)


System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)


Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean querySourceRequiresTracking)


Microsoft.Data.Entity.Query.QueryBuffer.<>c__DisplayClass12_0.<Include>b__0(EntityLoadInfo eli)


System.Linq.Enumerable.<>c__DisplayClass2`3.<CombineSelectors>b__3(TSource x)


System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()


System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()


System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)


System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)


Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean querySourceRequiresTracking)


Microsoft.Data.Entity.Query.QueryBuffer.<>c__DisplayClass12_0.<Include>b__0(EntityLoadInfo eli)


System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()


System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()


System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)


System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)


Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean querySourceRequiresTracking)


Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Boolean querySourceRequiresTracking)


Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.<>c__DisplayClass11_0`1.<_Include>b__2(T qss)


System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()


Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.<Finally>d__0`1.MoveNext()


System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()


Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.<Finally>d__0`1.MoveNext()


System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()


System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()


Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()


System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)


System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)


RFWA.Services.Generic.Service`2.List(Expression`1[] includeProperties) in Service.cs

63.		public int Count => _repository.Query().Count();64.65.	    public IList<T> List(params Expression<Func<T, object>>[] includeProperties)66.		{67.	        if (includeProperties?.Length > 0 && _repository.Query(includeProperties).Any())68.	        {69.				return _repository.Query(includeProperties).ToList();70.            }71.72.			return _repository.Query().ToList();73.		}74.75.		#endregion

Castle.Proxies.Invocations.IService`2_List.InvokeMethodOnTarget()


Castle.DynamicProxy.AbstractInvocation.Proceed()


Castle.Proxies.IService`2Proxy.List(Expression`1[] includeProperties)


RFWA.WebApplication.Controllers.api.CustomFieldsController.Get() in CustomFieldsController.cs

26.        [HttpGet]27.        public object Get()28.        {29.            var fieldService = _facade.GetGenericService<Field, int>();30.            var fieldTypeService = _facade.GetGenericService<FieldType, int>();31.32.            var fields = fieldService.List(x => x.Tooltip.Globalizations.Select(g => g.Language), x => x.Label.Globalizations.Select(g => g.Language), x => x.Placeholder.Globalizations.Select(g => g.Language));33.            var fieldTypes = fieldTypeService.List(ft => ft.MultilingualString.Globalizations.Select(g => g.Language));34.35.            return new36.            {37.                CustomFields = FieldFactory.CreateVms(fields),38.                FieldTypes = FieldTypeFactory.CreateVms(fieldTypes)

--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__3.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()


Microsoft.AspNet.Mvc.ControllerActionExecutor.<ExecuteAsync>d__2.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()


Microsoft.AspNet.Mvc.Core.ControllerActionInvoker.<InvokeActionAsync>d__7.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()


Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Mvc.Core.FilterActionInvoker.<InvokeAsync>d__32.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.MvcRouteHandler.<InvokeActionAsync>d__3.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.MvcRouteHandler.<RouteAsync>d__2.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__25.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Authentication.AuthenticationMiddleware`1.<Invoke>d__10.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


System.Threading.Tasks.EntityFrameworkTaskExtensions.CultureAwaiter.GetResult()


Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


Microsoft.AspNet.Diagnostics.Entity.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()


--- End of stack trace from previous location where exception was thrown ---


System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)


System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)


System.Runtime.CompilerServices.TaskAwaiter.GetResult()


Microsoft.AspNet.Diagnostics.ErrorPageMiddleware.<Invoke>d__4.MoveNext()

**Comment by makcakaya** [comment]
A little easier on the eyes:

```
System.InvalidOperationException
Invalid attempt to read when no data is present.
C:\Users\nicolas.bourgoin\Documents\Visual Studio 2015\Projects\rfwa\src\Application\RFWA.WebApplication\Configurations\Extensions\RfwaContextSeeder.cs
Line 21: {
Line 22:

Line 23: var field =
Line 24: context.Fields
Line 25: .Include(x => x.Label.Globalizations)
at System.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn, Boolean permitAsync, String methodName) 
at System.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn) 
at System.Data.SqlClient.SqlDataReader.GetValues(Object[] values) 
at Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReader..ctor(DbDataReader dataReader) 
at Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReaderFactory.Create(DbDataReader dataReader) 
at Microsoft.Data.Entity.Relational.Query.RelationalQueryContext.CreateValueReader(Int32 readerIndex) 
at Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.ReferenceIncludeRelatedValuesStrategy.d__5.MoveNext() 
at System.Linq.Enumerable.WhereSelectEnumerableIterator.MoveNext() 
at System.Linq.Enumerable.WhereEnumerableIterator.MoveNext() 
at System.Collections.Generic.List..ctor(IEnumerable collection) 
at System.Linq.Enumerable.ToList(IEnumerable source) 
at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList navigationPath, IReadOnlyList relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean querySourceRequiresTracking) 
at Microsoft.Data.Entity.Query.QueryBuffer.<>c__DisplayClass12_0.b__0(EntityLoadInfo eli) 
at System.Linq.Enumerable.<>c__DisplayClass2.b__3(TSource x) 
at System.Linq.Enumerable.WhereSelectEnumerableIterator.MoveNext() 
at System.Linq.Enumerable.WhereEnumerableIterator.MoveNext() 
at System.Collections.Generic.List..ctor(IEnumerable collection) 
at System.Linq.Enumerable.ToList(IEnumerable source) 
at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList navigationPath, IReadOnlyList relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean querySourceRequiresTracking) 
at Microsoft.Data.Entity.Query.QueryBuffer.<>c__DisplayClass12_0.b__0(EntityLoadInfo eli) 
at System.Linq.Enumerable.WhereSelectEnumerableIterator.MoveNext() 
at System.Linq.Enumerable.WhereEnumerableIterator.MoveNext() 
at System.Collections.Generic.List..ctor(IEnumerable collection) 
at System.Linq.Enumerable.ToList(IEnumerable source) 
at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList navigationPath, IReadOnlyList relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean querySourceRequiresTracking) 
at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList navigationPath, IReadOnlyList relatedEntitiesLoaders, Boolean querySourceRequiresTracking) 
at Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.<>c__DisplayClass11_0.<_Include>b__2(T qss) 
at System.Linq.Enumerable.WhereSelectEnumerableIterator.MoveNext() 
at Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.d__0.MoveNext() 
at System.Linq.Enumerable.WhereSelectEnumerableIterator.MoveNext() 
at Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.d__0.MoveNext() 
at System.Linq.Enumerable.d__1.MoveNext() 
at System.Linq.Enumerable.WhereSelectEnumerableIterator.MoveNext() 
at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor.EnumeratorExceptionInterceptor.MoveNext() 
at System.Collections.Generic.List..ctor(IEnumerable collection) 
at System.Linq.Enumerable.ToList(IEnumerable source) 
at RFWA.WebApplication.Configurations.Extensions.RfwaContextSeeder.Seed(RfwaContext context) in C:\Users\nicolas.bourgoin\Documents\Visual Studio 2015\Projects\rfwa\src\Application\RFWA.WebApplication\Configurations\Extensions\RfwaContextSeeder.cs:line 23 
at RFWA.WebApplication.Configurations.Extensions.EntityFrameworkServiceBuilderExtensions.UseDataInitializer(IApplicationBuilder app) in C:\Users\nicolas.bourgoin\Documents\Visual Studio 2015\Projects\rfwa\src\Application\RFWA.WebApplication\Configurations\Extensions\EntityFrameworkServiceBuilderExtensions.cs:line 116
at RFWA.WebApplication.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerfactory) in C:\Users\nicolas.bourgoin\Documents\Visual Studio 2015\Projects\rfwa\src\Application\RFWA.WebApplication\Startup.cs:line 164
System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) 
at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) 
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) 
at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) 
at Microsoft.AspNet.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder) 
at Microsoft.AspNet.Hosting.Startup.ConfigureBuilder.<>c__DisplayClass4_0.b__0(IApplicationBuilder builder) 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.HeliosStartupFilter.<>c__DisplayClass0_0.b__0(IApplicationBuilder builder) 
at Microsoft.AspNet.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.b__0(IApplicationBuilder builder) 
at Microsoft.AspNet.Hosting.HostingEngine.EnsureApplicationDelegate(HostingContext context) 
at Microsoft.AspNet.Hosting.HostingEngine.Start(HostingContext context) 
at Microsoft.AspNet.Loader.IIS.RuntimeHttpApplication.ApplicationStart(IHttpApplication application) 
at Microsoft.AspNet.Loader.IIS.HttpApplicationBase.InvokeApplicationStart(IHttpApplication application)
```

**Comment by maumar** [comment]
In the current bits it throws NRE:

Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at Microsoft.Data.Entity.Storage.ValueBuffer.get_Item(Int32 index) in D:\k\EntityFramework\src\EntityFramework.Core\Storage\ValueBuffer.cs:line 31
   at Microsoft.Data.Entity.ChangeTracking.Internal.SimpleEntityKeyFactory`1.Create(IEntityType entityType, IReadOnlyList`1 properties, ValueBuffer valueBuffer)
 in D:\k\EntityFramework\src\EntityFramework.Core\ChangeTracking\Internal\SimpleEntityKeyFactory.cs:line 22
   at Microsoft.Data.Entity.Query.QueryBuffer.<>c__DisplayClass14_0.<Include>b__0(EntityLoadInfo eli) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryBuffer.cs:line 225
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryBuffer.cs:line 218
   at Microsoft.Data.Entity.Query.QueryBuffer.<>c__DisplayClass14_0.<Include>b__0(EntityLoadInfo eli) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryBuffer.cs:line 241
   at System.Linq.Enumerable.<>c__DisplayClass2`3.<CombineSelectors>b__3(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryBuffer.cs:line 218
   at Microsoft.Data.Entity.Query.QueryBuffer.<>c__DisplayClass14_0.<Include>b__0(EntityLoadInfo eli) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryBuffer.cs:line 241
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Int32 currentNavigationIndex, Boolean queryStateManager) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryBuffer.cs:line 218
   at Microsoft.Data.Entity.Query.QueryBuffer.Include(Object entity, IReadOnlyList`1 navigationPath, IReadOnlyList`1 relatedEntitiesLoaders, Boolean queryStateManager) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryBuffer.cs:line 182
   at Microsoft.Data.Entity.Relational.Query.QueryMethodProvider.<>c__DisplayClass15_0`1.<_Include>b__2(T qss) in D:\k\EntityFramework\src\EntityFramework.Relational\Query\QueryMethodProvider.cs:line 110
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Relational.Utilities.EnumerableExtensions.<Finally>d
__0`1.MoveNext() in D:\k\EntityFramework\src\EntityFramework.Relational\Utilitie
s\EnumerableExtensions.cs:line 15
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in D:\k\EntityFramework\src\EntityFramework.Core\Query\LinqOperatorProvider.cs:line 144
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)

**Comment by maumar** [comment]
Standalone repro:

```
    public class MyContext : DbContext
    {
        public DbSet<Field> Fields { get; set; }
        public DbSet<MultilingualString> MultilingualStrings { get; set; }
        public DbSet<Globalization> Globalizations { get; set; }
        public DbSet<Language> Languages { get; set; }

        protected override void OnConfiguring(EntityOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Repro2274", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }


        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Field>().Key(e => e.Name);
            modelBuilder.Entity<MultilingualString>().Key(e => e.DefaultText);
            modelBuilder.Entity<Globalization>().Key(e => e.Text);
            modelBuilder.Entity<Language>().Key(e => e.Name);

            modelBuilder.Entity<Field>().Reference(f => f.Label);
            modelBuilder.Entity<Field>().Reference(f => f.Placeholder);

            modelBuilder.Entity<MultilingualString>().Collection(m => m.Globalizations);

            modelBuilder.Entity<Globalization>().Reference(g => g.Language);
        }
    }

    public class Field
    {
        public string Name { get; set; }
        public MultilingualString Label { get; set; }
        public MultilingualString Placeholder { get; set; }
    }

    public class MultilingualString
    {
        public string DefaultText { get; set; }
        public IList<Globalization> Globalizations { get; set; }
    }

    public class Globalization
    {
        public string Text { get; set; }
        public Language Language { get; set; }
    }

    public class Language
    {
        public string Name { get; set; }
        public string CultureString { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();
                for (int i = 0; i < 10; i++)
                {
                    var language = new Language { Name = "Language" + i, CultureString = "Foo" + i };
                    ctx.Languages.Add(language);
                }

                ctx.SaveChanges();

                int ii = 0;
                foreach (var l in ctx.Languages)
                {
                    var globalization = new Globalization { Text = "Globalization" + ii, Language = l };
                    ii++;

                    ctx.Globalizations.Add(globalization);
                }

                ctx.SaveChanges();

                var globs = ctx.Globalizations.ToList();

                var mls1 = new MultilingualString { DefaultText = "MLS1", Globalizations = globs.Take(3).ToList() };
                var mls2 = new MultilingualString { DefaultText = "MLS2", Globalizations = globs.Skip(3).Take(3).ToList() };
                var mls3 = new MultilingualString { DefaultText = "MLS3", Globalizations = globs.Skip(6).Take(3).ToList() };
                var mls4 = new MultilingualString { DefaultText = "MLS4", Globalizations = globs.Skip(9).ToList() };

                ctx.MultilingualStrings.AddRange(new[] { mls1, mls2, mls3, mls4 });
                ctx.SaveChanges();

                var field1 = new Field { Name = "Field1", Label = mls1, Placeholder = mls2 };
                var field2 = new Field { Name = "Field2", Label = mls3, Placeholder = mls4 };

                ctx.Fields.AddRange(new[] { field1, field2 });
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var field = ctx.Fields
                   .Include(x => x.Label.Globalizations)
                   .ThenInclude(x => x.Language)
                   .Include(x => x.Placeholder.Globalizations)
                   .ThenInclude(x => x.Language)
                   .ToList();
            }
        }
    }
```

**Comment by htuomola** [comment]
Just to add, with the current bits you don't even need the second .ThenInclude there. At least I'm seeing a case in which calling Include-ThenInclude-Include causes a NullReferenceException.

**Comment by maumar** [comment]
fixed in a5299acd7735ec9ebc98f76e2c08817bea97266b

**Comment by nicbourgoin** [comment]
Can we reopen this? The repro works in beta6. However, if field1's Placeholder is set to null, an exception is thrown. This only happens when the first record has a null, putting field1's placeholder to mls2 and field2's placeholder to null will NOT cause an exception.

**Comment by maumar** [comment]
Fixed in 486e4e5d78d9c13d4d9a13cac77c70c9c72f286e

**Comment by Serjster** [comment]
This issue is still not fixed.

**Comment by smitpatel** [comment]
@Serjster - Is 'Issue.Customers` collection navigation?

**Comment by Serjster** [comment]
Oops, sorry converting from my domain specific classes... you're right, that is supposed to be `Customer` (updated above). Thanks for noticing it.

**Comment by maumar** [comment]
@Serjster could you provide a repro? Specifically code listing of all the entity classes and DbContext (especially contents of OnModelCreated method). Also, which version of EF are you using?

**Comment by Eilon** [comment]
@ajcvickers - should this bug be opened/closed/different milestone?
