### ISSUE TITLE
ArgumentNullException when querying with nullable byte, short, or enum parameters

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#2365]
See "Can_query_with_null_parameters_using_any_nullable_data_type" to reproduce.

Stack trace:

>
Test 'Microsoft.Data.Entity.SqlServer.FunctionalTests.BuiltInDataTypesSqlServerTest.Can_query_with_null_parameters_using_any_nullable_data_type' failed:
	System.ArgumentNullException : Value cannot be null.
Parameter name: value
	C:\aspnet\EntityFramework\src\Shared\Check.cs(24,0): at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
	Query\CommandParameter.cs(18,0): at Microsoft.Data.Entity.Relational.Query.CommandParameter..ctor(String name, Object value, RelationalTypeMapping typeMapping)
	Query\Sql\DefaultQuerySqlGenerator.cs(841,0): at Microsoft.Data.Entity.Relational.Query.Sql.DefaultQuerySqlGenerator.VisitParameter(ParameterExpression parameterExpression)
	at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
	at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
	Query\Sql\DefaultQuerySqlGenerator.cs(669,0): at Microsoft.Data.Entity.Relational.Query.Sql.DefaultQuerySqlGenerator.VisitBinary(BinaryExpression binaryExpression)
	at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
	at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
	Query\Sql\DefaultQuerySqlGenerator.cs(669,0): at Microsoft.Data.Entity.Relational.Query.Sql.DefaultQuerySqlGenerator.VisitBinary(BinaryExpression binaryExpression)
	at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
	at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
	Query\Sql\DefaultQuerySqlGenerator.cs(154,0): at Microsoft.Data.Entity.Relational.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
	Query\Expressions\SelectExpression.cs(595,0): at Microsoft.Data.Entity.Relational.Query.Expressions.SelectExpression.Accept(ExpressionVisitor visitor)
	at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
	Query\Sql\DefaultQuerySqlGenerator.cs(51,0): at Microsoft.Data.Entity.Relational.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IDictionary`2 parameterValues)
	Query\CommandBuilder.cs(56,0): at Microsoft.Data.Entity.Relational.Query.CommandBuilder.Build(IRelationalConnection connection, IDictionary`2 parameterValues)
	Query\QueryingEnumerable.cs(69,0): at Microsoft.Data.Entity.Relational.Query.QueryingEnumerable.Enumerator.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
	at lambda_method(Closure )
	Query\LinqOperatorProvider.cs(144,0): at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
	Query\CompiledQueryCache.cs(94,0): at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDataStore dataStore, QueryContext queryContext)
	Query\EntityQueryProvider.cs(71,0): at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
	at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
	BuiltInDataTypesSqlServerTest.cs(311,0): at Microsoft.Data.Entity.SqlServer.FunctionalTests.BuiltInDataTypesSqlServerTest.Can_query_with_null_parameters_using_any_nullable_data_type()

**Comment by maumar** [comment]
Fixed in ed3209e4f08a1201e4e3cfb810b9383eb2f5de59
