### ISSUE TITLE
Async and Left Join

### ISSUE THREAD

**Issue by prasannapattam** [aspnet/EntityFramework#2485]
I am getting the following error when using ToListAsync with Left Join
Message: "Index was outside the bounds of the array."
Stack Trace:    at Microsoft.Data.Entity.Relational.RelationalObjectArrayValueReader.ReadValue[T](Int32 index)
   at lambda_method(Closure , QuerySourceScope )
   at System.Linq.AsyncEnumerable.<>c__DisplayClassb3`2.<>c__DisplayClassb5.<>c__DisplayClassb7.<Select>b__b1(Boolean res)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Threading.Tasks.EntityFrameworkTaskExtensions.CultureAwaiter`1.GetResult()
   at Microsoft.Data.Entity.Query.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()

Here is my code
            var query1 = from vehicles in dbContext.Vehicles
                         join driver in dbContext.VehicleDrivers on vehicles.VehicleDriverId equals driver.VehicleDriverId into driverJoin
                         from vehicledriver in driverJoin.DefaultIfEmpty()
                         select new VehicleListModel
                        {
                            VehicleId = vehicles.VehicleId,
                            Driver = (vehicledriver == null ? null : vehicledriver.DriverName)
                         };

            var abc = await query1.ToListAsync();

**Comment by rowanmiller** [comment]
@prasannapattam what build of EF7 are you using?

**Comment by maumar** [comment]
related to #1232

**Comment by prasannapattam** [comment]
I am using EF 7.0.0-beta4.

The error message I am getting is different to that of #1232. But this be could be related.

**Comment by maumar** [comment]
This works in the current bits, we generate the following query:

```
SELECT [driver].[VehicleDriverId], [driver].[DriverName], [vehicles].[VehicleId]
FROM [Vehicle] AS [vehicles]
LEFT JOIN [VehicleDriver] AS [driver] ON [vehicles].[VehicleDriverId] = [driver].[VehicleDriverId]
ORDER BY [vehicles].[VehicleDriverId]
```

**Comment by prasannapattam** [comment]
This is working with beta 7. Thanks.
