### ISSUE TITLE
Blocked: SequenceValueGenerator may fail with LocalDb due to LocalDb concurrency issue with sequences

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#266]
Stack trace from CI failure:

```
The statement has been terminated.
   at System.Data.SqlClient.SqlCommand.<ExecuteDbDataReaderAsync>b__24(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Relational.Update.BatchExecutor.<ExecuteBatchAsync>d__1.MoveNext() in C:\BuildAgent\work\9114aaddeefdc8e8\src\Microsoft.Data.Entity.Relational\Update\BatchExecutor.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Relational.Update.BatchExecutor.<ExecuteAsync>d__1.MoveNext() in C:\BuildAgent\work\9114aaddeefdc8e8\src\Microsoft.Data.Entity.Relational\Update\BatchExecutor.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Data.Entity.Relational.RelationalDataStore.<SaveChangesAsync>d__1.MoveNext() in C:\BuildAgent\work\9114aaddeefdc8e8\src\Microsoft.Data.Entity.Relational\RelationalDataStore.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Data.Entity.ChangeTracking.StateManager.<SaveChangesAsync>d__1.MoveNext() in C:\BuildAgent\work\9114aaddeefdc8e8\src\Microsoft.Data.Entity\ChangeTracking\StateManager.cs:line 266
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Data.Entity.SqlServer.FunctionalTests.SequenceEndToEndTest.<AddEntitiesAsync>d__1.MoveNext() in C:\BuildAgent\work\9114aaddeefdc8e8\test\Microsoft.Data.Entity.SqlServer.FunctionalTests\SequenceEndToEndTest.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Data.Entity.SqlServer.FunctionalTests.SequenceEndToEndTest.<Can_use_sequence_end_to_end_from_multiple_contexts_concurrently_async>d__1.MoveNext() in C:\BuildAgent\work\9114aaddeefdc8e8\test\Microsoft.Data.Entity.SqlServer.FunctionalTests\SequenceEndToEndTest.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)```


<!---
@huboard:{"custom_state":"blocked"}
-->

**Comment by ajcvickers** [comment]
Internal bug on SQL Server indicates that this is now fixed and released in latest versions and service packs. Re-enabling test and closing out.
