### ISSUE TITLE
        public virtual SelectExpression PushDownSubquery() forgot predicate

### ISSUE THREAD

**Issue by Anderman** [aspnet/EntityFramework#2767]
see Join_customers_orders_with_subquery_predicate_with_take
That create this SQL statement
```
                @"SELECT [c].[ContactName], [t0].[OrderID]
FROM [Customers] AS [c]
INNER JOIN (
    SELECT TOP(5) [o2].*
    FROM [Orders] AS [o2]
    ORDER BY [o2].[OrderID]
) AS [t0] ON [c].[CustomerID] = [t0].[CustomerID]
WHERE [t0].[CustomerID] = 'ALFKI'"
```
Instead of 
```
                @"SELECT [c].[ContactName], [t0].[OrderID]
FROM [Customers] AS [c]
INNER JOIN (
    SELECT TOP(5) [o2].*
    FROM [Orders] AS [o2]
    WHERE [o2].[OrderID] > 0 //************where part was missing
    ORDER BY [o2].[OrderID]
) AS [t0] ON [c].[CustomerID] = [t0].[CustomerID]
WHERE [t0].[CustomerID] = 'ALFKI'"
```

**Comment by Anderman** [comment]
When runnig test, I get fails because the text that's generated contains \r\n and the expexted only \n.
I have replaced all Sql with Sql.Replace("\r",''") to pass all test but there must be a better way to do this.

Also I can't buld the last DEV version. Is there a way I can see the last succesfull build like the MVC project [history mvc](https://ci.appveyor.com/project/aspnetci/mvc/history)

**Comment by ErikEJ** [comment]
I can build the latest dev, what issues do you see?
The linefeed issue is due to your git configuration, change and get files again.

**Comment by Anderman** [comment]
@ErikEJ Thx. I had the line ending problem in the delivery zip file of the Beta 6 pacakge.

The error is 
![image](https://cloud.githubusercontent.com/assets/1858745/9032640/cf924d38-39c0-11e5-9687-3d3b4fc6c102.png)

```
Total build time elapsed: 00:00:03.4769526
Total projects built: 1
warn: Exit code -1 from cmd
verbose: Stack trace:
   at View2ecd540af9644e8da975776bf95845ef.Exec(String program, String commandline) in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 271
   at View2ecd540af9644e8da975776bf95845ef.DnuPack(String projectFile, String kpmPackOutputDir, String configuration) in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 645

   at View2ecd540af9644e8da975776bf95845ef.<>c__DisplayClass9f.<RenderViewLevel0>b__61(String projectFile) in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 7076
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at View2ecd540af9644e8da975776bf95845ef.<>c__DisplayClass9f.<RenderViewLevel0>b__5f() in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 7076
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View2ecd540af9644e8da975776bf95845ef.<RenderViewLevel0>b__47() in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 1830
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View2ecd540af9644e8da975776bf95845ef.<RenderViewLevel0>b__48() in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 1847
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.Builder.BuilderBase`1.StartingTarget(String name)
   at View2ecd540af9644e8da975776bf95845ef.<RenderViewLevel0>b__49() in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 1864
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at View2ecd540af9644e8da975776bf95845ef.<RenderViewLevel0>b__41() in c:\Users\Thom\AppData\Local\Temp\561d48d715ce42d3a845e5aff9d6578c-1.cs:line 1720
   at Sake.Engine.Builder.BuilderBase`1.CallTarget(String name)
   at Sake.Engine.SakeEngine.Execute(Options options)
   at Sake.Engine.SakeEngine.Execute(String[] args)
   at Sake.Program.Main(String[] args)
```


I think there are problems with nuget. Yesterday and today i got connection errors/ file not found

**Comment by Anderman** [comment]
I have clear the nuget cache and get these errors again

![image](https://cloud.githubusercontent.com/assets/1858745/9033115/e0658ebe-39c4-11e5-83dd-597d0187c5da.png)

**Comment by ErikEJ** [comment]
Did you run 

   build initialize

**Comment by Anderman** [comment]
Yep that works. 
How do I run all test. 

The error I got is in building 
`Building EntityFramework.Commands for DNX,Version=v4.5.1` and 
`Building EntityFramework.Commands for DNXCore,Version=v5.0` 

But 4.5 has no error
`Building EntityFramework.Commands for .NETFramework,Version=v4.5`

**Comment by ErikEJ** [comment]
I am not sure that EF.Commands build properly under those platforms - @lajones ?

**Comment by rowanmiller** [comment]
Merged
