### ISSUE TITLE
Collection.Remove(entity) throws NRE on Save

### ISSUE THREAD

**Issue by bcrosnier** [aspnet/EntityFramework#2890]
Considering the repro at https://github.com/bcrosnier/Ef7_RemoveBug

- Model & context: [src/Ef7Test/TestDbContext.cs](https://github.com/bcrosnier/Ef7_RemoveBug/blob/master/src/Ef7Test/TestDbContext.cs)
- Execution: [src/Ef7Test/Program.cs](https://github.com/bcrosnier/Ef7_RemoveBug/blob/master/src/Ef7Test/Program.cs)

Using ver 7.0.0-beta6 from NuGet, and DNX 1.0.0-beta6 ([project.json](https://github.com/bcrosnier/Ef7_RemoveBug/blob/master/src/Ef7Test/project.json))

I have a `Company` and `Contact`s inside this company, and am using inverse references on both sides.

Creating the entity cluster with one `Company` and many `Contact` inside it works; but removing one `Contact` and saving will however throw a `NullReferenceException`.

No exception is thrown when `Remove()` is not called on the parent entity's collection -- but the parent entity's collection is not updated, and the removed entity stays there.

Details and stack:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.Entity.Metadata.Internal.ClrPropertySetter`2.SetClrValue(Object instance, Object value)
   at Microsoft.Data.Entity.ChangeTracking.Internal.EntityEntryMetadataServices.WriteValue(Object entity, IPropertyBase propertyBase, Object value)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.WritePropertyValue(IPropertyBase propertyBase, Object value)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.set_Item(IPropertyBase property, Object value)
   at Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.SetNullForeignKey(InternalEntityEntry dependentEntry, IReadOnlyList`1 dependentProperties)
   at Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.ConditionallySetNullForeignKey(InternalEntityEntry dependentEntry, IReadOnlyList`1 dependentProperties, IReadOnlyList`1 principalValues)
   at Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChangedAction(InternalEntityEntry entry, INavigation navigation, IEnumerable`1 added, IEnumerable`1 removed)
   at Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.<>c__DisplayClass10_0.<NavigationCollectionChanged>b__0()
   at Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.PerformFixup(Action fixupAction)
   at Microsoft.Data.Entity.ChangeTracking.Internal.NavigationFixer.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.<>c__DisplayClass10_0.<NavigationCollectionChanged>b__0(INavigationListener l)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.Dispatch(Action`1 action)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntryNotifier.NavigationCollectionChanged(InternalEntityEntry entry, INavigation navigation, ISet`1 added, ISet`1 removed)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectNavigationChange(InternalEntityEntry entry, INavigation navigation, Sidecar snapshot)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectNavigationChanges(InternalEntityEntry entry, Sidecar snapshot)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectRelationshipChanges(InternalEntityEntry entry)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectChanges(InternalEntityEntry entry)
   at Microsoft.Data.Entity.ChangeTracking.Internal.ChangeDetector.DetectChanges(IStateManager stateManager)
   at Microsoft.Data.Entity.DbContext.TryDetectChanges(IStateManager stateManager)
   at Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.Data.Entity.DbContext.SaveChanges()
   at Ef7Test.Program.Main(String[] args) in D:\Dev\Personal\Ef7_RemoveBug\src\Ef7Test\Program.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args, FrameworkName targetFramework)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args, FrameworkName targetFramework)
```

Debugging details: here, `object instance` is the removed `Contact`; `object value` is `null`, and `_setter` is the `int` setter of `Contact.CompanyId`.

Might be related to #1111 and #1371, looking at the stack.
#1111 also shows the same symptoms.

Thanks!

**Comment by mikary** [comment]
I was able to reproduce this issue using EF beta6 and beta7. After updating to beta8, the exception is no longer thrown and the entity is properly removed from the collection.

While we don't have any tests that specifically remove the original user-provided instance from the collection, I was also able to reproduce in beta6 by querying and calling remove. This seems like a common enough scenario that it should have been picked up by existing tests unless the issue was particular the structure of the model.

Since this issue appears to be resolved, I have opened a general issue for `Remove` test coverage #3496 so we can keep an eye on this and triage it accordingly.
