### ISSUE TITLE
Object reference not set to an instance of an object - 

### ISSUE THREAD

**Issue by CodeStoneK** [aspnet/EntityFramework#3063]
I wrote a simple DbContext + Repository using **beta7** that works (just "read") with one model. The code works on one server but fails on a different one - they both have the table that I am working with.

**SERVER 1 (@@version)**
Microsoft SQL Server 2008 R2 (SP1) - 10.50.2500.0 (X64)   Jun 17 2011 00:54:03   Copyright (c) Microsoft Corporation  **Enterprise Edition** (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) (Hypervisor) 

**SERVER 2**
Microsoft SQL Server 2008 R2 (SP2) - 10.50.4000.0 (X64)   Jun 28 2012 08:36:30   Copyright (c) Microsoft Corporation  **Express Edition** (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 

The code works on SERVER 2 but fails on SERVER 1, with the following exception.  What am I missing? Please let me know if more details are needed.

```

using (var context = new AccountContext())
{
    var acct = context.Accounts.Where(a => a.sLogin == email);
    foreach (DomainObjects.Account a in acct) // exception occurs here
    {
        // ...
    }
}

Object reference not set to an instance of an object

   at lambda_method(Closure , ValueBuffer )
   at Microsoft.Data.Entity.Query.EntityLoadInfo.Materialize()
   at Microsoft.Data.Entity.Query.QueryBuffer.GetEntity(IEntityType entityType, EntityKey entityKey, EntityLoadInfo entityLoadInfo, Boolean queryStateManager)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.CreateEntity[TEntity](IQuerySource querySource, QueryContext queryContext, QueryResultScope parentQueryResultScope, ValueBuffer valueBuffer, Int32 valueBufferOffset, IEntityType entityType, Boolean queryStateManager, EntityKeyFactory entityKeyFactory, IReadOnlyList`1 keyProperties, Func`2 materializer)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at LZ.Account.Repository.Sql.AccountRepository.GetAccount(String email) in C:\TFS\TEAMS\Platform\Reference Architecture\LZ.Services\LZ.Account.Repository.Sql\AccountRepository.cs:line 35

```

**Comment by rowanmiller** [comment]
@CodeStoneK can you share a complete sample code listing we can use to reproduce this (model etc.).

**Comment by CodeStoneK** [comment]
@rowanmiller,

Here you go. Let me know if you need more details.

    // Entity

    public class EntityBase
    {
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime LastUpdatedDate { get; set; }
        public string LastUpdatedBy { get; set; }
    }

    public class Account : EntityBase
    {
        public Account() {   }

        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    }

    // context

    public class AccountContext : DbContext
    {
        public AccountContext() : base() { }
        public DbSet<Entities.Account> Accounts { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
                modelBuilder.Entity<Account>().ToTable("User", schemaName: "dbo");
                modelBuilder.Entity<Entities.Account>().Property(p => p.Id).HasColumnName("pkUserTable");
                base.OnModelCreating(modelBuilder);
        }
    }

**Comment by maumar** [comment]
I was unable to reproduce this in current bits - scenario works properly when using both flavors of SQL SERVER. If the problem still persists feel free to re-open the issue.

**Comment by JeffGillin** [comment]
This Materialize issue occurs when you have a data type mismatch between the database column and the entity property. I tend to get it when I have a nullable column with a null value, but the entity property type is a not nullable value type. Perhaps the error message could point the user in the right direction.
