### ISSUE TITLE
RevEng: Nvarchar foreign key to unique column causing InvalidOperationException

### ISSUE THREAD

**Issue by davezych** [aspnet/EntityFramework#3105]
I'm running EF 7 beta8-15676.

I have an existing database I'm trying to reverse engineer using the `scaffold` command:

    dnx ef dbcontext scaffold "{connectionstring}" EntityFramework.SqlServer

Within the database is a table that foreign keys to a unique column of another table (note: Not the PK). They are both `nvarchar(25)`. The simplified schema is:

    TableA (
        ID int not null PK,
        Serial nvarchar(25) not null (unique)
    )

    TableB (
        ID int not null PK,
        Serial nvarchar(25) not null (FK to TableA(Serial))
    )

When running `scaffold`, I receive the following error:

    System.InvalidOperationException: The types of the properties specified for the foreign key {'[dbo][TableB][Serial]'} on entity type '[dbo][TableB]' do not match the types of the properties in the principal key on entity type '[dbo][TableA]'.
       at Microsoft.Data.Entity.Metadata.Property.EnsureCompatible(IReadOnlyList`1 principalProperties, IReadOnlyList`1 dependentProperties, EntityType principalEntityType, EntityType dependentEntityType)
       at Microsoft.Data.Entity.Metadata.ForeignKey..ctor(IReadOnlyList`1 dependentProperties, Key principalKey, EntityType dependentEntityType, EntityType principalEntityType)
       at Microsoft.Data.Entity.Metadata.EntityType.AddForeignKey(IReadOnlyList`1 properties, Key principalKey, EntityType principalEntityType)
       at Microsoft.Data.Entity.Metadata.EntityType.GetOrAddForeignKey(IReadOnlyList`1 properties, Key principalKey, EntityType principalEntityType)
       at Microsoft.Data.Entity.SqlServer.Design.ReverseEngineering.SqlServerMetadataModelProvider.AddForeignKeysToModel(Model relationalModel, Dictionary`2 entityTypeToForeignKeyConstraintsMap)
       at Microsoft.Data.Entity.SqlServer.Design.ReverseEngineering.SqlServerMetadataModelProvider.AddKeysToModel(Model relationalModel)
       at Microsoft.Data.Entity.SqlServer.Design.ReverseEngineering.SqlServerMetadataModelProvider.ConstructRelationalModel(String connectionString)
       at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringMetadataModelProvider.GenerateMetadataModel(String connectionString)
       at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator.GetMetadataModel(IDatabaseMetadataModelProvider provider, ReverseEngineeringConfiguration configuration)
       at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator.<GenerateAsync>d__25.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Data.Entity.Commands.Program.<ReverseEngineerAsync>d__16.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Data.Entity.Commands.Program.<>c__DisplayClass9_4.<<Main>b__11>d.MoveNext()

**Comment by davezych** [comment]
I realized that EF6 doesn't support FK's to columns with unique constraints. My assumption here is that it won't be supported in EF7 either. Is that correct?

**Comment by ErikEJ** [comment]
@davezych  EF 6,1,3 reverse engineering should support it... I got a fix accepted for that

**Comment by lajones** [comment]
This should be fixed with commit 6d6d1d3. Closing, but please re-open if you see issues.
