### ISSUE TITLE
NuGet Commands: No stack trace is shown

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#3135]
No stacktrace is printed either. The message comes from PowerShell throwing `$null`. For some reason, it looks like an exception is being thrown without a message...

I hit this using the `EntityFramework.Sqlite` provider and not having sqlite3.dll available (i.e. via aspnet/Microsoft.Data.Sqlite#134)

**Comment by divega** [comment]
AggregateException?

**Comment by bricelam** [comment]
@divega That was my suspicion too.

**Comment by lajones** [comment]
Can I get more details? I'm not seeing it. If I do Scaffold-DbContext in the Package Manager Console without sqlite3 I get:

`Unable to load DLL 'sqlite3': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

If I do it on the command line. I get:

```
System.AggregateException: One or more errors occurred. ---> System.DllNotFoundException: Unable to load DLL 'sqlite3': The specifie
d module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(IntPtr filename, Sqlite3Handle& ppDb, Int32 flags, IntPtr vfs)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_open_v2(String filename, Sqlite3Handle& ppDb, Int32 flags, String vfs)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Entity.Sqlite.Design.ReverseEngineering.SqliteMetadataModelProvider.ConstructRelationalModel(String connectionS
tring) in C:\git\aspnet\EntityFramework\src\EntityFramework.Sqlite.Design\ReverseEngineering\SqliteMetadataModelProvider.cs:line 45
   at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.RelationalMetadataModelProvider.GenerateMetadataModel(String connec
tionString) in C:\git\aspnet\EntityFramework\src\EntityFramework.Relational.Design\ReverseEngineering\RelationalMetadataModelProvide
r.cs:line 57
   at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineeringConf
iguration configuration) in C:\git\aspnet\EntityFramework\src\EntityFramework.Relational.Design\ReverseEngineering\ReverseEngineerin
gGenerator.cs:line 89
   at Microsoft.Data.Entity.Relational.Design.ReverseEngineering.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringConfigu
ration configuration, CancellationToken cancellationToken) in C:\git\aspnet\EntityFramework\src\EntityFramework.Relational.Design\Re
verseEngineering\ReverseEngineeringGenerator.cs:line 58
   at Microsoft.Data.Entity.Design.DatabaseOperations.ReverseEngineerAsync(String provider, String connectionString, String outputDi
r, Boolean useFluentApiOnly, CancellationToken cancellationToken) in C:\git\aspnet\EntityFramework\src\EntityFramework.Commands\Desi
gn\DatabaseOperations.cs:line 74
   at Microsoft.Data.Entity.Commands.Program.<ReverseEngineerAsync>d__14.MoveNext() in C:\git\aspnet\EntityFramework\src\EntityFrame
work.Commands\Commands\Program.cs:line 375
```

**Comment by bricelam** [comment]
I'm not seeing it anymore. Must've been a bug in my code that got fixed before merging.

**Comment by bricelam** [comment]
Wait, I'm still not seeing a stacktrace...

**Comment by bricelam** [comment]
Ah, looks like my use of `Write-Output` is wrong.
