### ISSUE TITLE
Entity type cannot be tracked exception from derived AspNet.Idenity user class

### ISSUE THREAD

**Issue by leak** [aspnet/EntityFramework#3148]
The following exception only occurs when running a custom dnx command to seed the database on an application that has been published on a server without VS2015 being installed.

```
System.InvalidOperationException: The instance of entity type 'MyApp.Database.Entities.User' cannot be tracked because it has an invalid (e.g. null or CLR default) primary key. Either set the key explicitly or consider using an IValueGenerator to generate unique key values.
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.GetKeyValueChecked(IKey key, InternalEntityEntry entry)
   at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.Data.Entity.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges)
   at Microsoft.Data.Entity.DbContext.Attach[TEntity](TEntity entity)
   at Microsoft.AspNet.Identity.EntityFramework.UserStore`4.<UpdateAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.UserManager`1.<UpdateUserAsync>d__149.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNet.Identity.UserManager`1.<AddToRoleAsync>d__92.MoveNext()
```

The class in question is derived from `Microsoft.AspNet.Identity.EntityFramework.IdentityUser` the property in question is `public virtual TKey Id { get; set; }`

````
    public class User : IdentityUser<int>
    {
        private ICollection<Search> _searches;
        public virtual ICollection<Search> Searches => _searches ?? (_searches = new List<Search>());

        private ICollection<NotificationRule> _notificationRules;
        public virtual ICollection<NotificationRule> NotificationRules => _notificationRules ?? (_notificationRules = new List<NotificationRule>());
    }
````

The migration created this field properly as
````
            migrationBuilder.CreateTable(
                name: "AspNetUsers",
                columns: table => new
                {
                    Id = table.Column<int>(isNullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
````

Running the dnx command within the dev environment it seems to work after expicitly specifying `modelBuilder.Entity<User>().Key(y => y.Id);`. In the published application the issue persists. All packages are beta7.

**Comment by AndriySvyryd** [comment]
This might have been fixed in 8667adaecfe8d96cd8929cf83939cae6fd43f189

**Comment by rowanmiller** [comment]
@smitpatel can you just verify that this is fixed

**Comment by leak** [comment]
Just removed the workaround code and it appears to be working on rc1.
