### ISSUE TITLE
Query :: include doesn't work well with inheritance

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#3163]
Repro:

```
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using Microsoft.Data.Entity;

namespace Repro3163
{
    public class Customer
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public List<Order> Orders { get; set; }
    }

    public class VipCustomer : Customer
    {
    }

    public class Order
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string Name { get; set; }
    }

    public class MyContext : DbContext
    {
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(new SqlConnectionStringBuilder { DataSource = ".", InitialCatalog = "Repro3163", MultipleActiveResultSets = true, IntegratedSecurity = true }.ToString());
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Customer>().Collection(e => e.Orders).InverseReference().ForeignKey(e => e.CustomerId);
            modelBuilder.Entity<VipCustomer>().BaseType<Customer>();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var o11 = new Order { Name = "O11", };
                var o12 = new Order { Name = "O13" };
                var o21 = new Order { Name = "O21" };
                var o22 = new Order { Name = "O22", };
                var o23 = new Order { Name = "O23" };
                var o3 = new Order { Name = "O3" };

                var c1 = new Customer { Name = "C1", Orders = new List<Order> { o11, o12 } };
                var c2 = new Customer { Name = "C2", Orders = new List<Order> { o21, o22, o23 } };

                ctx.Customers.AddRange(c1, c2);
                ctx.Orders.AddRange(o11, o12, o21, o22, o23);
                ctx.SaveChanges();

                var c3 = new VipCustomer { Name = "VC3", Orders = new List<Order> { o3 }, };
                ctx.Customers.Add(c3);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                var query = ctx.Customers.OfType<VipCustomer>().Include(c => c.Orders);
                var result = query.ToList();

                Console.WriteLine(result);
            }
        }
    }
}

```

throws:

 The expression 'Convert([<generated>_1]).Orders' passed to the Include operator could not be bound.
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<IncludeNavigations>b__43_0(IncludeQueryAnnotation annotation) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 297
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 270
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in D:\k\EntityFramework\src\EntityFramework.Core\Query\EntityQueryModelVisitor.cs:line 153
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel) in D:\k\EntityFramework\src\EntityFramework.Core\Storage\Database.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_0`1.<CompileQuery>b__0() in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryCompiler.cs:line 132
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\k\EntityFramework\src\EntityFramework.Core\Query\Internal\CompiledQueryCache.cs:line 32
   at Microsoft.Data.Entity.Query.QueryCompiler.CompileQuery[TResult](Expression query) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryCompiler.cs:line 110
   at Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query) in D:\k\EntityFramework\src\EntityFramework.Core\Query\QueryCompiler.cs:line 67
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in D:\k\EntityFramework\src\EntityFramework.Core\Query\Internal\EntityQueryProvider.cs:line 37
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.IncludableQueryable`2.GetEnumerator() in D:\k\EntityFramework\src\EntityFramework.Core\Extensions\EntityFrameworkQueryableExtensions.cs:line 2235
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by maumar** [comment]
Fixed in 1a100f95c36697949c5d25791d9b132662b49243
