### ISSUE TITLE
Grouping with Joins using anonymous objects

### ISSUE THREAD

**Issue by gustyn** [aspnet/EntityFramework#3316]
I am using dnx Beta7 as well as "EntityFramework.SqlServer": "7.0.0-beta7",

Given the following query which is a query I have run in various forms or other in EF6 and earlier:
```c#
    var query = (from blog in Model.Blogs
        join comment in Model.Comments on blog.Id equals comment.BlogId into commentJoin
	from comentLeft in commentJoin.DefaultIfEmpty()
	group new {blog.Id, blog.Body, blog.Summary, blog.Synopsis, blog.Title} by new { blog.Id, 
       blog.Body, blog.Summary, blog.Synopsis, blog.Title}
					//into g
					//			   select new  
					//			   {
					//				   Id = g.Key.Id,
					//				   Summary = g.Key.Summary,
					//				   Synopsis = g.Key.Synopsis,
					//				   Title = g.Key.Title,
					//				   Body = g.Key.Body,
					//				   //Comments = g.Select(x => new { Author = 
                                        //                          x.Comment.AuthorId.ToString(), Text = x.Comment.Text })
					//			   }
					).FirstOrDefault(x=>x.Key.Id == id);
```

I keep getting the following exception:
```
Expression of type 'System.Func`3[Microsoft.Data.Entity.Query.QueryResultScope,System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope`1[Microsoft.Data.Entity.Storage.ValueBuffer]],Microsoft.Data.Entity.Query.QueryResultScope`1[System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Storage.ValueBuffer]]]' cannot be used for parameter of type 'System.Func`3[Microsoft.Data.Entity.Query.QueryResultScope,System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope`1[Structured.Models.Content.Comment]],Microsoft.Data.Entity.Query.QueryResultScope`1[System.Collections.Generic.IEnumerable`1[Structured.Models.Content.Comment]]]' of method 'System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope] _GroupJoin[Comment](System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope], System.Func`3[Microsoft.Data.Entity.Query.QueryResultScope,System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope`1[Structured.Models.Content.Comment]],Microsoft.Data.Entity.Query.QueryResultScope`1[System.Collections.Generic.IEnumerable`1[Structured.Models.Content.Comment]]])'

My stack trace is as follows:
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.QueryFlatteningExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean outerJoin)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.GroupJoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.RelationalDatabase.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDatabase database, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__7`1.<Execute>b__7_0(Expression q, IDatabase ds)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDatabase database, Boolean isAsync, Func`3 compiler)
   at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDatabase database, QueryContext queryContext)
   at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at Structured.Web.Angular.Blog.Blog.<Get>d__19.MoveNext() in C:\Projects\Git\VS 2015\Structured\src\Structured.Web\Angular\Blog\Blog.cs:line 101
```

**Comment by mkelley82** [comment]
I am using beta8.. and am also getting the same `1[System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Storage.ValueBuffer]]]' cannot be used for parameter of type 'System.Func`3

(as seen from code inspector)

Expression of type 'System.Func`3[Microsoft.Data.Entity.Query.QueryResultScope,System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope`1[Microsoft.Data.Entity.Storage.ValueBuffer]],Microsoft.Data.Entity.Query.QueryResultScope`1[System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Storage.ValueBuffer]]]' cannot be used for parameter of type 'System.Func`3[Microsoft.Data.Entity.Query.QueryResultScope,System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope`1[mpk.Models.DistrictDistributor]],Microsoft.Data.Entity.Query.QueryResultScope`1[System.Collections.Generic.IEnumerable`1[mpk.Models.DistrictDistributor]]]' of method 'System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope] _GroupJoin[DistrictDistributor](System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope], System.Func`3[Microsoft.Data.Entity.Query.QueryResultScope,System.Collections.Generic.IEnumerable`1[Microsoft.Data.Entity.Query.QueryResultScope`1[mpk.Models.DistrictDistributor]],Microsoft.Data.Entity.Query.QueryResultScope`1[System.Collections.Generic.IEnumerable`1[mpk.Models.DistrictDistributor]]])'

 with a somewhat similar query....

var districtsdetails = from districts in _ctx.District
                select new
                {
                    Id = districts.Id,
                    CountyFP = districts.County.FIPSCode,
                    DirectorName = districts.DirectorName,
                    Email = districts.Email,
                    EstStudentPop = districts.EstStudentPop,
                    Name = districts.Name,
                    Phone = districts.Phone,
                    Ranking = districts.Ranking,
                    RANumber = districts.RANumber,
                    SchoolCount = districts.SchoolCount,
                    Coop = districts.Coop.Name,
                    County = districts.County.Name,

                    Distributors = (from district in _ctx.District
                                   join districtdistributor in _ctx.DistrictDistributor on district.Id equals districtdistributor.DistrictId
                                   into group1
                                   from g1 in group1.DefaultIfEmpty()
                                   join distributor in _ctx.Distributor on g1.DistributorId equals distributor.Id
                                   into group2
                                   from g2 in group2.DefaultIfEmpty()
                                   where district.Id == districts.Id
                                   select new { g2.Id, g2.Name })
                };


Stack trace:
at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.QueryFlatteningExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean outerJoin)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.GroupJoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
   at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()

**Comment by mkelley82** [comment]
From what I can gather it has to do with using a range variable from the queries scope level 1 in scope level 3

**Comment by rowanmiller** [comment]
Slightly different exception message, but this still repros as of 7.0.0-rc2-16514

**Comment by AmineKhi** [comment]
same error here with 7.0.0-rc1-final.

**Comment by mikary** [comment]
Queries of this form no longer throw exceptions on current dev, opened related issue (#5171) for similar queries where DefaultIfEmpty is not used.
