### ISSUE TITLE
IndexOutOfRange thrown from In-Memory with polymorphic types

### ISSUE THREAD

**Issue by TomGillen** [aspnet/EntityFramework#3377]
I am running an in-memory database within a DNX project (beta7), with a DbSet of an abtract type with two concrete classes.

Attempts to query the set throws an IndexOutOfRangeException. In addition, inspecting the DbSet in the debugger will work *once*, and then fail all subsequent attempts to expand the collection. This is also true if there are multiple DbSets with polymorphic types; expanding any one in the debugger will work correctly once, but then fail subsequent attempts across all collections.

I have put together a project reproducing the error [here](https://github.com/TomGillen/EF-OutOfBoundsTest).

```c#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddEntityFramework()
            .AddInMemoryDatabase()
            .AddDbContext<DatabaseContext>(options => options.UseInMemoryDatabase());
    }

    public void Configure(IApplicationBuilder app, DatabaseContext db)
    {
        var count = db.A.Count(); // throws exception
    }
}

public class DatabaseContext : DbContext
{
    public DbSet<A> A { get; set; }
}

public abstract class A
{
    [Key]
    public int Key { get; set; }
}

public class B : A
{
    public int DataB { get; set; }
}

public class C : A
{
    public int DataC { get; set; }
}
```
The call to `db.A.Count()` throws:

```
System.IndexOutOfRangeException was unhandled by user code
  HResult=-2146233080
  Message=Index was outside the bounds of the array.
  Source=EntityFramework.InMemory
  StackTrace:
       at Microsoft.Data.Entity.InMemory.Query.MaterializerFactory.CreateMaterializer(IEntityType entityType)
       at Microsoft.Data.Entity.InMemory.Query.InMemoryQueryModelVisitor.InMemoryEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
       at Microsoft.Data.Entity.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
       at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
       at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CompileMainFromClauseExpression(MainFromClause mainFromClause, QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
       at Remotion.Linq.Clauses.MainFromClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
       at Microsoft.Data.Entity.InMemory.InMemoryDatabase.CompileQuery[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.Data.Entity.Query.CompiledQueryCache.CompileQuery(IDatabase database, MethodInfo compileMethodInfo, Type resultItemType, QueryModel queryModel)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.<>c__7`1.<Execute>b__7_0(Expression q, IDatabase ds)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.GetOrAdd(Expression query, QueryContext queryContext, IDatabase database, Boolean isAsync, Func`3 compiler)
       at Microsoft.Data.Entity.Query.CompiledQueryCache.Execute[TResult](Expression query, IDatabase database, QueryContext queryContext)
       at Microsoft.Data.Entity.Query.EntityQueryProvider.Execute[TResult](Expression expression)
       at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
       at EF.OutOfBoundsTest.Startup.Configure(IApplicationBuilder app, DatabaseContext db) in E:\Projects\EF.OutOfBoundsTest\src\EF.OutOfBoundsTest\Startup.cs:line 25
  InnerException: 
```

It happens regardless of whether there are entities in the tables or not, and happens both with table-per-hierarchy and table-per-type setups.

**Comment by rowanmiller** [comment]
Inheritance wasn't fully supported in Beta 7. In the most recent code base you need to call Entity<T> on each type on `OnModelCreating`. Still leaving open as we should verify we don't throw this exception in negative cases (this is negative because the only type in the hierarchy is abstract)

**Comment by TomGillen** [comment]
This still doesn't work in beta8, and calling Entity on each type does not help.

**Comment by natemcmaster** [comment]
@TomGillen thanks for the complete repro project. I could not reproduce the error using RC1. If you still encounter this error, please post the error and we can re-open the issue.
