### ISSUE TITLE
Problem with Select statement

### ISSUE THREAD

**Issue by csunali** [aspnet/EntityFramework#3408]
There seems to be an exception whenever there is a "Select" statement as `HasChildren = item.Children.Count > 0` and the Children are bound to the parent entity using a `long?` field:

```
An exception of type 'System.InvalidOperationException' occurred in mscorlib.dll but was not handled in user code

Additional information: The binary operator Equal is not defined for the types 'System.Nullable`1[System.Int64]' and 'System.Int64'.
```

The entities are as follows:

```
    public class ItemDto
    {
        public long Id { get; set; }
        public long? ParentId { get; set; }
        public string Name { get; set; }

        public bool HasChildren { get; set; }
    }

    public class Item
    {
        public long Id { get; set; }
        public long? ParentId { get; set; }
        public string Name { get; set; }

        public virtual ItemModel Parent { get; set; }
        public virtual ICollection<ItemModel> Children { get; } = new List<ItemModel>();
    }
```

And a simple code that breaks is:

```
            long? parentId = 5;
            IQueryable<Item> query = new ApplicationDbContext().Items.Where(i => i.ParentId == parentId);

            List<ItemDto> items = (from i in query
                                select new ItemDto
                                {
                                    Id = i.Id,
                                    ParentId = i.ParentId,
                                    Name = i.Name,
                                    HasChildren = i.Children.Count > 0
                                })
                                .ToList();
```

Please consider the fact that if I remove the `HasChildren = i.Children.Count > 0` line, everything works.

**Comment by csunali** [comment]
Sorry for not attaching, here is the full stack:

```
   at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
   at System.Linq.Expressions.Expression.Equal(Expression left, Expression right)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.CreateJoinsForNavigations(QuerySourceReferenceExpression outerQuerySourceReferenceExpression, IEnumerable`1 navigations)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.<>c__DisplayClass12_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindNavigationPathMemberExpression[TResult](MemberExpression memberExpression, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.FromClauseBase.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by Boglen** [comment]
Did you try remove
 = new List<ItemModel>();
and get
IQueryable<Item> query = new ApplicationDbContext().Items.Include(c => c.Children).Where(i => i.ParentId == parentId);

?

**Comment by csunali** [comment]
Yes, tried them now and none of your suggestions helped. Still getting the same exception thrown.

**Comment by Boglen** [comment]
HasChildren = ( i.Children.Count ?? default(long)) > 0 
Or
HasChildren = i.Children.Count.GetValueOrDefault() > 0

I'm on mobile and can't test

**Comment by maumar** [comment]
looks like we are missing a convert to compensate for nullability difference between PK and FK. I'm currently working on an issue around this area (nav prop rewrite) and have fixed one instance when this was happening already, so this might get fixed along with issue 3103

**Comment by csunali** [comment]
Thank you!

**Comment by maumar** [comment]
Nullability issue fixed in 41ad57ad2f3755c5e35b51d939fab52b489ce738

**Comment by csunali** [comment]
I will test that ASAP but that might take a few days. Currently busy with migrating the things to RC 1 packages :)

**Comment by maumar** [comment]
Note that the scenario is still broken due to https://github.com/aspnet/EntityFramework/issues/3538

**Comment by csunali** [comment]
Thank you for the last detail and your overall feedback.
