### ISSUE TITLE
Problem with Union Operator

### ISSUE THREAD

**Issue by dwatty** [aspnet/EntityFramework#3459]
I'm using SQLite as my underlying data store and the app in question is a .NET 4.5.1 console application.  I believe these are the pertinent packages I'm using revolving this issue (if I missed one let me know):

- System.Data.SQLite.Core 
- System.Data.SQLite.Linq 1.0.98.1
- EntityFramework.Commands 7.0.0-beta8
- EntityFramework.SQLite 7.0.0-beta8

So, I have two lists of objects that I'm using a Union operator on a couple of lists like so:

```
var orders = _dbContext.Orders.Where(x => some filters);
var futureOrders = _dbContext.Orders.Where(x => some filter);

foreach (var order in orders.Union(futureOrders))
{
      result.Add(JsonConvert.DeserializeObject<Order>(order.Content));
}
```

This query worked fine using EF6 with a LocalDb data store.  But now on EF7 and SQLite, when the code gets to the foreach loop, it throws an exception with a message of Message = ***Remotion.Linq.Clauses.ResultOperators.UnionResultOperator***.  The source is listed as EntityFramework.Core and it produces the stack trace as follows:

```
   at Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
   at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Data.Entity.Query.QueryCompiler.<>c__DisplayClass16_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at Project.Repositories.OrderRepository.GetOrdersForProduction() in C:\{Path_To_Project\Repositories\OrderRepository.cs:line 100
```

I'm at a bit of loss as to where to begin.  Is this an EF7 issue?  A SQLite issue?  Any help would be greatly appreciated.

**Comment by mikary** [comment]
Attempted to reproduce this issue with current dev and no exception was thrown. This issue was likely resolved by unrelated changes and fixes between beta8 and now.

Reproduction used:
```cs
    class Program
    {
        static void Main(string[] args)
        {
            var now = DateTime.Now;

            using (var context = new UnionProblemContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var past = now - TimeSpan.FromDays(10);
                var future = now + TimeSpan.FromDays(10);

                context.Add(new Order { OrderDateTime = past });
                context.Add(new Order { OrderDateTime = future });
                context.SaveChanges();
            }


            using (var context = new UnionProblemContext())
            {
                var orders = context.Orders.Where(o => o.OrderDateTime < now);
                var futureOrders = context.Orders.Where(o => o.OrderDateTime > now);

                var result = new List<Order>();

                foreach (var order in orders.Union(futureOrders))
                {
                    result.Add(order);
                }
            }
        }
    }

    public class Order
    {
        public int OrderId { get; set; }
        public DateTime OrderDateTime { get; set; }
    }

    public class UnionProblemContext : DbContext
    {
        public DbSet<Order> Orders { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=unionProblem.db");
        }
    }
```

**Comment by smitpatel** [comment]
Set operations were implemented in RC2. Tracking issue #3638

**Comment by mikary** [comment]
Note: this specific scenario should be covered for regressions by an existing query test - `QueryTestBase.Union_simple`
