### ISSUE TITLE
Group By Null Reference Exception

### ISSUE THREAD

**Issue by brent-russell** [aspnet/EntityFramework#3595]
Beta8

The following query throws a null ref exception caused by the group by expression. Without the group by expression, the query runs fine. It doesn't matter what's in the select portion.

```C#
var q0 = from instance in this.DbContext.ExamInstances
		 join question in this.DbContext.ExamInstanceQuestions
			on instance.Id equals question.ExamInstanceId
		 where instance.Id == 3
		 group question by question.QuestionId into gQuestions
		 select new
		 {
			 Key = gQuestions.Key,
			 MaxDate = gQuestions.Max(q => q.UtcDateUpdated)
		 };
```

```
Result StackTrace:	
at Microsoft.Data.Entity.Query.QueryResultScope._GetResult[TResult](IQuerySource querySource)
   at lambda_method(Closure , QueryResultScope )
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__1`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Data.Entity.Query.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

Result Message:	Object reference not set to an instance of an object.
```

There's nothing really special about the model here. I'm running it against the SqlServer in-memory DB with a test data set in the thousands.

**Comment by rowanmiller** [comment]
@brent-russell any chance you can share your model so that we can run your query to reproduce the issue

**Comment by brent-russell** [comment]
@rowanmiller @maumar Here's a repo with sample code that exhibits the issue (xunit tests)
https://github.com/brent-russell/ef7-beta8-groupby-test

**Comment by rowanmiller** [comment]
Perfect, thanks!

**Comment by mikary** [comment]
Confirmed that this exception was being thrown in Beta8 using the InMemoryProvider. Ran the same repro against current dev and the exception was not thrown. Appears to have been resolved by fixes for other related issues.

**Comment by larkydoo** [comment]
I'm having the same issues. @brent-russell : how did you get around it? The one thing I did that worked was to use ToListAsync() rather than FirstOrDefaultAsync, but this isn't really a desirable solution. 

Original Query (throws undesired NullReferenceException):
```
            var feature = await _tenantContext.Permission.Where(e => e.Feature == request.FeatureName).OrderBy(o => o.Action).GroupBy(g => g.Feature).FirstOrDefaultAsync(cancellationToken);

            if (feature == null)
            {
                throw new NotFoundException(nameof(Domain.Entities.TenantDB.Permission));
            }
```
New Query (throws desired NotFoundException):
```
            var featureList = await _tenantContext.Permission.Where(e => e.Feature == request.FeatureName).OrderBy(o => o.Action).GroupBy(g => g.Feature).ToListAsync(cancellationToken);

            if (featureList.Count == 0)
            {
                throw new NotFoundException(nameof(Domain.Entities.TenantDB.Permission));
            }
            var feature = featureList[0];
```
