### ISSUE TITLE
PropertyMappingValidationConvention throws incorrectly with non-public properties

### ISSUE THREAD

**Issue by HenryGarle** [aspnet/EntityFramework#3679]
After updating to the latest RC1 I am having an odd issue with adding migrations. Most of my projects work correctly but my largest project is spitting out a rather unhelpful message upon trying to add a migration from scratch.

```
>dnx ef migration add Initial

System.ArgumentNullException: Value cannot be null.
Parameter name: propertyInfo
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationalPropertyMappingValidationConvention.FindCandidateNavigationPropertyType(PropertyInfo propertyInfo)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Validate()
   at Microsoft.Data.Entity.ModelBuilder.Validate()
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.<>c__DisplayClass7_0.<ConfigureContextServices>b__8(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass6_0.<AddMigration>b__0()
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
Value cannot be null.
Parameter name: propertyInfo
```

I assume it is caused by something specific in the model but its rather large and tracking it down has proved to be almost impossible. I'll continue to dig in but if anyone has any light to shed on what might be causing it that would be great.

**Comment by smitpatel** [comment]
@HenryGarle - Hey, thanks for reporting bug. In `PropertyMappingValidationConvention`, we use `GetRuntimeProperties()` to find all clr properties and for verify properties which are not added to the model, `GetRuntimeProperty(propertyName)` is used. Ideally they should be able to find out the property but it looks like there is slight behavior difference between those. (more info: http://stackoverflow.com/questions/14003872/reflection-inconsistent-framework-behavior-with-getruntimeproperty-methods)

For work-around,
In your model, in some entity type, you have a non-public property which is not added as property/navigation in the model. Unless the return type of such property is some entity type which is ignored in the model, there will be exception thrown that property/navigation is not added in the model. If it is navigation and target entity type is ignored in the model, you can try removing that property if it is not being used.

I will be sending out PR for the fix shortly.

**Comment by HenryGarle** [comment]
Thank you very much for your reply, its been a real head scratcher! That does sound completely possible and I will dig into my model tomorrow to see if I can find the culprit. I apologize for the lack of detail on the issue as it is a rather large model now so tracking it down was proving difficult. Thank you very much for the speedy response and incoming fix.

**Comment by HenryGarle** [comment]
I finally found the culprit but a little confused as to why suddenly it became a problem. I have been using long hand for navigation properties since I started using the very first alpha versions but now this syntax was causing the issue:

        private List<ServiceVariable> _variables { get; set; }
        public virtual List<ServiceVariable> Variables
        {
            get
            {
                return _variables ?? (_variables = new List<ServiceVariable>());
            }
            set
            {
                _variables = value;
            }
        }

It makes sense given the explanation you gave and replacing it with the short hand { get; set; } = new List<type>(); solved the issue. Only adding this in case there are implications with EF taking a look at those properties although I assume from looking it would end up ignoring those anyway (if there was no exception being thrown).

**Comment by smitpatel** [comment]
@HenryGarle - Thanks for adding information.
It is not uncommon to have a private field and a public property exposing it. At present EF will try to include both of them in the model and throw exception if not added/ignored. Since both the field and property represent essentially one navigation, it is bit weird for user to ignore the field or use auto-property always. @rowanmiller , @divega - thoughts?

**Comment by divega** [comment]
@smitpatel I can't remember if we closed on what we want to do with fields and properties? Let's discuss it tomorrow if we haven't. We should be able to come up with something, probably use the same rules we use elsewhere to pair properties and their fields so that we don't detect the same thing twice. 

cc @ajcvickers.

**Comment by ajcvickers** [comment]
@divega @smitpatel Agreed we can talk about this, but note that in the code above there is a pubilc property and a private _property_, not a private _field_. I believe if it was a private field we wouldn't have this problem because we don't currently attempt to map fields. I think having public and a private property representing the same thing is not that common, and it's probably okay to explicitly exclude the private property from the model for this scenario.

**Comment by smitpatel** [comment]
@ajcvickers - Agreed. I just now realized while looking at some other code that it was private property and not field.
>  I think having public and a private property representing the same thing is not that common, and it's probably okay to explicitly exclude the private property from the model for this scenario.

Seems fine to me.

**Comment by divega** [comment]
Ah, I also missed that it was a property. :+1:

**Comment by JanLenoch** [comment]
Hello, I'm observing the same behavior upon adding my migration, even with v7.0.0-rc1. And I don't have any explicit backing fields defined in my properties.

I have just three DbSets in my context and the most complex one looks like that:

`
public class InnerCollection : IInnerCollection
{
    public int Order { get; set; }
    public int NoOfItems { get; set; }
    public ILiteralCollection Parent { get; set; }
 
    ICollection<IDocumentPart> ILiteralCollection.Parts
    {
        get { return Parts; }
        set { Parts = (List<IDocumentPart>)value; }
    }

    public List<IDocumentPart> Parts { get; set; }
}
`

I can share the complete inheritance/association scheme with you if you wish.

The stack trace is as follows:

`
System.ArgumentNullException: Value cannot be null.
Parameter name: propertyInfo
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.RelationalPropertyMappingValidationConvention.FindCandidateNavigationPropertyType(PropertyInfo propertyInfo)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Validate()
   at Microsoft.Data.Entity.ModelBuilder.Validate()
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.Internal.DesignTimeServicesBuilder.<>c__DisplayClass7_0.<ConfigureContextServices>b__8(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.Data.Entity.Design.OperationExecutor.<AddMigrationImpl>d__7.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.Execute(Action action)
`

Would you give me some hints of what I might be doing wrong? Isn't there a problem in defining the container as `public List<IDocumentPart> Parts { get; set; }` (with interface declaration instead of specific type declaration)? Or is it a defect in EF?

Thanks

**Comment by rowanmiller** [comment]
@JanLenoch 

>  Isn't there a problem in defining the container as  public List<IDocumentPart> Parts { get; set; }  (with interface declaration instead of specific type declaration)?

This won't work, unless you do some extra configuration to tell EF what types to use. That said, you shouldn't get the very unhelpful error you are seeing :smile:. Can you open a new issue and share a complete code sample we can run to reproduce the issue.
