### ISSUE TITLE
sqlserver query returns different results on coreclr/linux

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#3772]
Using System.Data.SqlClient coreclr-linux.
```
Microsoft.Data.Entity.SqlServer.FunctionalTests.QuerySqlServerTest.Where_string_to_lower
 Assert.Equal() Failure
      Expected: 0
      Actual:   1
      Stack Trace:
           at Microsoft.Data.Entity.Tests.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Boolean assertOrder, Action`2 asserter)
           at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.AssertQuery[TItem](Func`2 efQuery, Func`2 l2oQuery, Boolean assertOrder, Int32 entryCount, Action`2 asserter)
           at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.AssertQuery[TItem](Func`2 query, Boolean assertOrder, Int32 entryCount, Action`2 asserter)
           at Microsoft.Data.Entity.FunctionalTests.QueryTestBase`1.Where_string_to_lower()
           at Microsoft.Data.Entity.SqlServer.FunctionalTests.QuerySqlServerTest.Where_string_to_lower()

Microsoft.Data.Entity.SqlServer.FunctionalTests.QuerySqlServerTest.SelectMany_mixed
      Assert.Equal() Failure
      Expected: 3873
      Actual:   3818
      Stack Trace:
           at Microsoft.Data.Entity.SqlServer.FunctionalTests.QuerySqlServerTest.SelectMany_mixed()
```

**Comment by rowanmiller** [comment]
Possibly case sensitivity

**Comment by natemcmaster** [comment]
`Where_string_to_lower` does not reproduce on System.Data.SqlClient 4.0.0-rc2-23513.
The error in SelectMany_mixed is that we assert the length of the raw sql, which includes the connection string.

**Comment by natemcmaster** [comment]
Correction. The difference in length is due to `"\r\n".Length == 2` and `"\n".Length = 1`. The string we expect has 55 new line characters.

**Comment by natemcmaster** [comment]
Fixed in https://github.com/aspnet/EntityFramework/commit/ea2d6b45e956074232045f20819b9b63bd23dd75
