### ISSUE TITLE
Tests using scratch localdb are flaky

### ISSUE THREAD

**Issue by AndriySvyryd** [aspnet/EntityFramework#3902]
```
System.Data.SqlClient.SqlException : Unable to open the physical file "C:\Users\asplab\Microsoft.Data.SqlServer.Scratch_15.mdf". Operating system error 2: "2(The system cannot find the file specified.)".
Unable to open the physical file "C:\Users\asplab\Microsoft.Data.SqlServer.Scratch_15.mdf". Operating system error 2: "2(The system cannot find the file specified.)".
Could not restart database "Microsoft.Data.SqlServer.Scratch_15". Reverting to the previous status.
ALTER DATABASE statement failed.
File activation failure. The physical file name "C:\Users\asplab\Microsoft.Data.SqlServer.Scratch_15_log.ldf" may be incorrect.
File activation failure. The physical file name "C:\Users\asplab\Microsoft.Data.SqlServer.Scratch_15_log.ldf" may be incorrect.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerTestStore.DeleteDatabase(String name) in C:\BuildAgent\work\212a0415691ecf7e\test\EntityFramework.MicrosoftSqlServer.FunctionalTests\Utilities\SqlServerTestStore.cs:line 392
   at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerTestStore.CreateTransient(Boolean createDatabase) in C:\BuildAgent\work\212a0415691ecf7e\test\EntityFramework.MicrosoftSqlServer.FunctionalTests\Utilities\SqlServerTestStore.cs:line 302
   at Microsoft.Data.Entity.SqlServer.FunctionalTests.SqlServerTestStore.CreateScratch(Boolean createDatabase) in C:\BuildAgent\work\212a0415691ecf7e\test\EntityFramework.MicrosoftSqlServer.FunctionalTests\Utilities\SqlServerTestStore.cs:line 36
   at Microsoft.Data.Entity.SqlServer.FunctionalTests.QueryBugsTest.Query_when_null_key_in_database_should_throw() in C:\BuildAgent\work\212a0415691ecf7e\test\EntityFramework.MicrosoftSqlServer.FunctionalTests\QueryBugsTest.cs:line 28
```

**Comment by bricelam** [comment]
A while ago, I noticed some code in the test fixture that deletes the files even if the database couldn't be dropped. You'd get this error if that code path was hit. I have no idea what would cause the database not to drop...

**Comment by rowanmiller** [comment]
We think we are good now, will reopen if needed
