### ISSUE TITLE
Changing MigrationsHistoryTableSchema generates error in migration generation

### ISSUE THREAD

**Issue by timotyweis** [aspnet/EntityFramework#3963]
Using this extension method to set the migration table name and schema on the current `SqlServerOptionsExtension` allows to override the migration table name and schema:

``` c#
public static DbContextOptionsBuilder UseMigrationHistoryTable(this DbContextOptionsBuilder optionsBuilder, string migrationsHistoryTableName, string migrationsHistoryTableSchema = null)
{
	if (string.IsNullOrWhiteSpace(migrationsHistoryTableName))
	{
		return optionsBuilder;
	}

	var orCreateExtension = GetOrCreateExtension(optionsBuilder);
	orCreateExtension.MigrationsHistoryTableName = migrationsHistoryTableName;

	if (!string.IsNullOrWhiteSpace(migrationsHistoryTableSchema))
	{
		orCreateExtension.MigrationsHistoryTableSchema = migrationsHistoryTableSchema;
	}

	((IDbContextOptionsBuilderInfrastructure)optionsBuilder).AddOrUpdateExtension(orCreateExtension);

	return optionsBuilder;
}

private static SqlServerOptionsExtension GetOrCreateExtension(DbContextOptionsBuilder optionsBuilder)
{
	var extension = optionsBuilder.Options.FindExtension<SqlServerOptionsExtension>();
	return extension == null ? new SqlServerOptionsExtension() : new SqlServerOptionsExtension(extension);
}
```

If only the table name is provided the migrations can be executed correctly and the migration table name gets effectively changed. However, when also the schema is provided the following exception is thrown:
```
GetCreateScript only handles operations in a single batch. For more advanced scenarios, override HistoryRepository.GetCreateScript in your provider.

   at Microsoft.Data.Entity.Migrations.HistoryRepository.GetCreateScript()
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
```

**Comment by bricelam** [comment]
Oh interesting. This is because we ensure the schema exists before creating the table...
```SQL
IF SCHEMA_ID(N'schema1') IS NULL EXEC(N'CREATE SCHEMA [schema1]');
```
This was regressed by #2739.

**Comment by bricelam** [comment]
This simplest fix would be for us to ignore `EnsureSchema` operations, but this means you'd have to create the schema before migrating.
