### ISSUE TITLE
Left Outer Join doesn't work with EF7

### ISSUE THREAD

**Issue by pierregaboriaud** [aspnet/EntityFramework#3982]
Please look at my post on stackoverflow: http://stackoverflow.com/questions/34095062/left-outer-join-with-entity-framework-7-vnext-rc1

**Comment by rowanmiller** [comment]
Copying details from StackOverflow

I'm trying to perform a left outer join request with EF7 (7.0.0-rc1-final), vNext RC1 (rc1-final) and SQL Server 2014


Database :

Pet: Id, Name

User: Id, Name, #PetId

This one works:
```
var queryWorks = from u in _context.Users
                 join p in _context.Pets on u.PetId equals p.Id into pp
                 from p in pp.DefaultIfEmpty()
                 select new {
                     UserName = u.Name,
                     Pet = p
                 };
```

but this one doesn't work (Message = "Sequence contains no elements"):

```
var queryFails = from u in _context.Users
                 join p in _context.Pets on u.PetId equals p.Id into pp
                 from p in pp.DefaultIfEmpty()
                 select new {
                     UserName = u.Name,
                     PetName = (p == null ? "NULL" : p.Name)
                 };
```

SQL Server Profile 2014 shows me that the second request is not sent to the SQL Server. Why ?

Thanks :)

**Comment by rowanmiller** [comment]
@pierregaboriaud can you provide the stack trace from the exception

**Comment by pierregaboriaud** [comment]
System.InvalidOperationException
Additional information: Sequence contains no elements

Stack trace : 
<pre>
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberOrMethod[TResult](Func`4 memberBinder, IQuerySource querySource, IProperty property, Boolean bindSubQueries)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.<>c__DisplayClass77_0`1.<BindMemberExpression>b__0(IProperty property, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass79_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`4 memberBinder, Boolean bindSubQueries)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, Func`4 memberBinder, Boolean bindSubQueries)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.<>n__0(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.<>c__DisplayClass61_0.<VisitJoinClause>b__0()
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean outerJoin)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.JoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at XXXAPI.Controllers.XXXController.GetAllXXX() in D:\XXXX.cs:line 81
</pre>

**Comment by pierregaboriaud** [comment]
This exception fired when I call queryFails.ToList();

The request itself doesn't throw any exception.

**Comment by prasannapattam** [comment]
I have the same issue. My code used to work in the previous beta 8. With RC1 it is not working.

Is there a hotfix or daily build I can use immediately.

**Comment by prasannapattam** [comment]
Linq Query:

```c#
var query1 = from vehicles in dbContext.Vehicles
                join driver in dbContext.VehicleDrivers on vehicles.VehicleDriverId equals driver.VehicleDriverId into driverJoin
                from vehicledriver in driverJoin.DefaultIfEmpty()
                select new VehicleListModel
                {
                    VehicleId = vehicles.VehicleId,
                    Driver = vehicledriver.DriverName
                };
var data = await query1.ToListAsync();
```
Error Message:
 "Sequence contains no elements"

Stack Trace:
```
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberOrMethod[TResult](Func`4 memberBinder, IQuerySource querySource, IProperty property, Boolean bindSubQueries)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.<>c__DisplayClass77_0`1.<BindMemberExpression>b__0(IProperty property, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass79_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`4 memberBinder, Boolean bindSubQueries)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, Func`4 memberBinder, Boolean bindSubQueries)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileAsyncQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate,TResult](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, Func`2 resultSelector, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.Aggregate[TSource,TAccumulate](IAsyncEnumerable`1 source, TAccumulate seed, Func`3 accumulator, CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.ToList[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at eMine.Lib.Repositories.Fleet.VehicleRepository.<VehicleListGet>d__42.MoveNext() in D:\Prasanna\Mind\Repos\MegaMine\MegaMine\src\eMine\Lib\Repositories\Fleet\VehicleRepository.cs:line 742
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at eMine.Lib.Domain.FleetDomain.<VehicleList>d__3.MoveNext() in D:\Prasanna\Mind\Repos\MegaMine\MegaMine\src\eMine\Lib\Domain\FleetDomain.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at eMine.Lib.Shared.AjaxHelper.<GetAsync>d__3`1.MoveNext() in D:\Prasanna\Mind\Repos\MegaMine\MegaMine\src\eMine\Lib\Shared\AjaxHelper.cs:line 62
```

**Comment by maumar** [comment]
This has been fixed in a47422fdc05dfb703378214e2a466f0225946f29

**Comment by tarikburakozonder** [comment]
Yuo havent fix it. Same problem continue. from device in _deviceRepository.Table
                         join vehicle in _vehicleRepository.Table
                         on device.Id equals vehicle.DeviceId into tmpVehicle
                         from vehicle in tmpVehicle.DefaultIfEmpty()
                         join locationProject in _locationProjectRepository.Table
                         on vehicle.LocationId equals locationProject.LocationId into tmplocationProject
                         from locationProject in tmplocationProject.DefaultIfEmpty()
                         orderby device.CreateDate descending
                         select new GetDeviceGridDataResponse.GridData
                         {
                             Id = device.Id,
                             Name = device.Name,
                             Code = device.Code,
                             IMEI = device.IMEI,
                             PlateNo = locationProject.CreatorAppVersion,
                             Location = device.Name,
                             Project = device.Name,
                             IsActive = device.IsActive
                         });


locationProject.CreatorAppVersion object reference not set error.

**Comment by smitpatel** [comment]
@tarikburakozonder - You are using `DefaultIfEmpty()` without args, which would return null if there is no matching elements, you need to do null check before calling `locationProject.CreatorAppVersion`.

**Comment by tarikburakozonder** [comment]
Hi , thanks for your response,
The thing is that, we were using the same statement on the earlier version of EF and there wasn't any problem at all. Therefore, I am trying to implement the same query, I don't understand the problem.

**Comment by smitpatel** [comment]
Hitting a null at that point is pretty much data dependent, So same query would work fine if there are no unmatched rows but would throw error otherwise. Are you sure that data has not changed from the time when query was running correctly?

**Comment by tarikburakozonder** [comment]
Let me put it this way, I am pretty sure the working style of left join on EF6 because of my old framework that is completely based on this kind of left join queries. Now, I am trying to fetch data from the same DB with the same LINQ Query it works fine on EF6. But it doesn't work on EF7. Is there any difference that I should know between dotnet core vs dotnet 4.6 about working styles of queries?

**Comment by maumar** [comment]
@tarikburakozonder EF Core (i.e. EF7) has been built completely from scratch and still can't translate many queries (especially around optional navigations/LOJs) that EF6 can. What you are probably experiencing is one of those cases.  Best thing would be to file a new issue with your query as well as code listing for all the entities and contents of OnModelCreating method on your DbContext and we will look into it. 

If your project heavily depends on queries like that, switching to EF Core might not be the best option at this moment.
