### ISSUE TITLE
Migrations: AddColumn, AddForeignKey, etc. use new table name before it's renamed

### ISSUE THREAD

**Issue by JaimeStill** [aspnet/EntityFramework#3990]
```C#
protected override void OnModelCreating(ModelBuilder builder)
{
    base.OnModelCreating(builder);
    // Customize the ASP.NET Identity model and override the defaults if needed.
    // For example, you can rename the ASP.NET Identity table names and more.
    // Add your customizations after calling base.OnModelCreating(builder);

   builder.Entity<ApplicationUser>()
        .Ignore(x => x.AccessFailedCount)
        .Ignore(x => x.EmailConfirmed)
        .Ignore(x => x.LockoutEnabled)
        .Ignore(x => x.LockoutEnd)
        .Ignore(x => x.PasswordHash)
        .Ignore(x => x.PhoneNumberConfirmed)
        .Ignore(x => x.TwoFactorEnabled)
        .ToTable("UserProfile");
}
```
When updating the database after generating the migration, the following exception is thrown:
```
Applying migration '00000000000000_CreateIdentitySchema'.
Applying migration '20151206142754_ModelBuilderConfigs'.
System.Data.SqlClient.SqlException (0x80131904): Cannot find the object "UserProfile" because it does not exist or you do not have permissions.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.<>c.<ExecuteNonQuery>b__13_0(DbCommand cmd, IRelationalConnection con)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, Boolean manageConnection)
   at Microsoft.Data.Entity.Storage.RelationalCommandExtensions.ExecuteNonQuery(IEnumerable`1 commands, IRelationalConnection connection)
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Execute(IEnumerable`1 relationalCommands)
   at Microsoft.Data.Entity.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.Data.Entity.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.Data.Entity.Commands.Program.Executor.Execute(Action action)
ClientConnectionId:f74269cd-30ab-46fb-9748-77e75753e9a9
Error Number:4902,State:1,Class:16
Cannot find the object "UserProfile" because it does not exist or you do not have permissions.
```
Migration file generated for reference:
```C#
protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.DropForeignKey(name: "FK_IdentityRoleClaim<string>_IdentityRole_RoleId", 
        table: "AspNetRoleClaims");
    migrationBuilder.DropForeignKey(name: "FK_IdentityUserClaim<string>_ApplicationUser_UserId", 
        table: "AspNetUserClaims");
    migrationBuilder.DropForeignKey(name: "FK_IdentityUserLogin<string>_ApplicationUser_UserId", 
        table: "AspNetUserLogins");
    migrationBuilder.DropForeignKey(name: "FK_IdentityUserRole<string>_IdentityRole_RoleId", 
        table: "AspNetUserRoles");
    migrationBuilder.DropForeignKey(name: "FK_IdentityUserRole<string>_ApplicationUser_UserId", 
        table: "AspNetUserRoles");
    migrationBuilder.DropColumn(name: "AccessFailedCount", table: "AspNetUsers");
    migrationBuilder.DropColumn(name: "EmailConfirmed", table: "AspNetUsers");
    migrationBuilder.DropColumn(name: "LockoutEnabled", table: "AspNetUsers");
    migrationBuilder.DropColumn(name: "LockoutEnd", table: "AspNetUsers");
    migrationBuilder.DropColumn(name: "PasswordHash", table: "AspNetUsers");
    migrationBuilder.DropColumn(name: "PhoneNumberConfirmed", table: "AspNetUsers");
    migrationBuilder.DropColumn(name: "TwoFactorEnabled", table: "AspNetUsers");
    migrationBuilder.AlterColumn<string>(
        name: "UserId",
        table: "AspNetUserLogins",
        nullable: false);
    migrationBuilder.AlterColumn<string>(
        name: "UserId",
        table: "AspNetUserClaims",
        nullable: false);
    migrationBuilder.AlterColumn<string>(
        name: "RoleId",
        table: "AspNetRoleClaims",
        nullable: false);
    migrationBuilder.AddColumn<Guid>(
        name: "UserGuid",
        table: "UserProfile",
        nullable: false,
        defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));
    migrationBuilder.AddForeignKey(
        name: "FK_IdentityRoleClaim<string>_IdentityRole_RoleId",
        table: "AspNetRoleClaims",
        column: "RoleId",
        principalTable: "AspNetRoles",
        principalColumn: "Id",
        onDelete: ReferentialAction.Cascade);
    migrationBuilder.AddForeignKey(
        name: "FK_IdentityUserClaim<string>_ApplicationUser_UserId",
        table: "AspNetUserClaims",
        column: "UserId",
        principalTable: "UserProfile",
        principalColumn: "Id",
        onDelete: ReferentialAction.Cascade);
    migrationBuilder.AddForeignKey(
        name: "FK_IdentityUserLogin<string>_ApplicationUser_UserId",
        table: "AspNetUserLogins",
        column: "UserId",
        principalTable: "UserProfile",
        principalColumn: "Id",
        onDelete: ReferentialAction.Cascade);
    migrationBuilder.AddForeignKey(
        name: "FK_IdentityUserRole<string>_IdentityRole_RoleId",
        table: "AspNetUserRoles",
        column: "RoleId",
        principalTable: "AspNetRoles",
        principalColumn: "Id",
        onDelete: ReferentialAction.Cascade);
    migrationBuilder.AddForeignKey(
        name: "FK_IdentityUserRole<string>_ApplicationUser_UserId",
        table: "AspNetUserRoles",
        column: "UserId",
        principalTable: "UserProfile",
        principalColumn: "Id",
        onDelete: ReferentialAction.Cascade);
    migrationBuilder.RenameTable(
        name: "AspNetUsers",
        newName: "UserProfile");
}
```

**Comment by smitpatel** [comment]
It looks like `AddForeignKey` operations uses the new table name and the table is renamed to new name after those operations which causes exception.

**Comment by JaimeStill** [comment]
Correct, I wanted to raise the fact that this is how EF is generating the migration file when working with migration commands.

**Comment by bricelam** [comment]
Yay, our first ordering bug! :smile:

**Comment by bricelam** [comment]
To workaround, just change the name in the generated migration file.

**Comment by JaimeStill** [comment]
Thanks @bricelam I figured as much, just wanted to bring it up for your awareness. Ya'll are doing great work!

**Comment by bricelam** [comment]
@divega @rowanmiller Making this a `pri1` `7.0.0-rc2` bug so I can sleep better at night. :wink: I expect to have the bandwidth to fix it.

**Comment by rowanmiller** [comment]
:+1:
