### ISSUE TITLE
Hierachical TPH table fails to load Parent when Included

### ISSUE THREAD

**Issue by matthewDDennis** [aspnet/EntityFramework#4027]
I have a Hierachical TPH structure where most of the derived types add no properties.

When I make the call below I get the shown error dump.  If I comment out the `.Include(x => x.Parent)` then the call succeeds and loads the children, or at least makes a Sql call that should.

A previous version that was TPC with only the Group having the self reference worked fine.

## The Problem call
```
        public async Task<ApiGroupDescription> GetGroupAsync(int? id)
        {
            if (!id.HasValue)
                return null;

            var results = _dbContext.Groups
                .Include(x => x.Parent)
                .Include(x => x.Children)
                .SingleOrDefaultAsync(m => m.Id == id);

            return await results;
        }
```
## The Base Class
```
    public interface IPostedAndModified
    {
        /// <summary>
        /// Gets or sets the Modified DateTime for the record. Use for optimistic concurrency.
        /// </summary>
        DateTime Modified { get; set; }

        /// <summary>
        /// Gets or sets the Posted DateTime for the described api item.
        /// </summary>
        DateTime Posted { get; set; }
    }

    /// <summary>
    /// This class defines the common properties for parts of an API document or page.
    /// </summary>
    /// <seealso cref="CodeProject.Reference.Models.ApiDoc.IPostedAndModified" />
    public class ApiDescriptionBase : IPostedAndModified
    {
        /// <summary>
        /// Gets or sets the ID for the described api item.
        /// </summary>
        [Key]
        public int Id { get; set; }

        /// <summary> Gets or sets the parent group identifier. </summary>
        public int? ParentId { get; set; }

        /// <summary> Gets or sets the parent group. </summary>
        [ForeignKey("ParentId")]
        public ApiDescriptionBase Parent { get; set; }

        /// <summary> Gets or sets the child groups of the Object or Group. </summary>
        [InverseProperty("Parent")]
        public List<ApiDescriptionBase> Children { get; set; }

        /// <summary>
        /// Gets or sets the Modified DateTime for the record. Use for optimistic concurrency.
        /// </summary>
        public DateTime Modified { get; set; }

        /// <summary>
        /// Gets or sets the Posted DateTime for the described api item.
        /// </summary>
        public DateTime Posted { get; set; }

        /// <summary>
        /// Gets or sets the Title of the DocPart.
        /// </summary>
        [Required]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the Type of the described api item.
        /// </summary>
        /// <remarks>
        /// This should be a hierarchical name starting from the root Description.  It will be used to 
        /// create links to the Type.
        /// </remarks>
        /// <example>Number</example>
        /// <example>window.location</example>
        public string Type {get; set;}

        /// <summary>
        /// Gets or sets the Abstract of the described api item.
        /// </summary>
        [Required]
        [DataType(DataType.MultilineText)]
        public string Abstract { get; set; }

        /// <summary>
        /// Gets or sets the Description of the described api item.
        /// </summary>
        [Required]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    }
```
## The DbContext
```
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public DbSet<ApiDescriptionBase>            ApiDescriptions { get; set; }
        public DbSet<ApiGroupDescription>           Groups          { get; set; }
        public DbSet<ApiMethodSignatureDescription> Methods         { get; set; }
        public DbSet<ApiExceptionDescription>       Exceptions      { get; set; }
        public DbSet<ApiParameterDescription>       Parameters      { get; set; }
        public DbSet<ApiPropertyDescription>        Properties      { get; set; }
        public DbSet<ApiCodeSample>                 Examples        { get; set; }
        public DbSet<ApiCodeSnippet>                CodeSnippets    { get; set; }
```
## The Console Log Dump
```
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ApiDoc/Details/1
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method CodeProject.Reference.Controllers.ApiDocController.Details with arguments (1) - ModelState is Valid'
fail: Microsoft.Data.Entity.Query.Internal.QueryCompiler[1]
      An exception occurred in the database while iterating the results of a query.
      System.InvalidOperationException: Sequence contains more than one matching element
         at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.MaterializerFactory.CreateMaterializer(IEntityType entityType, SelectExpression selectExpression, Func`3 projectionAdder, IQuerySource querySource)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.<CreateIncludeRelatedValuesStrategyFactories>d__13.MoveNext()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
         at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
         at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
         at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
         at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
         at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
         at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
         at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
         at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
         at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
         at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
         at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
         at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
         at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(IncludeSpecification includeSpecification, Type resultType, LambdaExpression accessorLambda, Boolean querySourceRequiresTracking
         at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
         at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
         at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
         at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
         at Microsoft.Data.Entity.Storage.Database.CompileAsyncQuery[TResult](QueryModel queryModel)
         at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileAsyncQuery>b__0()
         at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery[TResult](Object cacheKey, Func`1 compiler)
         at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileAsyncQuery[TResult](Expression query)
         at Microsoft.Data.Entity.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT OBJECT_ID(N'__EFMigrationsHistory');
info: Microsoft.Data.Entity.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT [MigrationId], [ProductVersion]
      FROM [__EFMigrationsHistory]
      ORDER BY [MigrationId];
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0266ms 500 text/html
```

**Comment by smitpatel** [comment]
When included is used on navigation, we join both the tables. This brings projections from target type of relationship into select. From the projections, we try to find discriminator property in the hierarchy of target type using `Single()` to generate predicate on discriminator. This works fine for all cases except in the case of intra-hierarchical relationship. In case of intra-hierarchical relationships, the target type is same table (but uses different alias), therefore now there are 2 projections which refers to same discriminator property with different alias. Using `Single()` on projections to find the discriminator property throws exception since there are 2 projections with matching property.
Solution would be to use `Last()` instead of `Single()` since before generating predicate on discriminator we generate projections, which assures that the last projections corresponds to the table being joined hence we need to add predicate on the last one found.
