### ISSUE TITLE
Many-To-Many relation: Filtering by collection of constants on related entity property produces: Sequence contains more than one element

### ISSUE THREAD

**Issue by kinstya** [aspnet/EntityFramework#4072]
I have the following entity model with many-to-many relationship implemented using junction table which is configured using CF:

```
    public partial class Artifact
    {
        public Artifact()
        {
            ArtifactTags = new HashSet<ArtifactTag>();
        }
        public long ArtifactId { get; set; }
        public virtual ICollection<ArtifactTag> ArtifactTags { get; set; }
  }

    public partial class ArtifactTag
    {
        public long ArtifactId { get; set; }
        public int TagId { get; set; }

        public virtual Artifact Artifact { get; set; }
        public virtual Tag Tag { get; set; }
    }

    public partial class Tag
    {
        public Tag()
        {
            ArtifactTags = new HashSet<ArtifactTag>();
        }
       public int TagId { get; set; }
       public string Name { get; set; }
       public virtual ICollection<ArtifactTag> ArtifactTags { get; set; }
    }
```

// ========== Configuration ========

```
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Artifact>(entity =>
            {
                entity.HasKey(e => e.ArtifactId);
                entity.HasMany(d => d.ArtifactTags).WithOne(p => p.Artifact).HasForeignKey(d => d.ArtifactId).OnDelete(DeleteBehavior.Restrict);
                entity.HasMany(d => d.Files).WithOne(p => p.Artifact).HasForeignKey(d => d.ArtifactId).OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity<ArtifactTag>(entity =>
            {
                entity.HasKey(e => new { e.ArtifactId, e.TagId });
                entity.HasOne(d => d.Artifact).WithMany(p => p.ArtifactTags).HasForeignKey(d => d.ArtifactId).OnDelete(DeleteBehavior.Restrict);
                entity.HasOne(d => d.Tag).WithMany(p => p.ArtifactTags).HasForeignKey(d => d.TagId).OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity<Tag>(entity =>
            {
                entity.HasKey(e => e.TagId);
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(500);
            });
        }
```

/*--------------------------------------------- end of model ---------------------------*/

In test against in-memory storage I'm trying to make search by Tag ids:

```
 var ids = new long[] { 1, 2 };
 var res =  context.Artifacts
                              .Include(a => a.ArtifactTags)
                              .ThenInclude(at => at.Tag)
                                .Where(a => a.ArtifactTags.
                                       Select(at => at.Tag).
                                        Where(t => ids.Contains(t.TagId)).Any());
```

So, trying to materialize the result produces the following IOE:

> 'res.ToList()' threw an exception of type 'System.InvalidOperationException'
    base: {System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass79_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression(MemberExpression memberExpression, Action`2 memberBinder)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Remotion.Linq.Clauses.ResultOperators.ContainsResultOperator.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.RequiresMaterializationExpressionVisitor.FindQuerySourcesRequiringMaterialization(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.QueryCompilationContext.FindQuerySourcesRequiringMaterialization(EntityQueryModelVisitor queryModelVisitor, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)}

**Comment by rowanmiller** [comment]
Confirmed that this reproduced on RC1 and that it is fixed in our working code base (I verified against build 7.0.0-rc2-16619). Here is the code I used to verify.

```c#
using Microsoft.Data.Entity;
using Microsoft.Data.Entity.Metadata;
using System.Collections.Generic;
using System.Linq;

namespace Console
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new MyContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                var tag = new Tag { Name = "Test" };
                context.Tags.Add(tag);

                var artifact = new Artifact { };
                context.Artifacts.Add(artifact);

                var join = new ArtifactTag { Artifact = artifact, Tag = tag };
                context.ArtifactTags.Add(join);

                context.SaveChanges();
            }

            using (var context = new MyContext())
            {
                var ids = new long[] { 1, 2 };
                var res = context.Artifacts
                    .Include(a => a.ArtifactTags)
                    .ThenInclude(at => at.Tag)
                    .Where(a => a.ArtifactTags
                        .Select(at => at.Tag)
                        .Where(t => ids.Contains(t.TagId))
                        .Any())
                    .ToList();

                foreach (var artifact in res)
                {
                    System.Console.WriteLine(artifact.ArtifactId);
                    foreach (var tag in artifact.ArtifactTags)
                    {
                        System.Console.WriteLine(" - " + tag.Tag.Name);
                    }
                }
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Artifact> Artifacts { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<ArtifactTag> ArtifactTags { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=MyDatabase;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Artifact>(entity =>
            {
                entity.HasKey(e => e.ArtifactId);
                entity.HasMany(d => d.ArtifactTags).WithOne(p => p.Artifact).HasForeignKey(d => d.ArtifactId).OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity<ArtifactTag>(entity =>
            {
                entity.HasKey(e => new { e.ArtifactId, e.TagId });
                entity.HasOne(d => d.Artifact).WithMany(p => p.ArtifactTags).HasForeignKey(d => d.ArtifactId).OnDelete(DeleteBehavior.Restrict);
                entity.HasOne(d => d.Tag).WithMany(p => p.ArtifactTags).HasForeignKey(d => d.TagId).OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity<Tag>(entity =>
            {
                entity.HasKey(e => e.TagId);
                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(500);
            });

        }
    }

    public partial class Artifact
    {
        public Artifact()
        {
            ArtifactTags = new HashSet<ArtifactTag>();
        }

        public long ArtifactId { get; set; }
        public virtual ICollection<ArtifactTag> ArtifactTags { get; set; }
    }

    public partial class ArtifactTag
    {
        public long ArtifactId { get; set; }
        public int TagId { get; set; }

        public virtual Artifact Artifact { get; set; }
        public virtual Tag Tag { get; set; }
    }

    public partial class Tag
    {
        public Tag()
        {
            ArtifactTags = new HashSet<ArtifactTag>();
        }
        public int TagId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<ArtifactTag> ArtifactTags { get; set; }
    }
}
```
