### ISSUE TITLE
Batching insert does not work on Linux with SQL Azure

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4228]
Repro: https://github.com/natemcmaster/EntityFramework.PlatformTesting/blob/master/test/SqlAzure/BatchingTest.cs#L26

Inserting more than 1 entity fails on SQL Azure v12. I dug into what is happening and `DbDataReader.HasRows` is `false` when it should return true. For whatever reason, the `DbCommand.ExecuteReader()` does not return as expected.

**Comment by natemcmaster** [comment]
FWIW I tried to reproduce what EF does with [this Linqpad](https://gist.github.com/natemcmaster/82534c60ecfdb6e4779e) script, but data reader returns data. :confused: Not sure why EF is different

**Comment by AndriySvyryd** [comment]
This still fails on Linux. Could be a SqlClient issue:
```
Microsoft.EntityFrameworkCore.DbUpdateException : An error occurred while updating the entries. See the inner exception for details.
 ---- System.Data.SqlClient.SqlException : A transport-level error has occurred when sending the request to the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
 -------- System.IO.IOException : The write operation failed, see inner exception.
 ------------ System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
 Parameter name: size
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
    at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.SqlAzure.SqlAzureBatchingTest.AddWithBatchSize(Int32 batchSize)
 ----- Inner Stack Trace -----
    at System.Data.SqlClient.TdsParser.TdsExecuteRPC(_SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean openConnection, Boolean closeConnection)
    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues, Boolean manageConnection)
    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
 ----- Inner Stack Trace -----
    at System.Net.Security.SslStreamInternal.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
    at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at System.Data.SqlClient.SNI.SNITCPHandle.Send(SNIPacket packet)
 ----- Inner Stack Trace -----
    at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
    at System.Data.SqlClient.SNI.SslOverTdsStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at System.Net.Security.SslStreamInternal.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
```

**Comment by natemcmaster** [comment]
cc @saurabh500 are there still known networking issues on Linux in RC2?

**Comment by saurabh500** [comment]
cc @corivera Can you take a look?

**Comment by saurabh500** [comment]
Is the target server Azure Sql?

**Comment by saurabh500** [comment]
@natemcmaster Have you seen the issue with an on premise server as well? 
Also is this an intermittent issue or persistent?

**Comment by natemcmaster** [comment]
I haven't seen this issue with an on-premise SQL Server, but yes, the issue is persistent. It has been consistently reproduces in EF testing on Linux for the last 4 days.

**Comment by AndriySvyryd** [comment]
And the test didn't run before the last 4 days, so the issue is not from a recent change

**Comment by AndriySvyryd** [comment]
Some specifics. The test runs against AdventureWorks and this query succeeds:
```SQL
INSERT INTO [SalesLT].[Product] ([Color], [DiscontinuedDate], [ListPrice], [Name], [ProductCategoryID], [ProductModelID], [ProductNumber], [SellEndDate], [SellStartDate], [Size], [StandardCost], [ThumbNailPhoto], [ThumbnailPhotoFileName], [Weight])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13);
SELECT [ProductID], [ModifiedDate], [rowguid]
FROM [SalesLT].[Product]
WHERE @@ROWCOUNT = 1 AND [ProductID] = scope_identity();
```

but this fails:
```SQL
DECLARE @toInsert10 TABLE ([Color] nvarchar(15), [DiscontinuedDate] datetime, [ListPrice] money, [Name] nvarchar(450), [ProductCategoryID] int, [ProductModelID] int, [ProductNumber] nvarchar(25), [SellEndDate] datetime, [SellStartDate] datetime, [Size] nvarchar(5), [StandardCost] money, [ThumbNailPhoto] varbinary(max), [ThumbnailPhotoFileName] nvarchar(50), [Weight] decimal, [_Position] [int]);
INSERT INTO @toInsert10
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, 0),
(@p14, @p15, @p16, @p17, @p18, @p19, @p20, @p21, @p22, @p23, @p24, @p25, @p26, @p27, 1),
(@p28, @p29, @p30, @p31, @p32, @p33, @p34, @p35, @p36, @p37, @p38, @p39, @p40, @p41, 2),
(@p42, @p43, @p44, @p45, @p46, @p47, @p48, @p49, @p50, @p51, @p52, @p53, @p54, @p55, 3),
(@p56, @p57, @p58, @p59, @p60, @p61, @p62, @p63, @p64, @p65, @p66, @p67, @p68, @p69, 4),
(@p70, @p71, @p72, @p73, @p74, @p75, @p76, @p77, @p78, @p79, @p80, @p81, @p82, @p83, 5),
(@p84, @p85, @p86, @p87, @p88, @p89, @p90, @p91, @p92, @p93, @p94, @p95, @p96, @p97, 6),
(@p98, @p99, @p100, @p101, @p102, @p103, @p104, @p105, @p106, @p107, @p108, @p109, @p110, @p111, 7),
(@p112, @p113, @p114, @p115, @p116, @p117, @p118, @p119, @p120, @p121, @p122, @p123, @p124, @p125, 8),
(@p126, @p127, @p128, @p129, @p130, @p131, @p132, @p133, @p134, @p135, @p136, @p137, @p138, @p139, 9);

DECLARE @inserted10 TABLE ([ProductID] int, [Color] nvarchar(15), [DiscontinuedDate] datetime, [ListPrice] money, [ModifiedDate] datetime, [Name] nvarchar(450), [ProductCategoryID] int, [ProductModelID] int, [ProductNumber] nvarchar(25), [SellEndDate] datetime, [SellStartDate] datetime, [Size] nvarchar(5), [StandardCost] money, [ThumbNailPhoto] varbinary(max), [ThumbnailPhotoFileName] nvarchar(50), [Weight] decimal, [rowguid] uniqueidentifier, [_Position] [int]);
MERGE [SalesLT].[Product] USING @toInsert10 AS i ON 1=0
WHEN NOT MATCHED THEN
INSERT ([Color], [DiscontinuedDate], [ListPrice], [Name], [ProductCategoryID], [ProductModelID], [ProductNumber], [SellEndDate], [SellStartDate], [Size], [StandardCost], [ThumbNailPhoto], [ThumbnailPhotoFileName], [Weight])
VALUES (i.[Color], i.[DiscontinuedDate], i.[ListPrice], i.[Name], i.[ProductCategoryID], i.[ProductModelID], i.[ProductNumber], i.[SellEndDate], i.[SellStartDate], i.[Size], i.[StandardCost], i.[ThumbNailPhoto], i.[ThumbnailPhotoFileName], i.[Weight])
OUTPUT INSERTED.[ProductID], INSERTED.[Color], INSERTED.[DiscontinuedDate], INSERTED.[ListPrice], INSERTED.[ModifiedDate], INSERTED.[Name], INSERTED.[ProductCategoryID], INSERTED.[ProductModelID], INSERTED.[ProductNumber], INSERTED.[SellEndDate], INSERTED.[SellStartDate], INSERTED.[Size], INSERTED.[StandardCost], INSERTED.[ThumbNailPhoto], INSERTED.[ThumbnailPhotoFileName], INSERTED.[Weight], INSERTED.[rowguid], i._Position
INTO @inserted10;

SELECT [ProductID], [ModifiedDate], [rowguid] FROM @inserted10
ORDER BY _Position;
```

**Comment by divega** [comment]
@AndriySvyryd could you please file a corefx bug for this?

**Comment by saurabh500** [comment]
Please tag @corivera in the CoreFx bug. Cory is looking into it.

**Comment by natemcmaster** [comment]
Verified this is fixed now using corefx 24018
