### ISSUE TITLE
Query :: SelectMany + GroupJoin + DefaultIfEmpty breaks if anything is composed on top of it

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#4262]
Repro query:

```
                var query = from l1 in context.LevelOne
                            join l2 in context.LevelTwo on l1.Id equals l2.Level1_Optional_Id into groupJoin
                            from l2 in groupJoin.DefaultIfEmpty()
                            select l2 == null ? null : l2.Name;
```

Exception thrown is:

Sequence contains no elements
	at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
	Query\RelationalQueryModelVisitor.cs(912,0): at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberOrMethod[TResult](Func`4 memberBinder, IQuerySource querySource, IProperty property, Boolean bindSubQueries)
	Query\RelationalQueryModelVisitor.cs(872,0): at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.<>c__DisplayClass77_0`1.<BindMemberExpression>b__0(IProperty property, IQuerySource qs)
	Query\EntityQueryModelVisitor.cs(1050,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.<>c__DisplayClass78_0`1.<BindMemberExpression>b__0(IEnumerable`1 ps, IQuerySource qs)
	Query\EntityQueryModelVisitor.cs(1070,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpressionCore[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
	Query\EntityQueryModelVisitor.cs(1045,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`3 memberBinder)
	Query\RelationalQueryModelVisitor.cs(871,0): at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, IQuerySource querySource, Func`4 memberBinder, Boolean bindSubQueries)
	Query\RelationalQueryModelVisitor.cs(859,0): at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.BindMemberExpression[TResult](MemberExpression memberExpression, Func`4 memberBinder, Boolean bindSubQueries)
	Query\ExpressionVisitors\RelationalEntityQueryableExpressionVisitor.cs(79,0): at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitMember(MemberExpression node)
	at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	Query\ExpressionVisitors\ExpressionVisitorBase.cs(15,0): at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
	at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
	at System.Linq.Expressions.ConditionalExpression.Accept(ExpressionVisitor visitor)
	at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
	Query\ExpressionVisitors\ExpressionVisitorBase.cs(15,0): at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression node)
	Query\EntityQueryModelVisitor.cs(923,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
	Query\EntityQueryModelVisitor.cs(789,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
	at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
	at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
	Query\EntityQueryModelVisitor.cs(528,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	Query\RelationalQueryModelVisitor.cs(253,0): at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	Query\Internal\SqlServerQueryModelVisitor.cs(77,0): at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
	Query\EntityQueryModelVisitor.cs(158,0): at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
	Storage\Database.cs(67,0): at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	Query\Internal\QueryCompiler.cs(183,0): at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
	Query\Internal\CompiledQueryCache.cs(32,0): at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
	Query\Internal\QueryCompiler.cs(138,0): at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
	Query\Internal\QueryCompiler.cs(84,0): at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
	Query\Internal\EntityQueryProvider.cs(37,0): at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
	at Remotion.Linq.QueryableBase`1.GetEnumerator()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by maumar** [comment]
Test case can be found in ComplexNavigationsQuerySqlServerTest.Select_nav_prop_reference_optional1_via_DefaultIfEmpty
