### ISSUE TITLE
Mapping column to UInt32 throws an invalid cast exception

### ISSUE THREAD

**Issue by TrabacchinLuigi** [aspnet/EntityFramework#4287]
doing so, ef7 will correctly generate a bigger datatype for sql (bigint) but is unabe to "re-hidratate" the class instance with a value, it will throw an invalid cast exception.
Actually i was trying to have UInt32 as Id in my POCO classes.

**Comment by TrabacchinLuigi** [comment]
Well ... actually mapping uint to a bigint could also be considered a waste of space, because of the same amount of bits between uint and int.
But maybe for the consistency of the information it's better to not change this behaviour...

Just saying it would fit into an int column...

**Comment by rowanmiller** [comment]
**Notes for triage:** We do create a schema for the model, so migrations is handling the `uint` and creating a `bigint` column. Both query and save fail though.

SaveChanges exception

```
Microsoft.Data.Entity.DbUpdateException was unhandled
  HResult=-2146233088
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=EntityFramework.Relational
  StackTrace:
       at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
       at Microsoft.Data.Entity.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
       at Microsoft.Data.Entity.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
       at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
       at Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
       at Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
       at Microsoft.Data.Entity.DbContext.SaveChanges()
       at EF7ConsoleApplication.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\Console.CI\Console.CI\Program.cs:line 18
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2147024809
       Message=The parameter data type of UInt32 is invalid.
       Source=System.Data
       StackTrace:
            at System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
            at System.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
            at System.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
            at System.Data.SqlClient.SqlCommand.BuildParamList(TdsParser parser, SqlParameterCollection parameters, Boolean includeReturnValue)
            at System.Data.SqlClient.SqlCommand.BuildExecuteSql(CommandBehavior behavior, String commandText, SqlParameterCollection parameters, _SqlRPC& rpc)
            at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
            at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
            at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
            at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
            at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
            at System.Data.Common.DbCommand.ExecuteReader()
            at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, Boolean openConnection, Boolean closeConnection, IReadOnlyDictionary`2 parameterValues)
            at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, Boolean manageConnection, IReadOnlyDictionary`2 parameterValues)
            at Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
       InnerException: 
```

Query exception

```
System.InvalidCastException was unhandled
  HResult=-2147467262
  Message=Specified cast is not valid.
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , ValueBuffer )
       at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
       at Microsoft.Data.Entity.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
       at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
       at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at EF7ConsoleApplication.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\Console.CI\Console.CI\Program.cs:line 20
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```
