### ISSUE TITLE
Group By with Where clause

### ISSUE THREAD

**Issue by capesean** [aspnet/EntityFramework#4318]
I'm not sure if this is a bug or if I'm writing a bad query, but this worked in EF6.

My model has Projects against which Consultants log Times.

To try get a summary of Times by Consultant on a given Project, I have:

```c#
_dbContext.Times
.Include(t => t.Project)
.Where(t => t.Project.Code == projectCode) // projectCode is a parameter
.GroupBy(t => new { ConsultantId = t.ConsultantId.ToString() }) // just grouping by consultantId for now
.Select(o => new
{
	o.Key.ConsultantId,
	TotalMinutes = o.Sum(t => t.Minutes)
})
```

The error I get is:
`ArgumentException: Expression of type 'System.Func'2[Microsoft.Data.Entity.Query.EntityQueryModelVisitor+TransparentIdentifier'2[Time,Microsoft.Data.Entity.Storage.ValueBuffer],<>f__AnonymousType19'1[System.String]]' cannot be used for parameter of type 'System.Func'2[Time,<>f__AnonymousType19'1[System.String]]' of method 'System.Collections.Generic.IEnumerable'1[System.Linq.IGrouping'2[<>f__AnonymousType19'1[System.String],Time]] _GroupBy[Time,<>f__AnonymousType19'1,Time](System.Collections.Generic.IEnumerable'1[Time], System.Func'2[Time,<>f__AnonymousType19'1[System.String]], System.Func'2[Time,Time])'`

**Comment by rowanmiller** [comment]
Clearing milestone to re-triage as this actually repros on a much simpler query:

```c#
var query = db.Times
    .Where(t => t.Project.Code == projectCode)
    .GroupBy(t => t.ConsultantId);
```

```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Expression of type 'System.Func`2[Microsoft.Data.Entity.Query.EntityQueryModelVisitor+TransparentIdentifier`2[EF7ConsoleApplication.Program+Time,Microsoft.Data.Entity.Storage.ValueBuffer],System.Int32]' cannot be used for parameter of type 'System.Func`2[EF7ConsoleApplication.Program+Time,System.Int32]' of method 'System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[System.Int32,EF7ConsoleApplication.Program+Time]] _GroupBy[Time,Int32,Time](System.Collections.Generic.IEnumerable`1[EF7ConsoleApplication.Program+Time], System.Func`2[EF7ConsoleApplication.Program+Time,System.Int32], System.Func`2[EF7ConsoleApplication.Program+Time,EF7ConsoleApplication.Program+Time])'
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
       at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2)
       at Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleGroup(EntityQueryModelVisitor entityQueryModelVisitor, GroupResultOperator groupResultOperator, QueryModel queryModel)
       at Microsoft.Data.Entity.Query.ResultOperatorHandler.<>c.<.cctor>b__25_9(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel q)
       at Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
       at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
       at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandleGroup(HandlerContext handlerContext)
       at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
       at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
       at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
       at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
       at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
       at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
       at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
       at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
       at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
       at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at EF7ConsoleApplication.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\Console.CI\Console.CI\Program.cs:line 21
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```


Here is a complete repro:

```c#
using Microsoft.Data.Entity;
using System.Linq;

namespace EF7ConsoleApplication
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                var projectCode = "123";

                var query = db.Times
                    .Where(t => t.Project.Code == projectCode)
                    .GroupBy(t => t.ConsultantId);

                query.ToList();
            }
        }

        public class MyContext : DbContext
        {
            public DbSet<Time> Times { get; set; }
            public DbSet<Project> Projects { get; set; }
            public DbSet<Consultant> Consultants { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
            }
        }

        public class Time
        {
            public int TimeId { get; set; }
            public int Minutes { get; internal set; }

            public int ConsultantId { get; set; }
            public Consultant Consultant { get; set; }

            public int ProjectId { get; set; }
            public Project Project { get; set; }
        }

        public class Project
        {
            public int ProjectId { get; set; }
            public string Code { get; set; }
            public string Name { get; set; }
        }

        public class Consultant
        {
            public int ConsultantId { get; set; }
            public string Name { get; set; }
        }
    }
}
```

**Comment by anpete** [comment]
No longer repros on latest bits.

**Comment by capesean** [comment]
Thanks! :+1:
