### ISSUE TITLE
Where(Contains(NavigationProp)) fails with NullRef Exception

### ISSUE THREAD

**Issue by glatzert** [aspnet/EntityFramework#4447]
We were just Building some queries and fell over the following situation:

```c#
public class E1 {
  public int Id { get; set; }
}
public class E2 {
  public int Id { get; set; }
  public E1 NavE1 { get; set; }
}

// Query
var list1 = await dbContext.E1.Where(something).ToListAsync();
var list2 = await dbContext.E2.Where(e2 => list1.Contains(e2.NavE1)).ToListAsync();
```

*Result*
The second query will fail with an NullReference Exception, since NavE1 is not included.

**Comment by rowanmiller** [comment]
In triage we thought this may be due to the where clause being client eval'd and the nav prop being null. But the NullReferenceException actually happens during query compilation. 

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: operand
   at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
   at Microsoft.Data.Entity.Query.Expressions.InExpression..ctor(AliasExpression operand, IReadOnlyList`1 values)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitSubQuery(SubQueryExpression subQueryExpression)
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\Console.RC1\Console.RC1\Program.cs:line 26
```

 Here is a full repro.

```c#
using Microsoft.Data.Entity;
using System.Linq;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var dbContext = new MyContext())
            {
                dbContext.Database.EnsureDeleted();
                dbContext.Database.EnsureCreated();

                var e = new E2
                {
                    NavE1 = new E1()
                };

                dbContext.E2.Add(e);
                dbContext.E1.Add(e.NavE1);
                dbContext.SaveChanges();

                var list1 = dbContext.E1.ToList();

                var list2 = dbContext.E2
                    .Include(e2 => e2.NavE1)
                    .Where(e2 => e2.NavE1 != null && list1.Contains(e2.NavE1))
                    .ToList();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<E1> E1 { get; set; }
        public DbSet<E2> E2 { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }
    }

    public class E1
    {
        public int Id { get; set; }
    }

    public class E2
    {
        public int Id { get; set; }
        public E1 NavE1 { get; set; }
    }
}
```

**Comment by mikary** [comment]
Ran the full repo against current dev and it does not throw anymore.

As written, the query in the reproduction performs client evaluation of the entity comparison (either through change tracking, or if that is disabled object comparison). I am looking into adding test coverage that uses a navigation property on the IDs to work better with the default untracked entities in our query tests.

**Comment by mikary** [comment]
Tests added in #5219
