### ISSUE TITLE
InvalidCastException when using a subquery in a let clause with SQLiteProvider

### ISSUE THREAD

**Issue by ArnaudDebaene** [aspnet/EntityFramework#4459]
Using Entity Framework 7 RC1 with the SQLite provider

Consider the following model with a simple one-to-one relation:

    class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public BlogImage Image { get; set; }
    }
    
    class BlogImage
    {
        public int ObjectId { get; set; }
        public Blog Parent { get; set; }
        public string ImageFormat { get; set; }
        public byte[] ImageBuffer { get; set; }
    }

    class MyDbContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogImage> BlogImages { get; set; }
    
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite(@"Filename=e:\blog.db");
        }
    
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>().HasKey(e => e.Id);
            modelBuilder.Entity<Blog>().HasOne(e => e.Image).WithOne(e => e.Parent).HasForeignKey<BlogImage>(e => e.ObjectId);
    
            modelBuilder.Entity<BlogImage>().HasKey(e => e.ObjectId);
        }
    }

Say i want to get all the Blogs in the DB and know wether or not they have an image, but without the overhead of loading the images themselves.
I tried the following:

    var query = from blog in context.Blogs
                   let hasImage = context.BlogImages.Any(e => e.ObjectId == blog.Id)
                   select new { blog, hasImage };

    foreach(var item in query)
    {
        Console.WriteLine("Blog "+item.blog.Name + (item.hasImage ? " has an image" : " doesn't have an image"));
    }

I get an InvalidCastException when iterating over the query

CallStack:
at Microsoft.Data.Entity.ChangeTracking.Internal.SimpleKeyValueFactory`1.Create(Object value)
at Microsoft.Data.Entity.ChangeTracking.Internal.SimpleKeyValueFactory`1.Create(ValueBuffer valueBuffer)
at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.CreateEntity[TEntity](IQuerySource querySource, ValueBuffer valueBuffer, Int32 valueBufferOffset, QueryContext queryContext, IEntityType entityType, Boolean trackingQuery, KeyValueFactory keyValueFactory, Func`2 materializer, Boolean allowNullResult, Boolean useQueryBuffer)
at lambda_method(Closure , ValueBuffer )
at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
at System.Linq.Enumerable.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
at TestEntityGraphManipulation.Program.Main(String[] args)

I tried a few variations on the query (Count instead of Any, ....), but always stumbled on this exception.

The same query works fine when using the InMemory provider instead of SQLite.

Thank you!

**Comment by rowanmiller** [comment]
Confirmed this is not related to invalid data (as we speculated in triage). Here is a complete repro:

```c#
using Microsoft.Data.Entity;
using System.Linq;
using System;

namespace ConsoleApp1
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var context = new MyDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();

                context.Blogs.Add(new Blog
                {
                    Name = "Test Blog",
                    Image = new BlogImage { ImageFormat = "png" }
                });

                context.SaveChanges();
            }

            using (var context = new MyDbContext())
            {
                var query = from blog in context.Blogs
                            let hasImage = context.BlogImages.Any(e => e.ObjectId == blog.Id)
                            select new { blog, hasImage };

                foreach (var item in query)
                {
                    Console.WriteLine("Blog " + item.blog.Name + (item.hasImage ? " has an image" : " doesn't have an image"));
                }
            }
        }
    }

    class Blog
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public BlogImage Image { get; set; }
    }

    class BlogImage
    {
        public int ObjectId { get; set; }
        public Blog Parent { get; set; }
        public string ImageFormat { get; set; }
        public byte[] ImageBuffer { get; set; }
    }

    class MyDbContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<BlogImage> BlogImages { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite(@"Filename=blog.db");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Blog>()
                .HasKey(e => e.Id);

            modelBuilder.Entity<Blog>()
                .HasOne(e => e.Image)
                .WithOne(e => e.Parent)
                .HasForeignKey<BlogImage>(e => e.ObjectId);

            modelBuilder.Entity<BlogImage>()
                .HasKey(e => e.ObjectId);
        }
    }
}
```

```
System.InvalidCastException was unhandled
  HResult=-2147467262
  Message=Specified cast is not valid.
  Source=EntityFramework.Core
  StackTrace:
       at Microsoft.Data.Entity.ChangeTracking.Internal.SimpleKeyValueFactory`1.Create(Object value)
       at Microsoft.Data.Entity.ChangeTracking.Internal.SimpleKeyValueFactory`1.Create(ValueBuffer valueBuffer)
       at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.CreateEntity[TEntity](IQuerySource querySource, ValueBuffer valueBuffer, Int32 valueBufferOffset, QueryContext queryContext, IEntityType entityType, Boolean trackingQuery, KeyValueFactory keyValueFactory, Func`2 materializer, Boolean allowNullResult, Boolean useQueryBuffer)
       at lambda_method(Closure , ValueBuffer )
       at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
       at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
       at ConsoleApp1.Program.Main(String[] args) in C:\Users\rowmil\Documents\Visual Studio 2015\Projects\Console.RC1\Console.RC1\Program.cs:line 31
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by mikary** [comment]
Ran the complete repro against current dev and the exception was not thrown / valid results were displayed.
