### ISSUE TITLE
SQL Server batching with Identity columns fails for image, text, and ntext columns

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#4478]
Because these types cannot be compared.

Search for "See Issue #4478" in code for tests.

```
An error occurred while updating the entries. See the inner exception for details.
The data types image and image are incompatible in the equal to operator.

at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Update\ReaderModificationCommandBatch.cs:line 167
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Update\Internal\BatchExecutor.cs:line 29
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\RelationalDatabase.cs:line 38
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\ChangeTracking\Internal\StateManager.cs:line 427
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\ChangeTracking\Internal\StateManager.cs:line 367
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\DbContext.cs:line 337
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges() in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore\DbContext.cs:line 301
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.BuiltInDataTypesSqlServerTest.Can_insert_and_read_back_all_mapped_data_types_with_identity_in_batch() in C:\aspnet\EntityFramework\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\BuiltInDataTypesSqlServerTest.cs:line 1395
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, Boolean openConnection, Boolean closeConnection, IReadOnlyDictionary`2 parameterValues) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\Internal\RelationalCommand.cs:line 205
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, Boolean manageConnection, IReadOnlyDictionary`2 parameterValues) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Storage\Internal\RelationalCommand.cs:line 88
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection) in C:\aspnet\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Update\ReaderModificationCommandBatch.cs:line 156
```

**Comment by divega** [comment]
Non-comparable types might be yet another reason to consider using multiple INSERT statements in the batch instead of the more complicated mechanism we have created around multi-row INSERTs. 

Related to #4218.

cc @AndriySvyryd.
