### ISSUE TITLE
Use existing DB with numeric(18,0) primary keys

### ISSUE THREAD

**Issue by Thomas5890** [aspnet/EntityFramework#4594]
Hello,
What’s property type suits best for a primary key column with data type numeric(18,0)? I’ve an existing database. I’d like to use EF 7 as ORM. And, if possible, I’d like to use an autoincrement for the id column to generate new primary keys. What am I doing wrong?
### a)	Using int 
The base class of my some entities looks like this:
```
    public abstract class EntityBase
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        [Required][MaxLength(200)]
        public string Suchname { get; set; }
    }
```
In OnModelCreating override of my DBContext there are these settings for the id column / property.
```
      builder
          .Property(b => b.Id)
          .IsRequired()
          .HasColumnName(idColumn).HasColumnType("numeric(18,0)")
          .UseSqlServerIdentityColumn();
```
When I’am try to fetch data from the DbContext (e.g. with context.Persons.FirstOrDefault()), there’s an InvalidCastException
System.InvalidCastException wurde nicht behandelt.
  HResult=-2147467262
  Message=Die angegebene Umwandlung ist ungültig.
  Source=EntityFramework.Core
  StackTrace:
       bei Microsoft.Data.Entity.ChangeTracking.Internal.IdentityMap`1.TryGetEntry(ValueBuffer valueBuffer, Boolean throwOnNullKey)
       bei Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.TryGetEntry(IKey key, ValueBuffer valueBuffer, Boolean throwOnNullKey)
       bei Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
       bei Microsoft.Data.Entity.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
       bei Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
       bei Microsoft.Data.Entity.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
       bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       bei TestEf7.MainWindow.LadeObjekte_Click(Object sender, RoutedEventArgs e) in d:\VS Projects\TestEf7\TestEf7\MainWindow.xaml.cs:Zeile 36.
  InnerException: null
### b)	Using decimal
The type of Id property is changed to decimal
```
    public abstract class EntityBase
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public decimal Id { get; set; }
```
The override of OnModelCreating of my DBContex now looks like this:
```
     builder
         .Property(b => b.Id)
         .IsRequired()
         .HasColumnName(idColumn).HasColumnType("numeric(18,0)");
   //.UseSqlServerIdentityColumn(); that’s not allowed for decimal props
```

Fetching data works fine, but inserting a new person into database causes an Exception, although the generated Sql is correct, see below. (I’ve have investigated AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation, it seems the reader inside this method is empty.)
```
    using (var context = new TestContext())
    {
        var newPerson = new Person();
        //newPerson.Id = 981;
        // setting other props that are required
        newPerson.Suchname = "Testmann,Heinz";
        newPerson.AeDatum = DateTime.Now;
        newPerson.AePerson = 1;
        newPerson.VPersId = 1;
        newPerson.VDatum = newPerson.AeDatum;
        context.Personen.Add(newPerson);
        context.SaveChanges();
    }
```

Microsoft.Data.Entity.DbUpdateConcurrencyException wurde nicht behandelt.
  HResult=-2146233088
  Message=Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
  Source=EntityFramework.Relational
  StackTrace:
       bei Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
       bei Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithPropagation(Int32 commandIndex, DbDataReader reader)
       bei Microsoft.Data.Entity.Update.AffectedCountModificationCommandBatch.Consume(DbDataReader reader)
       bei Microsoft.Data.Entity.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
       bei Microsoft.Data.Entity.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
       bei Microsoft.Data.Entity.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
       bei Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
       bei Microsoft.Data.Entity.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
       bei Microsoft.Data.Entity.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
       bei Microsoft.Data.Entity.DbContext.SaveChanges()
       bei TestEf7.MainWindow.SpeichereNeuePerson_Click(Object sender, RoutedEventArgs e) in d:\VS Projects\TestEf7\TestEf7\MainWindow.xaml.cs:Zeile 70.

The Sql, generated by Ef7 works fine, if you send it to the database e.g. with MS SQL Server Management Studio
```
DECLARE @p0 DateTime2 SET @p0 = '18.02.2016 08:18:56'
DECLARE @p1 Decimal(18,0) SET @p1 = 1
DECLARE @p2 DateTime2 SET @p2 = ''
DECLARE @p3 NVarChar(Max) SET @p3 = ''
DECLARE @p4 NVarChar(Max) SET @p4 = ''
DECLARE @p5 NVarChar(4000) SET @p5 = 'Testmann,Heinz'
DECLARE @p6 DateTime2 SET @p6 = '18.02.2016 08:18:56'
DECLARE @p7 Decimal(18,0) SET @p7 = 1
DECLARE @p8 NVarChar(Max) SET @p8 = ''

-- Executed query
SET NOCOUNT ON;
DECLARE @toInsert1 TABLE ([AEDATUM] datetime2, [AEPERSID] decimal(18, 2), [GebDat] datetime2, [GebName] nvarchar(max), [Name] nvarchar(max), [SUCHNAME] nvarchar(200), [VDATUM] datetime2, [VPERSID] decimal(18, 2), [Vorname] nvarchar(max), [_Position] [int]);
INSERT INTO @toInsert1
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, 0);
DECLARE @inserted1 TABLE ([PERSID] decimal(18, 2), [AEDATUM] datetime2, [AEPERSID] decimal(18, 2), [GebDat] datetime2, [GebName] nvarchar(max), [Name] nvarchar(max), [SUCHNAME] nvarchar(200), [VDATUM] datetime2, [VPERSID] decimal(18, 2), [Vorname] nvarchar(max));
INSERT INTO [T_OPERSON] ([AEDATUM], [AEPERSID], [GebDat], [GebName], [Name], [SUCHNAME], [VDATUM], [VPERSID], [Vorname])
OUTPUT INSERTED.[PERSID], INSERTED.[AEDATUM], INSERTED.[AEPERSID], INSERTED.[GebDat], INSERTED.[GebName], INSERTED.[Name], INSERTED.[SUCHNAME], INSERTED.[VDATUM], INSERTED.[VPERSID], INSERTED.[Vorname]
INTO @inserted1
SELECT [AEDATUM], [AEPERSID], [GebDat], [GebName], [Name], [SUCHNAME], [VDATUM], [VPERSID], [Vorname] FROM @toInsert1;
SELECT [PERSID]
FROM (SELECT [PERSID], [_Position],
ROW_NUMBER() OVER (PARTITION BY [_t].[PERSID] ORDER BY [_j].[_Position]) AS [_RowNumber1],
ROW_NUMBER() OVER (PARTITION BY [_j].[_Position] ORDER BY [_t].[PERSID]) AS [_RowNumber2]
FROM @inserted1 [_t]
INNER JOIN @toInsert1 [_j] ON ([_t].[AEDATUM] = [_j].[AEDATUM]) AND ([_t].[AEPERSID] = [_j].[AEPERSID]) AND ([_t].[GebDat] = [_j].[GebDat] OR ([_t].[GebDat] is NULL AND [_j].[GebDat] is NULL)) AND ([_t].[GebName] = [_j].[GebName] OR ([_t].[GebName] is NULL AND [_j].[GebName] is NULL)) AND ([_t].[Name] = [_j].[Name] OR ([_t].[Name] is NULL AND [_j].[Name] is NULL)) AND ([_t].[SUCHNAME] = [_j].[SUCHNAME]) AND ([_t].[VDATUM] = [_j].[VDATUM]) AND ([_t].[VPERSID] = [_j].[VPERSID]) AND ([_t].[Vorname] = [_j].[Vorname] OR ([_t].[Vorname] is NULL AND [_j].[Vorname] is NULL))) [_p]
WHERE [_RowNumber1] = [_RowNumber2]
ORDER BY [_Position];
```

**Comment by rowanmiller** [comment]
You want to add a call to `.ValueGeneratedOnAdd()` to your configuration to let EF know that values are generated by the database.

**Comment by rowanmiller** [comment]
**Note for Triage:** `IDENTITY` can be used for decimal types with a scale of `0`, currently we block this with the following exception. We should probably update our logic to match SQL Servers actual requirements.

```
Unhandled Exception: System.ArgumentException: Identity value generation cannot be used for the property 'BlogId' on entity type 'Console.CI.Blog' because the property type is 'Decimal'. Identity value generation can only be used with signed integer properties.
   at Microsoft.Data.Entity.Metadata.SqlServerPropertyAnnotations.SetValueGenerationStrategy(Nullable`1 value)
   at Microsoft.Data.Entity.Metadata.SqlServerPropertyAnnotations.set_ValueGenerationStrategy(Nullable`1 value)
   at Microsoft.Data.Entity.SqlServerPropertyBuilderExtensions.UseSqlServerIdentityColumn(PropertyBuilder propertyBuilder)
   at Microsoft.Data.Entity.SqlServerPropertyBuilderExtensions.UseSqlServerIdentityColumn[TProperty](PropertyBuilder`1 propertyBuilder)
   at Console.CI.BloggingContext.OnModelCreating(ModelBuilder modelBuilder) in c:\users\rowmil\documents\visual studio 2015\Projects\Repro.RC1\Repro.RC1\Program.cs:line 34
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_0(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryService.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ClosedIEnumerableService.CallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.TransientCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass12_0.<RealizeService>b__0(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.DbContext.EntryWithoutDetectChanges[TEntity](TEntity entity)
   at Microsoft.Data.Entity.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState, GraphBehavior behavior)
   at Microsoft.Data.Entity.DbContext.Add[TEntity](TEntity entity, GraphBehavior behavior)
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.Add(TEntity entity, GraphBehavior behavior)
   at Console.CI.Program.Main(String[] args) in c:\users\rowmil\documents\visual studio 2015\Projects\Repro.RC1\Repro.RC1\Program.cs:line 11
Press any key to continue . . .
```

**Comment by Thomas5890** [comment]
Hello Rowan,
Thanks for your quick reply. Unfortunately I am not sure, if got you right and my example still doesn’t save data.
Do you recommend me to use decimal as property type for Id?
Using decimal now there is the following code in override of OnModelCreating
```
            builder
                .Property(b => b.Id)
                .IsRequired()
                .HasColumnName(idColumn)
                .HasColumnType("numeric(18,0)")
                .ValueGeneratedOnAdd();
```

Saving the data still results in the same exception as stated above (and still generating the correct SQL statements for the database):
```
Microsoft.Data.Entity.DbUpdateConcurrencyException
Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded.
```

**Comment by Thomas5890** [comment]
Maybe it is useful - here's the definition of the table I'm trying to save data to:

```
CREATE TABLE [dbo].[T_OPERSON](
	[PERSID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[AEDATUM] [datetime] NOT NULL,
	[AEPERSID] [numeric](18, 0) NOT NULL,
	[GebDat] [datetime2](7) NULL,
	[GebName] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[SUCHNAME] [nvarchar](200) NOT NULL,
	[VDATUM] [datetime] NOT NULL,
	[VPERSID] [numeric](18, 0) NOT NULL,
	[Vorname] [nvarchar](max) NULL,
 CONSTRAINT [PK_T_OPERSON] PRIMARY KEY CLUSTERED 
(
	[PERSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
```

**Comment by rowanmiller** [comment]
@Thomas5890 using the table create script you supplied, here is some code that accesses the database and correctly fetches back the generated `IDENTITY` values on save.

```c#
using Microsoft.Data.Entity;
using System;

namespace Console.CI
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new TestContext())
            {
                var newPerson = new Person();
                newPerson.Suchname = "Testmann,Heinz";
                newPerson.AeDatum = DateTime.Now;
                newPerson.AePerson = 1;
                newPerson.VPersId = 1;
                newPerson.VDatum = newPerson.AeDatum;
                context.Personen.Add(newPerson);
                context.SaveChanges();

                System.Console.WriteLine(newPerson.Id);
            }
        }
    }

    class TestContext : DbContext
    {
        public DbSet<Person> Personen { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Sample;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>()
                .ToTable("T_OPERSON");

            modelBuilder.Entity<Person>()
                .Property(p => p.Id)
                .HasColumnName("PERSID")
                .HasColumnType("numeric(18,0)")
                .ValueGeneratedOnAdd();

            modelBuilder.Entity<Person>()
                .Property(p => p.AeDatum)
                .HasColumnName("AEDATUM");

            modelBuilder.Entity<Person>()
                .Property(p => p.AePerson)
                .HasColumnName("AEPERSID");

            modelBuilder.Entity<Person>()
                .Property(p => p.Suchname)
                .HasColumnName("SUCHNAME");

            modelBuilder.Entity<Person>()
                .Property(p => p.VDatum)
                .HasColumnName("VDATUM");

            modelBuilder.Entity<Person>()
                .Property(p => p.VPersId)
                .HasColumnName("VPERSID");
        }
    }

    public class Person
    {
        public decimal Id { get; set; }
        public DateTime AeDatum { get; internal set; }
        public decimal AePerson { get; internal set; }
        public DateTime GebDat { get; internal set; }
        public string GebName { get; internal set; }
        public string Name { get; internal set; }
        public string Suchname { get; internal set; }
        public DateTime VDatum { get; internal set; }
        public decimal VPersId { get; internal set; }
        public string Vorname { get; internal set; }
    }
}
```

**Comment by Thomas5890** [comment]
It still doesn’t work on my pc (with still the same exception). I pasted in your code into a new project with no modifications but the connection string.
Do you use a version where the issue is already fixed?
I’m currently using EF 7 RC 2 16649 running on .Net Framework 4.5.1 with SqlServer Express 2014.

**Comment by rowanmiller** [comment]
@Thomas5890 I was using RC1, just tried on the latest build and I see the same error. I think it is a manifestation of https://github.com/aspnet/EntityFramework/issues/4478.

**Comment by Thomas5890** [comment]
Okay, thank you so far. I’ll wait until the related bug is fixed.

**Comment by rowanmiller** [comment]
We are keeping this issue open to track relaxing the restrictions around what is allowed to be configured as an `IDENTITY` column.
