### ISSUE TITLE
Error when querying with two Contains statements

### ISSUE THREAD

**Issue by SoftwareFactor** [aspnet/EntityFramework#4597]
We have the following code:

           var result = DB.Incidents
                           .Include(c => c.Car)
                           .Include(u => u.User)
                           .Where(o => o.User.LastName.Contains("Rol") && o.Car.NumberPlate.Contains("B"))
                         .ToList();

It throws us this exception:

```
An exception of type 'System.InvalidCastException' occurred in mscorlib.dll but was not handled in user code
Additional information: Unable to cast object of type 'System.Linq.Expressions.FieldExpression' to type 'System.Linq.Expressions.ParameterExpression'.
```

Here is stack trace:

```
at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
  at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
  at System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
  at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
  at Microsoft.Data.Entity.Query.ExpressionVisitors.Internal.IncludeExpressionVisitor.VisitMethodCall(MethodCallExpression expression)
  at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
  at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
  at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
  at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(IncludeSpecification includeSpecification, Type resultType, LambdaExpression accessorLambda, Boolean querySourceRequiresTracking)
  at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
  at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
  at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
  at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
  at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
  at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
  at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
  at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
  at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
  at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
  at Remotion.Linq.QueryableBase`1.GetEnumerator()
  at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
  at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

The package we use are:
* "EntityFramework.Core": "7.0.0-rc1-final"
* "EntityFramework7.Npgsql": "3.1.0-rc1-3"

**Comment by mikary** [comment]
Verified that this exception is thrown (using EntityFramework.MicrosoftSqlServer 7.0.0-rc1-final) but it does not reproduce in current dev. Most likely, this was resolved by unrelated changes / fixes for `Include` and `Contains`.
