### ISSUE TITLE
dbcontext scaffold throws an error

### ISSUE THREAD

**Issue by gdoron** [aspnet/EntityFramework#4724]
Using RC1-Final

Running `dnx ef dbcontext scaffold "[My connection string]" EntityFramework.MicrosoftSqlServer`

Outputs the following error to the console:

> System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at System.Data.SqlClient.SqlBuffer.get_String()
   at System.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at Microsoft.Data.Entity.Scaffolding.SqlServerDatabaseModelFactory.GetIndexes()
   at Microsoft.Data.Entity.Scaffolding.SqlServerDatabaseModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.Data.Entity.Scaffolding.RelationalScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.Data.Entity.Scaffolding.SqlServerScaffoldingModelFactory.Create(String connectionString, TableSelectionSet tableSelectionSet)
   at Microsoft.Data.Entity.Scaffolding.Internal.ReverseEngineeringGenerator.GetMetadataModel(ReverseEngineeringConfiguration configuration)
   at Microsoft.Data.Entity.Scaffolding.Internal.ReverseEngineeringGenerator.GenerateAsync(ReverseEngineeringConfiguration configuration, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.Design.DatabaseOperations.ReverseEngineerAsync(String provider, String connectionString, String outputDir, String dbContextClassName, List`1 schemas, List`1 tables, Boolean useDataAnnotations, CancellationToken cancellationToken)
   at Microsoft.Data.Entity.Commands.Program.Executor.<>c__DisplayClass11_0.<<ReverseEngineerAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Data.Entity.Commands.Program.Executor.<ExecuteAsync>d__13.MoveNext()
**Data is Null. This method or property cannot be called on Null values.**

@rowanmiller if you want the connection string, I can email it to you, I still have your email from the time I worked at  Schneider Electric.

Thanks.

**Comment by lajones** [comment]
@gdoron We used to have an issue where several bits of code called `GetString()` (or other `SqlDataReader.GetXyz()` methods) without checking whether the data was null first. Those have all been updated now - so it's fixed in the nightly builds. But if you'd like to send @rowanmiller your connection string he can pass it on to me and I can check that we no longer see the error.

**Comment by gdoron** [comment]
@lajones I tried to migrate to the nightly builds, but I honestly have no idea how to do that, I couldn't find enough information how to do so, and just changing `dnx` to `dotnet` commands didn't cut it...
So if you have some blog post about that, it would be really helpful.

Anyway I emailed @rowanmiller.

Thank you both :thumbsup:

**Comment by lajones** [comment]
@gdoron I agree that getting going on the nightly builds right now is a big mess and I would not recommend it til the work to pin down all the dotnet-cli tools has completed. But I received the connection string and I confirm that scaffolding works fine against that connection string on the most recent builds. We no longer see any error. So I'll go ahead and close this out.

**Comment by gdoron** [comment]
@lajones There are 201 closed issues in the rc2 milestone, but they all can't be tested by the community since _"it is a big mess"_.
And bugs that I find (and I believe it's the same with others) I had to guess if it was already fix in the dev branch or not, and I might be wrong and not report bugs...
I hope there will be some sort of upgrading manual soon before RC2-final will go live.

Thanks
