### ISSUE TITLE
UseRowNumberPaging causes NRE in complex queries

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#4739]
Repro:
ComplexNavigationsQuerySqlServerTest.Include_with_groupjoin_skip_and_take

Change ComplexNavigationsQuerySqlServerFixture to use row number paging.

Expected:
Instead of offset/fetch, the query generated should use row number paging.

Result:
```
	System.NullReferenceException : Object reference not set to an instance of an object.
	at lambda_method(Closure , ValueBuffer )
	Query\EntityLoadInfo.cs(27,0): at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
	Query\Internal\QueryBuffer.cs(70,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
	Query\ExpressionVisitors\Internal\BufferedEntityShaper`.cs(32,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
	Query\ExpressionVisitors\Internal\BufferedOffsetEntityShaper.cs(26,0): at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedOffsetEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
	Query\QueryMethodProvider.cs(255,0): at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_GroupJoin>d__26`4.MoveNext()
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	Query\Internal\LinqOperatorProvider.cs(125,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	ComplexNavigationsQueryTestBase.cs(1938,0): at Microsoft.EntityFrameworkCore.FunctionalTests.ComplexNavigationsQueryTestBase`2.Include_with_groupjoin_skip_and_take()
	ComplexNavigationsQuerySqlServerTest.cs(887,0): at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.ComplexNavigationsQuerySqlServerTest.Include_with_groupjoin_skip_and_take()
```

The test throws on this query:
```c#
(from l1 in context.LevelOne
    .Include(e => e.OneToMany_Optional)
    .ThenInclude(e => e.OneToOne_Optional_FK)
join l2 in context.LevelTwo.Include(e => e.OneToOne_Required_PK)
on (int?)l1.Id equals (l2 != null ? l2.Level1_Optional_Id : null) into grouping
where l1.Name != "L1 03"
select new { l1, grouping }).Skip(1).Take(5)
```

**Comment by natemcmaster** [comment]
cc @maumar looks like this was added with changes for #4706

**Comment by smitpatel** [comment]
The issue here is in translation of FETCH/OFFSET into rownumber query. We are generating incorrect Sql, due to which materializer throws NRE.

**Comment by smitpatel** [comment]
@maumar
