### ISSUE TITLE
GroupBy after SelectMany: Microsoft.Data.Entity.Query.EntityQueryModelVisitor+TransparentIdentifier cannot be used ...

### ISSUE THREAD

**Issue by mdmoura** [aspnet/EntityFramework#4786]
Hello,

I am using EntityFramework 7 RC1 and I have the following:

    context.Organizations
       .SelectMany(x => 
            context.Users.Select(y => 
               new Leadership { 
                  OrganizationId = x.Id, 
                  UserId = y.Id }))
            .GroupBy(z => z.OrganizationId)
            .ToList();

With this I get the error:

'System.Func`2[Microsoft.Data.Entity.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.Data.Entity.Storage.ValueBuffer,Microsoft.Data.Entity.Storage.ValueBuffer],System.Int32]' cannot be used for parameter of type 'System.Func`2[Leadership,System.Int32]' of method 'System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[System.Int32,Leadership]] _GroupBy[Leadership,Int32,Leadership](System.Collections.Generic.IEnumerable`1[Leadership], System.Func`2[Leadership,System.Int32], System.Func`2[Leadership,Leadership])'

The error is avoided adding a ToList() before GroupBy but that loads everything into memory.

The Model is the following:

    public class Organization {
      public Int32 Id { get; set; }
      public String Name { get; set; }
      public virtual ICollection<Leadership> Leaderships { get; set; } = new List<Leadership>();
    }

    public class Leadership {    
      public Int32 OrganizationId { get; set; }
      public Int32 UserId { get; set; }
      public virtual Organization Organization { get; set; }
      public virtual User User { get; set; }
    }

    public class User : IdentityUser<Int32> {    
      public virtual ICollection<Leadership> Leaderships { get; set; } = new List<Leadership>();
    }

And the configuration is:

     public class Context : IdentityDbContext<User, Role, Int32> {

         protected override void OnModelCreating(ModelBuilder builder) {

          base.OnModelCreating(builder);

          builder.Entity<Organization>(b => {
            b.ToTable("Organizations");
            b.HasKey(x => x.Id);
            b.Property(x => x.Id).UseSqlServerIdentityColumn();
            b.Property(x => x.Name).IsRequired().HasMaxLength(100);
          });
 
          builder.Entity<Leadership>(b => {
            b.ToTable("Leaderships");
            b.HasKey(x => new { x.OrganizationId, x.UserId });
            b.HasOne(x => x.Organization).WithMany(x => x.Leaderships).HasForeignKey(x => x.OrganizationId).IsRequired();
            b.HasOne(x => x.User).WithMany(x => x.Leaderships).HasForeignKey(x => x.UserId).IsRequired();
           });
       }
    }

The full stack is:

'System.Func`2[Microsoft.Data.Entity.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.Data.Entity.Storage.ValueBuffer,Microsoft.Data.Entity.Storage.ValueBuffer],System.Int32]' cannot be used for parameter of type 'System.Func`2[Leadership,System.Int32]' of method 'System.Collections.Generic.IEnumerable`1[System.Linq.IGrouping`2[System.Int32,Leadership]] _GroupBy[Leadership,Int32,Leadership](System.Collections.Generic.IEnumerable`1[Leadership], System.Func`2[Leadership,System.Int32], System.Func`2[Leadership,Leadership])'

at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1, Expression arg2)
   at Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleGroup(EntityQueryModelVisitor entityQueryModelVisitor, GroupResultOperator groupResultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.ResultOperatorHandler.<>c.<.cctor>b__25_9(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel q)
   at Microsoft.Data.Entity.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator)
   at Microsoft.Data.Entity.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

Thank You,
Miguel

**Comment by rowanmiller** [comment]
@mikary can you verify if this is fixed

**Comment by anpete** [comment]
Confirmed fixed in 1.0.0
