### ISSUE TITLE
Windows 10 UWP with Sqlite: remove-migration error

### ISSUE THREAD

**Issue by patrickadamek** [aspnet/EntityFramework#4812]
Trying to remove a migration via remove-migration in an UWP App results in the following error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Der Prozess besitzt keine Paketidentität. (Exception from HRESULT: 0x80073D54)
   at Windows.Storage.ApplicationData.get_Current()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Data.Sqlite.SqliteConnection.GetApplicationData()
   at Microsoft.Data.Sqlite.SqliteConnection.AdjustForRelativeDirectory(String path)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.Data.Entity.Storage.RelationalConnection.Open()
   at Microsoft.Data.Entity.Storage.Internal.SqliteRelationalConnection.Open()
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.Execute[T](IRelationalConnection connection, Func`3 action, String executeMethod, Boolean openConnection, Boolean closeConnection)
   at Microsoft.Data.Entity.Storage.Internal.RelationalCommand.ExecuteScalar(IRelationalConnection connection, Boolean manageConnection)
   at Microsoft.Data.Entity.Migrations.HistoryRepository.Exists()
   at Microsoft.Data.Entity.Migrations.HistoryRepository.GetAppliedMigrations()
   at Microsoft.Data.Entity.Migrations.Design.MigrationsScaffolder.RemoveMigration(String projectDir, String rootNamespace)
   at Microsoft.Data.Entity.Design.MigrationsOperations.RemoveMigration(String contextType)
   at Microsoft.Data.Entity.Design.OperationExecutor.<RemoveMigrationImpl>d__13.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

This is true if the database path / connection string is specified as connection string or dbconnection. Also it does not matter if the path is relative or absolute.

**Comment by bricelam** [comment]
We should skip checking the database on UWP projects and always issue a warning instead.

**Comment by rowanmiller** [comment]
@natemcmaster did we just add the `-Force` option, or do we actually " skip checking the database on UWP projects and just always issue a warning about rewriting history instead."

**Comment by natemcmaster** [comment]
We added `-Force` that [defaults to true](https://github.com/natemcmaster/EntityFramework/blob/c83b9c9fd72fb8935fd563613660786c75f9c278/src/Microsoft.EntityFrameworkCore.Commands/tools/EntityFramework.psm1#L374) on UWP.
```ps1
$forceRemove = $Force -or (IsUwpProject $dteProject)
```

**Comment by rowanmiller** [comment]
Ah, I missed that part. Thanks :smile:
