### ISSUE TITLE
Given expression does not contain searched expression

### ISSUE THREAD

**Issue by brianro** [aspnet/EntityFramework#4819]
Hi Everyone,

I created this test project for a previous bug and now nearly all the tests are throwing errors. Could someone please take a look at the project and see what I am doing wrong? The objective is to use projection to reduce the number of fields returned in the SQL query. Additionally, profiling the two "join" queries are creating disparate SQL, where I expected a single query for each.

Thanks,
B.

[BugDemo.zip](https://github.com/aspnet/EntityFramework/files/176776/BugDemo.zip)

Test Name:	EFTest.query_ef_test_abc
Test FullName:	BugDemoEF.EFTest.query_ef_test_abc
Test Source:	C:\Code\General\BugDemo\src\BugDemoEF\EFTests.cs : line 69
Test Outcome:	Failed
Test Duration:	0:00:00.047

Result StackTrace:	
at Remotion.Linq.Clauses.ExpressionVisitors.AccessorFindingExpressionVisitor.FindAccessorLambda(Expression searchedExpression, Expression fullExpression, ParameterExpression inputParameter)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.IncludeNavigations(QueryModel queryModel, IReadOnlyCollection`1 includeSpecifications)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
   at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.First[TSource](IQueryable`1 source)
   at BugDemoEF.EFTest.query_ef_test_abc() in C:\Code\General\BugDemo\src\BugDemoEF\EFTests.cs:line 72
Result Message:	
The given expression 'new A() {Id = [a].Id, B = new B() {Id = [a.B].Id, AId = [a].Id}, CId = [a].CId, C = new C() {Id = Property([a], "CId")}}' does not contain the searched expression '[a]' in a nested NewExpression with member assignments or a MemberBindingExpression.
Parameter name: fullExpression

**Comment by smitpatel** [comment]
which version of ef are you using?
I tried running this in latest codebase and it is running without exception.
Setup:
DbContext & Classes:
````c#
public class EntityA
{
	public int Id { get; set; }
	public int EntityCId { get; set; }
	public EntityB EntityB { get; set; }
	public EntityC EntityC { get; set; }
}

public class EntityB
{
	public int Id { get; set; }
	public int EntityAId { get; set; }
	public EntityA EntityA { get; set; }
}

public class EntityC
{
	public EntityC()
	{
		EntityAs = new List<EntityA>();
	}
	public int Id { get; set; }
	public ICollection<EntityA> EntityAs { get; set; }
}

public class MyContext : DbContext
{
	public DbSet<EntityA> EntityAs { get; set; }
	public DbSet<EntityB> EntityBs { get; set; }
	public DbSet<EntityC> EntityCs { get; set; }
	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
		=> optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=BugDemo;Trusted_Connection=True;MultipleActiveResultSets=true");

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<EntityA>(b =>
			{
				b.HasKey(a => a.Id);

				b.HasOne(a => a.EntityC)
					.WithMany(c => c.EntityAs)
					.HasForeignKey(a => a.EntityCId);
			});

		modelBuilder.Entity<EntityB>(b =>
			{
				b.HasKey(a => a.Id);

				b.HasOne<EntityA>()
					.WithOne(a => a.EntityB)
					.HasForeignKey<EntityB>(a => a.EntityAId);
			});
	}
}
````
Test code:
````c#
[Fact]
public virtual void Bug_demo_test()
{
	using (var ctx = new MyContext())
	{
		ctx.Database.EnsureDeleted();
		ctx.Database.EnsureCreated();

		var entityA = new EntityA { EntityB = new EntityB() };
		var entityC = new EntityC();
		entityC.EntityAs.Add(entityA);
		ctx.Add(entityC);

		ctx.SaveChanges();
	}

	using (var ctx = new MyContext())
	{
		var item = (from a in ctx.EntityAs.Include(a => a.EntityB).Include(a => a.EntityC)
					select new EntityA
					{
						Id = a.Id,
						EntityB = new EntityB
						{
							Id = a.EntityB.Id,
							EntityAId = a.Id
						},
						EntityCId = a.EntityCId,
						EntityC = new EntityC
						{
							Id = a.EntityC.Id
						}
					}).First();

		Assert.Equal(1, item.Id);
		Assert.Equal(1, item.EntityB.Id);
		Assert.Equal(1, item.EntityB.EntityAId);
		Assert.Equal(1, item.EntityC.Id);
	}
}
````

**Comment by brianro** [comment]
All 7.0.0-rc1-final.

B.

**Comment by smitpatel** [comment]
Confirmed this was a bug in RC1-final but has been fixed already in latest codebase.
