### ISSUE TITLE
Scaffolding brings 'System.ComponentModel.DataAnnotations.ValidationResult' as entity type

### ISSUE THREAD

**Issue by Sheens1983** [aspnet/EntityFramework#4827]
I created my models using the dnx ef dbcontext scaffold command and created my first repository to select the data. When trying to select an object (from any model repo) I get the error "The property 'MemberNames' on entity type 'System.ComponentModel.DataAnnotations.ValidationResult' has not been added to the model or ignored."

The stack trace if as follows:

```
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.Data.Entity.Metadata.Internal.InternalModelBuilder.Validate()
   at Microsoft.Data.Entity.ModelBuilder.Validate()
   at Microsoft.Data.Entity.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.<>c__DisplayClass8_0.<GetModel>b__0(Type k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Data.Entity.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.Data.Entity.Internal.DbContextServices.CreateModel()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_5(IServiceProvider p)
   at lambda_method(Closure , ServiceProvider )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_0(IServiceProvider p)
   at lambda_method(Closure , ServiceProvider )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Storage.DatabaseProviderServices.GetService[TService]()
   at Microsoft.Data.Entity.Storage.RelationalDatabaseProviderServices.get_QueryContextFactory()
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.<>c.<AddQuery>b__1_0(IServiceProvider p)
   at lambda_method(Closure , ServiceProvider )
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Data.Entity.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.<.ctor>b__2_0()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at LBS.ActionLearning.SDB.DAL.EmploymentRepository.GetSingleItem(SingleCriteria`1 criteria) in C:\Users\sheenapatel\Documents\lbs_canvas\LBS.ActionLearning\LBS.ActionLearning.SDB.DAL\EmploymentRepository.cs:line 34
   at LBS.ActionLearning.WebUI.Areas.ClassList.Controllers.ProfilesController.ProcessResults(IEnumerable`1 userProfiles, IEnumerable`1 courseEnrollments) in C:\Users\sheenapatel\Documents\lbs_canvas\LBS.ActionLearning\LBS.ActionLearning.WebUI\Areas\ClassList\Controllers\ProfilesController.cs:line 74
   at LBS.ActionLearning.WebUI.Areas.ClassList.Controllers.ProfilesController.Participants() in C:\Users\sheenapatel\Documents\lbs_canvas\LBS.ActionLearning\LBS.ActionLearning.WebUI\Areas\ClassList\Controllers\ProfilesController.cs:line 53
```

Am I missing a reference or something? Thanks in advance!

**Comment by smitpatel** [comment]
Can you share your model classes & DbContext?

**Comment by Sheens1983** [comment]
Model::
    public partial class Person
    {
        public int LBSNo { get; set; }
        public string Nationality { get; set; }
    }

Context::
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>(entity =>
            {
                entity.HasKey(e => e.LBSNo);

                entity.Property(e => e.Nationality)
                    .HasMaxLength(50)
                    .HasColumnType("varchar");
            });
        }

        public virtual DbSet<Person> Person { get; set; }

The actual database table contains lots of columns but these 2 are the only ones I need. I have tried using all the columns but the same error message is thrown

**Comment by Sheens1983** [comment]
I managed to resolve the issue but still unsure what the underlying problem was? I recreated the project but built the models & datacontext from scratch rather than auto generating using the scaffold script.

**Comment by smitpatel** [comment]
>  I get the error "The property 'MemberNames' on entity type 'System.ComponentModel.DataAnnotations.ValidationResult' has not been added to the model or ignored."

This error suggests that type 'System.ComponentModel.DataAnnotations.ValidationResult' has been added as entity type which should not happen. Seems like error in scaffolding somewhere. cc: @lajones

**Comment by lajones** [comment]
Could you post the generated classes exactly as scaffolding generated them before you made any edits to them? Also the full `dnx ef dbcontext scaffold` command would be useful.

**Comment by lajones** [comment]
We haven't heard back and I can't repro this problem, so closing. Feel free to reopen if you still see the problem in the latest builds.
