### ISSUE TITLE
InvalidOperationException seeding database

### ISSUE THREAD

**Issue by rynowak** [aspnet/EntityFramework#4828]
I'm seeing an exception while seeding the db during startup. Repro project here: https://github.com/aspnet/Performance/tree/18b0daa9f5deeb34a671c48f9bf892edcfafdc9d/testapp/BasicApi

Exception is thrown here: https://github.com/aspnet/Performance/blob/18b0daa9f5deeb34a671c48f9bf892edcfafdc9d/testapp/BasicApi/Startup.cs#L159

```
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean skipInitialFixup, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.<>c__DisplayClass6_0.<StateChanged>b__0(IEntityStateListener l)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.Dispatch(Action`1 action)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at BasicApi.Startup.CreateDatabase(IServiceProvider services) in D:\k\Performance\testapp\BasicApi\Startup.cs:line 159
   at BasicApi.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in D:\k\Performance\testapp\BasicApi\Startup.cs:line 86
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.Startup.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
crit: Microsoft.AspNetCore.Hosting.Internal.WebHost[6]
      Application startup exception
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.StateChanged(InternalEntityEntry entry, EntityState oldState, Boolean skipInitialFixup, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.<>c__DisplayClass6_0.<StateChanged>b__0(IEntityStateListener l)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.Dispatch(Action`1 action)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph(EntityEntryGraphNode node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.DbContext.SetEntityState[TEntity](TEntity entity, EntityState entityState)
   at BasicApi.Startup.CreateDatabase(IServiceProvider services) in D:\k\Performance\testapp\BasicApi\Startup.cs:line 159
   at BasicApi.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory) in D:\k\Performance\testapp\BasicApi\Startup.cs:line 86
   --- End of inner exception stack trace ---
```

**Comment by ajcvickers** [comment]
This issue here is using the same List instance as the navigation property on multiple entities. This is not supported. We discussed trying to detect this and throwing with a better message, but it doesn't seem like the value would be enough given the performance/memory costs of detecting it. To fix the code do a ToList on the tags instance each time it is used to create a navigation property. For example, 
```C#
new Pet() { Category = categories[0], Name = "Cat 1", Status = "available", Tags = tags.ToList(), },
```

**Comment by rynowak** [comment]
oops :laughing: - glad this turned out to be my mistake

**Comment by RehanSaeed** [comment]
Was just stung by this, only way to figure this out was to stumble on this issue. Could a Roslyn Analyzer or some compile time checking be done to catch this type of stuff? Maybe a Development mode for EF that turns on heavier checking.
