### ISSUE TITLE
The binary operator Equal is not defined

### ISSUE THREAD

**Issue by pariesz** [aspnet/EntityFramework#4852]
The relational / id naming conventions seem to be applied even when specifying all keys and relationships using FluentAPI:

### Exception
    System.InvalidOperationException: The binary operator Equal is not defined for the types 'System.Nullable`1[System.Int32]' and 'System.String'.
     at System.Linq.Expressions.Expression.GetEqualityComparisonOperator(ExpressionType binaryType, String opName, Expression left, Expression right, Boolean liftToNull)
     at System.Linq.Expressions.Expression.Equal(Expression left, Expression right, Boolean liftToNull, MethodInfo method)
     at System.Linq.Expressions.Expression.MakeBinary(ExpressionType binaryType, Expression left, Expression right)
     at Microsoft.Data.Entity.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.ProcessComparisonExpression(BinaryExpression binaryExpression)
     at Microsoft.Data.Entity.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitBinary(BinaryExpression binaryExpression)
     at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
     at Microsoft.Data.Entity.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
     at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
     at Remotion.Linq.Clauses.WhereClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
     at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
     at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
     at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
     at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
     at Microsoft.Data.Entity.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
     at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
     at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
    --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
     at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
     at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
     at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
     at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
     at Remotion.Linq.QueryableBase`1.GetEnumerator()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

### Test
    var services = new ServiceCollection();
    services.AddEntityFramework().AddSqlServer().AddDbContext<Context>(ob => ob.UseSqlServer("test"));
    var db = services.BuildServiceProvider().GetService<Context>();

    var result = db.Parents.SelectMany(p => p.Children).ToArray();

### DbContext
    public class Context : DbContext {
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Child> Children { get; set; }

        protected override void OnModelCreating(ModelBuilder builder) {
            builder.Entity<Parent>(b => {
                b.HasKey(p => p.Id);
                b.HasMany(p => p.Children).WithOne(c => c.Parent).HasPrincipalKey(p => p.Id).IsRequired();
            });
            builder.Entity<Child>(b => {
                b.HasKey(c => c.Id);
                b.HasOne(c => c.Parent).WithMany(p => p.Children).HasPrincipalKey(p => p.Id).IsRequired();
            });
        }
    }

### Entities
    public class Parent {
        public int Id { get; set; }
        public string ParentId { get; set; }
        public IList<Child> Children { get; set; }
    }

    public class Child {
        public int Id { get; set; }
        public virtual Parent Parent { get; set; }
    }

### Dependancies
    "EntityFramework.Core": "7.0.0-rc1-*",
    "EntityFramework.MicrosoftSqlServer": "7.0.0-rc1-*"

### Workaround
remove the Parent's ParentId property:

    public class Parent {
        public int Id { get; set; }
        public IList<Child> Children { get; set; }
    }

**Comment by smitpatel** [comment]
This works fine in latest codebase.
