### ISSUE TITLE
Query intermittently produces incorrect results on timeout

### ISSUE THREAD

**Issue by mikary** [aspnet/EntityFramework#4919]
There appears to be an issue on the CI where several tests will fail due to incorrect results while others fail due to a `SqlException` "Timeout Expired." This appears to be a potential data corruption issue as the results are incorrect but no exception is thrown.

```
[Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QueryNavigationsSqlServerTest.Select_Navigation] Assert.Equal() Failure
Expected: 830
Actual:   781
   at Microsoft.EntityFrameworkCore.FunctionalTests.QueryNavigationsTestBase`1.Select_Navigation() in C:\BuildAgent\work\16b2695b987e66d0\test\Microsoft.EntityFrameworkCore.FunctionalTests\QueryNavigationsTestBase.cs:line 317
   at Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests.QueryNavigationsSqlServerTest.Select_Navigation() in C:\BuildAgent\work\16b2695b987e66d0\test\Microsoft.EntityFrameworkCore.SqlServer.FunctionalTests\QueryNavigationsSqlServerTest.cs:line 52
```

Several more examples in in the CI logs.

**Comment by divega** [comment]
@mikary to investigate if this is an issue with the seeding of the test database or something more concerning.
