### ISSUE TITLE
Select related entities throws "Value cannot be null. Parameter name: querySource"

### ISSUE THREAD

**Issue by StefH** [aspnet/EntityFramework#4968]
Tested with _frameworks_:

-  dnx452 
-  dnxcore50

Tested with _servers_:
-  SQLite
-  MicrosofSQLServer

<br/>

**BlogContext**
```c#
    public class BlogContext : DbContext
    {
        public BlogContext(DbContextOptions options)
            : base(options)
        {
        }

        public DbSet<Blog> Blogs { get; set; }

        public DbSet<Post> Posts { get; set; }
    }
```

**Blog**
```c#
    public class Blog
    {
        public int BlogId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Post> Posts { get; set; }
    }
```

**Post**
```c#
    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public virtual Blog Blog { get; set; }

        public DateTime PostDate { get; set; }

        public int NumberOfReads { get; set; }
    }
```

Test code is:
```c#
var test = _context.Blogs.Select(x => new { x.BlogId, x.Name, x.Posts }).ToArray();
```

I get this exception:
```
System.ArgumentNullException : Value cannot be null.
      Parameter name: querySource
      Stack Trace:
           at Microsoft.Data.Entity.Utilities.Check.NotNull[T](T value, String parameterName)
           at Microsoft.Data.Entity.Query.QuerySourceExtensions.HasGeneratedItemName(IQuerySource querySource)
           at Microsoft.Data.Entity.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
           at Microsoft.Data.Entity.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
           at System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
           at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
           at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
           at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
           at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
           at System.Linq.Expressions.ExpressionVisitor.VisitAndConvert[T](ReadOnlyCollection`1 nodes, String callerName)
           at Remotion.Linq.Parsing.RelinqExpressionVisitor.VisitNew(NewExpression expression)
           at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
           at Microsoft.Data.Entity.Query.ExpressionVisitors.ExpressionVisitorBase.Visit(Expression expression)
           at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.ReplaceClauseReferences(Expression expression, IQuerySource querySource, Boolean inProjection)
           at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
           at Remotion.Linq.Clauses.SelectClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel)
           at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
           at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
           at Microsoft.Data.Entity.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
           at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
           at Microsoft.Data.Entity.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
        --- End of stack trace from previous location where exception was thrown ---
           at Microsoft.Data.Entity.Query.Internal.QueryCompiler.<>c__DisplayClass18_0`1.<CompileQuery>b__0()
           at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
           at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
           at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
           at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
           at Remotion.Linq.QueryableBase`1.GetEnumerator()
           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
           at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)

```
Test code can be found at : https://github.com/StefH/System.Linq.Dynamic/tree/master/Src/System.Linq.Dynamic.dnx.Tests

**Comment by StefH** [comment]
I'm using version "7.0.0-rc1-final".

**Comment by rowanmiller** [comment]
@StefH thanks for the fantastic bug report... made our job a LOT easier! This is assigned to someone from our team to be fixed.

**Comment by StefH** [comment]
I'm glad I could help on this issue. Initially I thought this issue was related to not-supported lazy loading from EF.

**Comment by maumar** [comment]
@StefH I verified that this scenario works in current bits. It will be available in RC2 release.
