### ISSUE TITLE
Migrations: Can't Add-Migration in WPF app (ArgumentException: Path cannot be the empty string or all whitespace.)

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/EntityFramework#5274]
Repro steps:
* VS2015 Update 2
* New WPF app (.NET 4.5.2 - default in VS2015.2)
* `PM> Install-Package Microsoft.EntityFrameworkCore.SqlServer -Pre -Source https://www.myget.org/F/aspnetcirelease/api/v3/index.json`
* `PM> Install-Package Microsoft.EntityFrameworkCore.Tools -Pre -Source https://www.myget.org/F/aspnetcirelease/api/v3/index.json`
* Add any EF model (I used [this one](http://docs.efproject.net/en/latest/platforms/full-dotnet/new-db.html#create-your-model))
* `PM> Add-Migration Test`

Results in the following:
```
PM> Add-Migration Test
System.ArgumentException: Path cannot be the empty string or all whitespace.
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.Save(String projectDir, ScaffoldedMigration migration, String outputDir)
   at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Path cannot be the empty string or all whitespace.
```

**Comment by rowanmiller** [comment]
Found testing against `1.0.0-rc2-20820`

**Comment by rowanmiller** [comment]
When fixing this, also make sure that relative paths in `-OutDir` work. At the moment, it puts them in a relative path to the compiled binaries (i.e. `bin\debug\...`).

```
PM> Add-Migration Test -OutputDir Migrations
Add-Migration : Cannot add the link because the source file 'Migrations\20160505192531_Test.cs' cannot be found.
At line:1 char:1
+ Add-Migration Test -OutputDir Migrations
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Add-Migration], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Add-Migration
```

I'm assuming this has the same root cause of the project directory not being picked up.

**Comment by rowanmiller** [comment]
BTW as a workaround to this entire issue, you can specify an absolute path in `-OutDir` to a folder within you project.
