### ISSUE TITLE
Query: String concatenation on a nav prop fails

### ISSUE THREAD

**Issue by AlexBilonog** [aspnet/EntityFramework#5347]
I use EntityFrameworkCore version: 1.0.0-rc3-20831, .Net Framework: 4.6, AspNet.Mvc: 5.2.3
Code:

`var fullNames = _dbContext.Set<UserRole>().Select(r => r.User.FirstName + " " + r.User.LastName).ToList();`

Throws:
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
Additional information: The binary operator Add is not defined for the types 'System.String' and 'System.String'.
   at System.Linq.Expressions.Expression.GetUserDefinedBinaryOperatorOrThrow(ExpressionType binaryType, String name, Expression left, Expression right, Boolean liftToNull)
   at System.Linq.Expressions.Expression.Add(Expression left, Expression right, MethodInfo method)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func2 transformation)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_01.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase1.GetEnumerator()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at EventManager.Business.UsersManager.GetUserRolesQuery() in C:\Work\EventManager\trunk\06-Source\EventManager.Business\UsersManager.cs:line 449

But this code (without nav props) works fine:

`var fullNames = _dbContext.Set<UserRole>().Select(r => r.CreationUser + " " + r.CreationUser).ToList();`

**Comment by rowanmiller** [comment]
@anpete should this be doing client eval until we support translation?

**Comment by anpete** [comment]
Yep, looks like a bug in nav rewrite. cc @maumar

**Comment by rowanmiller** [comment]
Should the client eval part be fixed in 1.0.0? We move translation out to 1.0.1.

**Comment by anpete** [comment]
Yes, I suspect it should be quick because it looks like we just need to pass the correct method info when we rebuild the binary expression.

**Comment by maumar** [comment]
Fixed in b8870c0946e069a70c143613962aa4817024c760
