### ISSUE TITLE
Metadata: Exception in model validation if derived type is discovered before base type

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#5547]
### Steps to reproduce
Model and context
```
public class MyContext : DbContext
{
    public DbSet<TicketBatch> TicketBatches { get; set; }
    public DbSet<PrintBatch> PrintBatches { get; set; }
    public DbSet<Ticket> Tickets { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;");
    }
}

public class TicketBatch
{
    [Key]
    public int Id { get; set; }
    public List<Ticket> Tickets { get; set; }
}

public class PrintBatch : TicketBatch
{
}

public class Ticket
{
    [Key]
    public Guid Guid { get; set; }

    public int TicketBatchId { get; set; }

    public TicketBatch TicketBatch { get; set; }
}
```

### The issue
Model building fails.
```
using (var db = new MyContext())
{
    var model = db.Model;
}
```
```
Exception message: Exception: System.InvalidOperationException: The entity type 'PrintBatch' should derive from 'TicketBatch' to reflect the hierarchy of the corresponding CLR types.
Stack trace:
at Microsoft.EntityFrameworkCore.Internal.ModelValidator.ShowError(String message)
at Microsoft.EntityFrameworkCore.Internal.ModelValidator.EnsureClrInheritance(IModel model, IEntityType entityType, HashSet`1 validEntityTypes)
at Microsoft.EntityFrameworkCore.Internal.ModelValidator.EnsureClrInheritance(IModel model)
at Microsoft.EntityFrameworkCore.Internal.RelationalModelValidator.Validate(IModel model)
at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.EntityFrameworkCore.DbContext.get_Model()
at ModelApp.Program.Main(String[] args)
```
If the name of the dbset of `TicketBatches` is changed to `ATicketBatches` (or anything which comes before `PrintBatches` alphabetically) it works fine.

### Further technical details

EF Core version: RC2-final
Operating system: Win10
Visual Studio version: VS2015.2

Other details about my project setup:

**Comment by smitpatel** [comment]
The issue here is `[key]` annotation sets key with CS.DataAnnotation which CS.Convention could not remove and doesn't set the base type conventionally.

**Comment by divega** [comment]
Sounds to me like something we should try to fix for RTM. BTW, this is one of the issues we found in the repro we obtained from the customer for #5406.

**Comment by divega** [comment]
We agreed this should be fixed in RTM with @smitpatel @bricelam and @ajcvickers.

**Comment by RichardJDay** [comment]
Whats the actual fix for this ?
Value cannot be null. (Parameter 'builder')
