### ISSUE TITLE
No mapping to a relational type can be found for the CLR type 'System.UInt16'

### ISSUE THREAD

**Issue by MicahZoltu** [aspnet/EntityFramework#5663]
### Steps to reproduce
1. Create SQL Server database with some table having an `int` column.
2. Attempt to query using an `Int16` in the Where clause:
   `
   UInt16 foo = 5;
   dbContext.Table
       .Where(x => x.intColumn == foo)
       .ToList();
   `
3. **NOTICE** the exception.
4. Attempt to inline typecast to Int32 with `.Where(x => x.intColumn == (Int32)foo)`
5. **NOTICE** the compiler optimizes out the typecast, so you still get the exception.
### The issue

I expect to be able to use losslessly convertible types in where clauses, such as `UInt16` when querying an `Int32` column in the database.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: No mapping to a relational type can be found for the CLR type 'System.UInt16'
Stack trace:
fail: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.InvalidOperationException: No mapping to a relational type can be found for the CLR type 'System.UInt16'
         at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapperExtensions.GetMapping(IRelationalTypeMapper typeMapper, Type clrType, Boolean unicode)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBuilder.AddParameter(String invariantName, String name, Type type, Boolean unicode)
         at Microsoft.EntityFrameworkCore.Storage.RelationalCommandBuilderExtensions.AddParameter(IRelationalCommandBuilder commandBuilder, String invariantName, String name, Type type, Boolean unicode)
         at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitParameter(ParameterExpression expression)
         at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
         at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
         at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitUnary(UnaryExpression expression)
         at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
         at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
         at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitBinary(BinaryExpression expression)
         at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
         at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
         at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.VisitSelect(SelectExpression selectExpression)
         at Remotion.Linq.Parsing.ThrowingExpressionVisitor.Visit(Expression expression)
         at Microsoft.EntityFrameworkCore.Query.Sql.DefaultQuerySqlGenerator.GenerateSql(IReadOnlyDictionary`2 parameterValues)
         at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.GetRelationalCommand(IReadOnlyDictionary`2 parameters)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```
### Further technical details

EF Core version: `1.0.0-rc2-final`
Operating system: Windows 10
Visual Studio version: VS 2015
### Workaround

Try to trick the compiler into not optimizing out the typecast.  The following works for me at the moment, but I suspect the compiler may optimize it out in some situations.

```
UInt16 foo = 5;
Int32 foo32 = foo;
dbContext.Table
    .Where(x => x.intColumn == foo32)
    .ToList();
```

**Comment by divega** [comment]
Note from triage: it seems interesting that the issue may be caused by removing the convert node. If we didn't to it for subtrees that we end up funcletize, the parameter would be of a supported type.
