### ISSUE TITLE
After second SaveChanges() EF loses added new dependents

### ISSUE THREAD

**Issue by AlexBilonog** [aspnet/EntityFramework#5734]
After second SaveChanges() EF loses added new dependents:
```
using (var db = new TheContext())
{
   var user = db.Set<User>().AsQueryable().First();
   var userDepartment = new UserDepartment { DepartmentID = 1 };
   user.UserDepartments.Add(userDepartment);
   db.SaveChanges(); // After this line: user.UserDepartments: Count = 1 (OK)
   db.SaveChanges(); // After this line: user.UserDepartments: Count = 0 (Wrong)
   db.SaveChanges(); // By executing this line exception: The association between entity types 'User' and 'UserDepartment' has been severed but the foreign key for this relationship cannot be set to null
}
```

EF Core version: 1.0.0-rc3-21338
Operating system: Windows 10
Visual Studio version: VS 2015 last updates
StackTrace:
```
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at EFGetStarted.ConsoleApp.Program.Main() in C:\Work\Console4\EFGetStarted.ConsoleApp\Program.cs:line 21
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by ajcvickers** [comment]
@AlexBilonog Can you post the code for the entity types User and UserDepartment and any code you have in OnConfiguring?

Note for triage: I have been able to reproduce the issue where the navigation properties get corrupted, but so far not the conceptual null exception.

**Comment by AlexBilonog** [comment]
Can provide code only next Monday. But I can add some details. UserID is NOT NULL FK. On Delete and On Update setting is Restrict.

**Comment by dc-m** [comment]
I am getting this issue on 1.1.0 exact same code style as originally posted and same error.

**Comment by ajcvickers** [comment]
@dc-m Please open a new issue and include a project or the code needed to reproduce what you are seeing.
