### ISSUE TITLE
Query: Short-circuiting is not working

### ISSUE THREAD

**Issue by sam-wheat** [aspnet/EntityFramework#5736]
### Steps to reproduce

``` C#
        public async Task<List<ContentItem>> GetContentItems(int siteID, int menuID, int? groupID, DateTime? dateFilter)
        {
            var query = from item in db.ContentItems
                        from mi in item.MenuContentItems
                        where (menuID == 0 || mi.MenuID == menuID) 
                        && (groupID == null || groupID == 0 || item.ContentGroupID == groupID)
                        && ((dateFilter == null) || (item.PublishDate.HasValue && item.PublishDate.Value.Month == dateFilter.Value.Month && item.PublishDate.Value.Year == dateFilter.Value.Year))
                        && mi.Menu.SiteID == siteID
                        && item.Active
                        select item;

            return await query.ToListAsync();
        }
```

### The issue
if the left side of an or expression is true then the right side should not be evaluated in the where clause.
This query:
from c in db.customers where (true || c.id == 999) select c
should generate this sql
select * from customers

If you are seeing an exception, include the full exceptions details (message and stack trace).
An exception was thrown while attempting to evaluate the LINQ query parameter expression 'value(Blog.Services.ContentItemService+<>c__DisplayClass3_0).dateFilter.Value.Month'.
```
Exception message:
An exception was thrown while attempting to evaluate the LINQ query parameter expression 'value(Blog.Services.ContentItemService+<>c__DisplayClass3_0).dateFilter.Value.Month'.

Stack trace:
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.TryExtractParameter(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitMember(MemberExpression memberExpression)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.ParameterExtractingExpressionVisitor.ExtractParameters(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExtractParameters(Expression query, QueryContext queryContext)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blog.Services.ContentItemService.<GetContentItems>d__3.MoveNext() in C:\Git\Blog\src\Blog.Services\ContentItemService.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blog.Core.ServiceCallWrapper`1.<TryAsync>d__5`1.MoveNext() in C:\Git\Blog\src\Blog.Core\ServiceClient.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Blog.API.Controllers.BlogController.<GetContentItems>d__4.MoveNext() in C:\Git\Blog\src\Blog.API\Controllers\BlogController.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.FilterActionInvoker.<InvokeActionFilterAsync>d__41.MoveNext()
```

### Further technical details

EF Core version: (found in project.json or packages.config)
"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0-rc2-final",
Operating system: Windows 10
Visual Studio version: (e.g. VS 2013 or n/a) 2015 

Other details about my project setup:

**Comment by divega** [comment]
@sam-wheat Thanks for reporting this. In the meanwhile you can workaround it by extracting the year and month parts of the parameter outside the query, e.g.:

``` C#
        public async Task<List<ContentItem>> GetContentItems(int siteID, int menuID, int? groupID, DateTime? dateFilter)
        {

            var yearFilter = dateFilter?.Year;
            var monthFilter = dateFilter?.Month;

            var query = from item in db.ContentItems
                        from mi in item.MenuContentItems
                        where (menuID == 0 || mi.MenuID == menuID) 
                            && (groupID == null || groupID == 0 || item.ContentGroupID == groupID)
                            && ((dateFilter == null) || 
                                (item.PublishDate.Value.Month == monthFilter  
                                    && item.PublishDate.Value.Year == yearFilter))
                            && mi.Menu.SiteID == siteID
                            && item.Active
                        select item;

            return await query.ToListAsync();
        }
```

Note that checking for `item.PublishDate.HasValue` isn't necessary for this particular query.

Hope this helps.

**Comment by sam-wheat** [comment]
Thank you divega.

**Comment by smitpatel** [comment]
@sam-wheat - Can you share your model classes & DbContext? I am not able to repro from the top query.
Meanwhile I also tried the shorter query. Following test passes using northwind database. And it generates the Sql as you described. 
```
[Fact]
public virtual void Test()
{
    using (var context = CreateContext())
    {
        var query = from c in context.Customers where (true || c.CustomerID == "ALFKI") select c;
        query.ToList();

        Assert.Equal(
            @"SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region]
FROM [Customers] AS [c]",
            Sql);
    }
}
```

**Comment by divega** [comment]
@smitpatel it repros with this part of the query only:

``` C#
&& ((dateFilter == null) || (item.PublishDate.HasValue && item.PublishDate.Value.Month == dateFilter.Value.Month && item.PublishDate.Value.Year == dateFilter.Value.Year))
```
The rest if handled correctly.

**Comment by anpete** [comment]
@divega Yeah, that's what I figured, too. Thoughts on how to deal with this?

**Comment by divega** [comment]
Ah, and it repros when `dateFilter == null`. Problems is that funcletization still tries to evaluate dateFilter.Value. I was also surprised to see we introduced a parameter for `dateFilter` when the evaluation of `== null` should happen in memory.

**Comment by divega** [comment]
@anpete I haven't had any great insight on this so far :smile: I wish the compiler supported `?.` in the expression tree because that would be a more natural way to write this query and possibly would be much easier for us to support. 

Other than that, maybe it would require us to look at a bigger subtree and implement the short circuit logic in funcletization. E.g. currently we wouldn't look at the whole expression above and think we can funcletize it because it contains server correlated stuff after the `||` operator, but the truth is, if `dataFilter == null` we don't need to translate the rest.

**Comment by divega** [comment]
BTW, the reason we put this in 1.0.1 is because I wanted us to evaluate if there is anything simple we can do. If it becomes very complex and we think it won't help in a large number of scenarios we can move this to the backlog.

**Comment by anpete** [comment]
@divega I have some initial thoughts we can talk about in person.

**Comment by sam-wheat** [comment]
@divega  I have dozens of queries that use this syntax please accept my vote for inclusion in 1.0.  As you mention there are workarounds but not very elegant.

**Comment by rowanmiller** [comment]
@sam-wheat it's not going to make it in to 1.0.0 purely due to timing (we are pretty much locked down on the code base now). We have it on the list of issues to look at in the following release.
