### ISSUE TITLE
The non-generic EntityQueryProvider.Execute() throws InvalidCastException for some expressions

### ISSUE THREAD

**Issue by dxvm** [aspnet/EntityFramework#5982]
### Steps to reproduce

Run the test.

```
public class TestFixture {
    public class TestEntity {
        public int Id { get; set; }
    }

    public class TestContext : DbContext {
        public DbSet<TestEntity> TestEntities { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) {
            optionsBuilder.UseInMemoryDatabase();
        }
    }

    [Fact]
    public void Test() {
        var context = new TestContext();
        Func<IQueryable<TestEntity>, int> func = Queryable.Count;
        IQueryable q = context.TestEntities;
        var expr = Expression.Call(null, func.Method, Expression.Constant(q));
        Assert.Equal(0, q.Provider.Execute<int>(expr)); // fine
        Assert.Equal(0, (int)q.Provider.Execute(expr)); // exception
    }
}
```
### The issue

Provider.Execute throws an exception

```
Test 'efcore_instantfeedback.TestFixture.Test' failed: System.InvalidCastException : Unable to cast object of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Int32]' to type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.QueryContext,System.Object]'.
    at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
    at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
    at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
    at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute(Expression expression)
```

The same code works fine for EF6 and LINQ to Objects.
### Further technical details

EF Core version: 1.0.0

**Comment by rowanmiller** [comment]
This is lower priority as it doesn't look like a common scenario, but we would take a pull request sooner if you want to take a look at fixing it.

**Comment by BladeWise** [comment]
I have made a pull request to address the issue. Waiting for a review.
