### ISSUE TITLE
NullReferenceException if FromSql returns no data

### ISSUE THREAD

**Issue by corradolab** [aspnet/EntityFramework#6039]
```
public class SomeTotals
{
  [Key] // required by EF but unused
  public Decimal Sales { get; set; }
}

string sql = "select sum(Sales) as Sales from SomeTable where SomeField > @p0";
return context.SomeTable.FromSql(sql, aParam).FirstOrDefault();

```
Execute a Query using FromSql.<br/>
Let the query return a custom type, not directly backed by a physical table. <br/>
If the query returns no results, I get NullReferenceException. <br/>
No error if the query returns any result.

```
Exception message:
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (27ms) [Parameters=[@p0='?', @p1='?'], CommandType='Text', CommandTimeout='30']
      SELECT    sum(Incassato) as Incassato FROM Rilevazioni WHERE  [Data]>=@p0  AND [Data]<@p1
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.UnbufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
   at Microsoft.EntityFrameworkCore.Query.AsyncQueryMethodProvider.<>c__DisplayClass3_0`1.<_ShapedQuery>b__0(ValueBuffer vb)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.SelectAsyncEnumerable`2.SelectAsyncEnumerator.get_Current()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Rileva.Controllers.StatisticheController.<Get>d__2.MoveNext() in C:\Users\....\StatisticheController.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ObjectMethodExecutor.<CastToObject>d__40`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 2565.7791ms 500 application/json
```

EF Core 1.0 with SQL Server (LocalDB)
Windows 10
Visual Studio 2015

**Comment by anpete** [comment]
@corradolab Change the Sales property to be *decimal?*. When the predicate matches no rows, SQL Server returns a single row containing a NULL value. 

I will try and improve the error that gets generated here.

**Comment by corradolab** [comment]
@anpete   By MSDN SingleOrDefault "Returns the first element of a sequence, or a default value if the sequence contains no elements" so I would expect an empty SalesTotal object. In this simple example changing Sales to decimal? could be ok, but it doesn't sound good to change the entity just to accomodate the error. Now I just handle the exception and return a new SalesTotal object.

**Comment by anpete** [comment]
> so I would expect an empty SalesTotal object

Do you mean a null SalesTotal object? If so, you will get one iif the underlying "sequence contains no elements". However, in this case, the sequence is not empty, but contains a single element - the row resulting from the SUM operation.

Can you change your SQL query to something like this?

```sql
select t.Sales
from (select sum(Sales) as Sales from SomeTable where SomeField > @p0) as t
where t.Sales is not null
```

**Comment by corradolab** [comment]
I went for something like this:

`select sum(Sales) as Sales, sum(Revenues) as Revenues, sum(..) as ... from SomeTable where SomeField > @p0 having sum(Sales) is not null`

It's easier to write with a lot of aggregated fields.
Thank you for your help.
