### ISSUE TITLE
Using boolean properties on a referenced entity throws ArgumentException

### ISSUE THREAD

**Issue by ac-esousa** [aspnet/EntityFramework#6092]
### Steps to reproduce
Ideally include a complete code listing that we can run to reproduce the issue.
Alternatively, you can provide a project/solution that we can run.

Try to run the console application on github:

        https://github.com/ac-esousa/EFBooleanBug

### The issue
If I have two entities, and try to filter by a boolean property on a referenced entity, EF throws ArgumentException. For instance:

        public class EntityA
        {
            [Key]
            public int Id { get; set; }

            public EntityB EntityB { get; set; }
        }

        public class EntityB
        {
            [Key]
            public int Id { get; set; }

            public bool IsActive { get; set; }
        }

The following query will fail:

            var data = context.EntityA
                .Where(e => e.EntityB.IsActive)
                .ToList();

Exception thrown:

        System.ArgumentException

Exception message:

        Expression of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[EFBooleanBug.EntityA,System.Collections.Generic.IEnumerable`1[EFBooleanBug.EntityB]],EFBooleanBug.EntityB],System.Nullable`1[System.Boolean]]' cannot be used for parameter of type 'System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[EFBooleanBug.EntityA,System.Collections.Generic.IEnumerable`1[EFBooleanBug.EntityB]],EFBooleanBug.EntityB],System.Boolean]' of method 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[EFBooleanBug.EntityA,System.Collections.Generic.IEnumerable`1[EFBooleanBug.EntityB]],EFBooleanBug.EntityB]] _Where[TransparentIdentifier`2](System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[EFBooleanBug.EntityA,System.Collections.Generic.IEnumerable`1[EFBooleanBug.EntityB]],EFBooleanBug.EntityB]], System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[EFBooleanBug.EntityA,System.Collections.Generic.IEnumerable`1[EFBooleanBug.EntityB]],EFBooleanBug.EntityB],System.Boolean])'

Stack trace:

```
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
````

### Further technical details

EF Core version:

        "Microsoft.EntityFrameworkCore": "1.0.0",
        "Microsoft.EntityFrameworkCore.InMemory": "1.0.0",
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        }

Operating system: Windows 10 x64
Visual Studio version: VS2015 with Update 3

### Workaround

The following query works fine:

            var data = context.EntityA
                .Where(e => e.EntityB.IsActive == true)
                .ToList();

**Comment by maumar** [comment]
verified this is fixed in dev, most likely by https://github.com/aspnet/EntityFramework/commit/add3939bd592f1c4a7f249b81d024a2ff260091d, closing
