### ISSUE TITLE
sqlite, decimal and academic number - System.FormatException: Input string was not in a correct format #1057

### ISSUE THREAD

**Issue by leo90skk** [aspnet/EntityFramework#6205]
### Steps to reproduce
Build a Sqlite DB with a table with a field with decimal(16,8).
Update the field with the value 0.0001 and try to make a linq select wit .ToList();

### The issue

I have a code similar to this:
```
IQueryable<Instrument> query = context.Instruments
                .Include(x => x.Tags)
                .Include(x => x.Exchange)
                .Include(x => x.PrimaryExchange)
                .Include(x => x.Datasource)
                .Include(x => x.Sessions)
                .Include(x => x.ContinuousFuture)
                .Include(x => x.ContinuousFuture.UnderlyingSymbol)
                .AsQueryable();
IQueryable<Instrument> query;
var allInstruments = query.ToList();
```

At the last line, i face an exception.

This issue seems to be similar with #1057.

```
Exception message: "Input string was not in a correct format." (System.FormatException)
Stack trace:
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDecimal(Int32 ordinal)
   at lambda_method(Closure , DbDataReader )
   at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_Include>d__30`1.MoveNext()\
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[...]
```

The database table had a content like this:
```
sqlite> select ID, Symbol, Name, Strike, MinTick FROM instruments;
4|EUR/USD|EUR/USD price||1.0e-05
5|SPY|SPDR S&P 500 ETF Trust||0.01
6|GBP/USD|GBP/USD||
7|USD/JPY|USD/JPY||
8|AUD/USD|AUD/USD||
sqlite> 
```

After i deleted all decimal values with ``sqlite> UPDATE instruments SET MinTick = NULL;``

```
sqlite> select ID, Symbol, Name, Strike, MinTick FROM instruments;
4|EUR/USD|EUR/USD price||
5|SPY|SPDR S&P 500 ETF Trust||
6|GBP/USD|GBP/USD||
7|USD/JPY|USD/JPY||
8|AUD/USD|AUD/USD||
sqlite> 
```

The exception was gone.
So i strongly belief it has to do with the academic number style that sqlite produces and send to the EF Library...

### Further technical details

EF Core version: 1.0.0
Operating system: ubuntu 14.04 LTS - linux
Visual Studio version: n/a

**Comment by natemcmaster** [comment]
The issue is actually in Microsoft.Data.Sqlite.

https://github.com/aspnet/Microsoft.Data.Sqlite/blob/dev/src/Microsoft.Data.Sqlite/SqliteDataReader.cs#L420-L421

In order to parse exponential form, we need to use the [NumberStyles](https://docs.microsoft.com/en-us/dotnet/core/api/system.globalization.numberstyles) option when calling `decimal.Parse`. e.g. `decimal.Parse("1.0e-05", System.Globalization.NumberStyles.Float)`
