### ISSUE TITLE
CLI commands: database drop throws ObjectDisposedException

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/EntityFramework#6371]
### Steps to reproduce
`dotnet ef database drop` on a project that uses Startup and .AddDbContext.

### The issue
The command discovers the database correctly, but when it attempts to actually drop the database, it throws:

```
> dotnet ef database drop
This command will permanently drop the database:
    Database name : main
    Data source   : ./test.db
Are you sure you want to proceed? (y/N) y
System.ObjectDisposedException: Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to
 use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using
dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'AppDbContext'.
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.DbContextOperations.DropDatabase(String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.DropDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Further technical details

Microsoft.EntityFrameworkCore.Tools.DotNet 1.0.0-preview3-21911

**Comment by flensrocker** [comment]
I'm still seeing this error with EFCore 1.1.5, when I have a scoped DbContext. As far as I can see, the first DbContext is created (and disposed) in `DbContextOperations.GetContextInfo`. When it comes to the "drop database" command, the same already disposed DbContext is used.

If I use `AddDbContext` with a lifetime of transient, everything is ok.

**Comment by natemcmaster** [comment]
@flensrocker can you open a new issue? Although the error may look the same, it is likely a different issue.

**Comment by flensrocker** [comment]
Ok, I will do and also try to setup a repository for reproduction. Thanks!
