### ISSUE TITLE
Incorrect SQL generated for multiple "from" clauses

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/EntityFramework#6390]
### Steps to reproduce
```
// program.cs
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.Logging;

namespace ConsoleApp1
{
	public class Book
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}

	public class Author
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}

	public class Reader
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}

	public class Context : DbContext
	{
		public Context(DbContextOptions<Context> options) : base(options)
		{
		}

		protected override void OnModelCreating(ModelBuilder builder)
		{
			base.OnModelCreating(builder);
			builder.Entity<Book>(b => { b.Property(x => x.Id).ValueGeneratedNever(); });
			builder.Entity<Author>(b => { b.Property(x => x.Id).ValueGeneratedNever(); });
			builder.Entity<Reader>(b => { b.Property(x => x.Id).ValueGeneratedNever(); });
		}

		public DbSet<Book> Books { get; set; }
		public DbSet<Author> Authors { get; set; }
		public DbSet<Reader> Readers { get; set; }
	}

	public class Program
	{
		public static void Main(string[] args)
		{
			var sp = new ServiceCollection().AddLogging().AddEntityFramework().BuildServiceProvider();
			var builder = new DbContextOptionsBuilder<Context>();
			builder.UseSqlServer($"Server=(localdb)\\mssqllocaldb;Database=test;Trusted_Connection=True;MultipleActiveResultSets=true"); ;
			var b = new Book { Id = 2, Name = "Book" };
			var a = new Author { Id = 2, Name = "Author" };
			var r = new Reader { Id = 2, Name = "Reader" };
			using (var c = new Context(builder.Options))
			{
				var serviceProvider = c.GetInfrastructure();
				var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
				loggerFactory.AddConsole();

				c.Database.EnsureDeleted();
				c.Database.EnsureCreated();

				c.Add(a);
				c.Add(b);
				c.Add(r);
				c.SaveChanges();

				// exception is thrown here
				var book = (from b1 in c.Books
							from a1 in c.Authors
							from r1 in c.Readers
							select new { b1 }).FirstOrDefault();
			}
		}
	}
}
```

```
// project.json
{
	"version": "1.0.0-*",
	"buildOptions": {
		"emitEntryPoint": true
	},

	"dependencies": {
		"Microsoft.EntityFrameworkCore": "1.0.0",
		"Microsoft.EntityFrameworkCore.SqlServer": "1.0.0",
		"Microsoft.Extensions.Logging.Console": "1.0.0",
		"Microsoft.NETCore.App": {
			"type": "platform",
			"version": "1.0.0"
		}

	},

	"frameworks": {
		"netcoreapp1.0": {}
	}
}
```
### The issue
Executing the linq query throws an exception
```
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) 1
      FROM [Books] AS [b1]
      CROSS JOIN [Authors] AS [a1]
      CROSS JOIN [Readers] AS [r1]
fail: Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler[1]
      An exception occurred in the database while iterating the results of a query.
      System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
      Parameter name: index
         at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
         at System.SZArrayHelper.get_Item[T](Int32 index)
         at lambda_method(Closure , ValueBuffer )
         at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean queryStateManager, Boolean throwOnNullKey)
         at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.BufferedEntityShaper`1.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
         at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.QueryFlattener.CompositeShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
         at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.QueryFlattener.CompositeShaper`3.Shape(QueryContext queryContext, ValueBuffer valueBuffer)
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
         at lambda_method(Closure , QueryContext )
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_1`1.<CompileQuery>b__1(QueryContext qc)
```

The generated SQL  seems to be incorrect. If I change the query to 
```
				var book = (from b1 in c.Books
							from a1 in c.Authors
							from r1 in c.Readers
							select new { b1, a1 }).FirstOrDefault();
```
SQL becomes correct
```
info: Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommandBuilderFactory[1]
      Executed DbCommand (1ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT TOP(1) [b1].[Id], [b1].[Name], [a1].[Id], [a1].[Name]
      FROM [Books] AS [b1]
      CROSS JOIN [Authors] AS [a1]
      CROSS JOIN [Readers] AS [r1]
```
### Further technical details

EF Core version: 1.0.0
Operating system: Windows 10
Visual Studio version: VS 2015 Update 3

**Comment by smitpatel** [comment]
Generated SQL for first query is incorrect as there is no columns selected in projection when it should have columns for `b1`. Materializer throws exception due to that.

**Comment by MaximBalaganskiy** [comment]
@smitpatel there are no columns for `r1` in the second query, yet it succeeds

**Comment by smitpatel** [comment]
@MaximBalaganskiy - It is bug in stack. I wrote the notes for triage/assignee. To explain bit more, in the second query, the selector clause is `new { b1, a1 }` hence the SQL has columns from projected from `Books` and `Authors` table. But in the first query, even though selector clause is `new { b1 }` there are no columns in projection from `Books` which indeed is wrong query generated by EF core.

**Comment by MaximBalaganskiy** [comment]
@smitpatel I see. There is another exception possibly related to this one.
```
// considering we have another class
```
	public class Library
	{
		public int Id { get; set; }
		public string Name { get; set; }
	}
```
the query
```
				var book = (from b1 in c.Books
							from a1 in c.Authors
							from l1 in c.Libraries
							where b1.Reader.Name == a.Name && a1.Id == b1.AuthorId
							select new { b1, a1, l1 }).FirstOrDefault();
```
will throw an exception even before trying to execute the query
```
System.InvalidCastException: 
Unable to cast object of type 'System.Linq.Expressions.Expression`1[System.Func`3[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[ConsoleApp1.Book,System.Collections.Generic.IEnumerable`1[ConsoleApp1.Reader]],ConsoleApp1.Reader],ConsoleApp1.Author,Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[ConsoleApp1.Book,System.Collections.Generic.IEnumerable`1[ConsoleApp1.Reader]],ConsoleApp1.Reader],ConsoleApp1.Author]]]' to type 'System.Linq.Expressions.ConstantExpression'.
```
The causes are: multiple `from`, nullable navigation `Reader`, filtering by navigation property
