### ISSUE TITLE
Throw better exception when reading incorrect data for relational providers

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#6471]
### Steps to reproduce
Running the OptimisticConcurrencyTestBase tests with the SQLCE 1.1 alpha provider
### The issue
Instead of the expected InvalidOperationException, InvalidCastException is thrown (from the ADO.NET provider)

```
Test 'Microsoft.EntityFrameworkCore.Specification.Tests.FromSqlQuerySqlCeTest.Bad_data_error_handling_invalid_cast_key' failed:
	Assert.Throws() Failure
Expected: typeof(System.InvalidOperationException)
Actual:   typeof(System.InvalidCastException): Specified cast is not valid.
	at System.Data.SqlServerCe.SqlCeDataReader.GetInt32(Int32 ordinal)
	at lambda_method(Closure , DbDataReader )
	at Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
	at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
	at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
	at Microsoft.EntityFrameworkCore.Specification.Tests.FromSqlQueryTestBase`1.<>c__DisplayClass0_0.<Bad_data_error_handling_invalid_cast_key>b__0()
```

### Further technical details

EF Core version: 1.1.0-alpha1-21973
Operating system: Win 10
Visual Studio version: VS 2015 Update 3

**Comment by ajcvickers** [comment]
@ErikEJ I think this is fine. The point of this test was to throw with a better message for providers that grab the value from the data reader as an object. I believe that currently this is only SQL Server. Every other provider will throw when reading out of the data reader. This is why the test is skipped for SQLite.

**Comment by ajcvickers** [comment]
However, @divega or @anpete may want to comment. Maybe the intention was for this message to be used for all providers, but if so then it doesn't make sense that the test would be skipped for SQLite.

**Comment by ErikEJ** [comment]
@ajcvickers Thanks, yes, I saw the tests were disabled for sqlite, but I was also unsure abot the purpose of the introduced message - since it is in Relational, and not in the SQL Server provider

**Comment by divega** [comment]
AFAIR it is what @ajcvickers said. I guess could add a comment somewhere in these tests to clarify this intent to provider writers. 

Also I am thinking we could refactor the tests to allow provider writers to override the assertion and match whatever exception their providers would throw. At least that way provider writers would have a chance to asses if the exception customers would get would be clear, or if they want to do something specific in their providers to improve it. But I am not sure there is enough value in that.

**Comment by anpete** [comment]
Initial thought is that we should make the improved error handling work for these providers, too. I can't remember whether there was something fundamental blocking it, but it looks like we just need to gen the try/catch stuff in TypedRelationalValueBufferFactoryFactory. Re-opening.

**Comment by hkoestin** [comment]
Don't know if this is related to this issue, but I also have encountered the InvalidCastException on the SQL Server relational provider, which does not provide any additional information nor meaning. Just from the message, I can't figure out, which of the columns from the SQL cannot be handled correctly. 

A message would be good to show, which of the columns is actually causing the problem.

Here is the log output of the EF ILoggerProvider:
`7 Debug 2016-09-21 09:48:11.8136 EF-SQL An exception occurred in the database while iterating the results of a query.
System.InvalidCastException: Specified cast is not valid.
   at lambda_method(Closure , Object[] )
   at Microsoft.EntityFrameworkCore.Storage.Internal.UntypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() `

Screenshot from the VS debugger:
![image](https://cloud.githubusercontent.com/assets/13849875/18702343/9aebfa44-7fe1-11e6-979f-aa4e59fc5551.png)

**Comment by anpete** [comment]
@hkoestin Which version of EF Core?

**Comment by hkoestin** [comment]
Sorry for the late reply. It is core 1.0.1 with relational provider 1.0.1
(sql-server and sqlite)
