### ISSUE TITLE
Model Builder: Configuring one-to-one in OnModelCreating causes NullReferenceException

### ISSUE THREAD

**Issue by HappyNomad** [aspnet/EntityFramework#6957]
The issue can be reproduced with this version:

	"Microsoft.EntityFrameworkCore.SqlServer": "1.1.0-preview2-*",

and this context:

	public class BloggingContext : DbContext
	{
		public BloggingContext( DbContextOptions<BloggingContext> options )
			: base( options ) { }

		public DbSet<L> Ls { get; set; }
		public DbSet<AL> ZAs { get; set; }

		protected override void OnModelCreating( ModelBuilder modelBuilder )
		{
			modelBuilder.Entity( typeof( P ) );
			modelBuilder.Entity( typeof( T ) )
				.HasOne( typeof( P ) )
				.WithOne()
				.HasForeignKey<P>( "PreID" );
		}
	}

and this model:

	public class AL
	{
		public int ID { get; set; }
		public PBase L { get; set; }
	}

	public class L
	{
		public int ID { get; set; }
		public IList<T> Ts { get; set; }
	}

	public class T : P
	{
		public P Pre { get; set; }
	}

	public class P : PBase { }

	public abstract class PBase
	{
		public int ID { get; set; }
		public string Stuff { get; set; }
	}

The exception is:

System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
       at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.<>c__DisplayClass22_0.<CanSetRequiredOnProperties>b__2(Property property)
       at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
       at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.CanSetRequiredOnProperties(IReadOnlyList`1 properties, Nullable`1 isRequired, EntityType entityType, Nullable`1 configurationSource, Boolean shouldThrow)
       at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.CanSetForeignKey(IReadOnlyList`1 properties, EntityType dependentEntityType, Nullable`1 configurationSource, Boolean& resetIsRequired, Boolean& resetPrincipalKey, Boolean overrideSameSource)
       at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(IReadOnlyList`1 properties, EntityType dependentEntityType, Nullable`1 configurationSource, Boolean runConventions)
       at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalRelationshipBuilder.HasForeignKey(IReadOnlyList`1 propertyNames, EntityType dependentEntityType, ConfigurationSource configurationSource)
       at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.<>c__DisplayClass20_0.<HasForeignKeyBuilder>b__0(InternalRelationshipBuilder b, EntityType d)
       at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, Func`3 hasForeignKey)
       at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKeyBuilder(EntityType dependentEntityType, String dependentEntityTypeName, IReadOnlyList`1 foreignKeyPropertyNames)
       at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKey(Type dependentEntityType, String[] foreignKeyPropertyNames)
       at Microsoft.EntityFrameworkCore.Metadata.Builders.ReferenceReferenceBuilder.HasForeignKey[TDependentEntity](String[] foreignKeyPropertyNames)
       at EFGetStarted.AspNetCore.NewDb.Models.BloggingContext.OnModelCreating(ModelBuilder modelBuilder) in C:\Users\Adrian\Development\Examples\ASP.NET Core\EFGetStarted.AspNetCore.NewDb\src\EFGetStarted.AspNetCore.NewDb\Models\Model.cs:line 21
       at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext dbContext)
       at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
       at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass14_0.<GetModel>b__0(Object k)
       at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
       at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
       at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
       at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
       at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
       at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_6(IServiceProvider p)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
       at Microsoft.EntityFrameworkCore.Storage.DatabaseProviderServices.GetService[TService]()
       at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseProviderServices.get_RelationalDatabaseCreator()
       at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseProviderServices.get_Creator()
       at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServiceCollectionExtensions.<>c.<AddEntityFramework>b__0_13(IServiceProvider p)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactoryService(FactoryService factoryService, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(IServiceCallSite callSite, ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
       at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
       at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
       at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
       at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
       at EFGetStarted.AspNetCore.NewDb.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, BloggingContext dataContext) in C:\Users\Adrian\Development\Examples\ASP.NET Core\EFGetStarted.AspNetCore.NewDb\src\EFGetStarted.AspNetCore.NewDb\Startup.cs:line 55
  InnerException:

**Comment by AndriySvyryd** [comment]
Fixed in 47961c0
@HappyNomad Thanks for finding all these bugs!

**Comment by HappyNomad** [comment]
@AndriySvyryd I'm not finding the bugs.  The bugs are finding me. 🐜 😱 🐞
