### ISSUE TITLE
Exception with OfType(<Type>).Include(string) LINQ Query

### ISSUE THREAD

**Issue by caleblloyd** [aspnet/EntityFramework#6969]
### Steps to reproduce

Models are at: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Models/People.cs

DB Context: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/blob/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/AppDb.cs

You can run these tests against a MySql Database by cloning the Pomelo.EntityFrameworkCore.MySql repo and following these instructions: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/tree/master/test/Pomelo.EntityFrameworkCore.MySql.PerfTests

### The issue

The following query generates an exception:

```csharp
var teachers = await db.People.OfType<PersonTeacher>()
    .Include("Family.Members")
    .Include("Students.Family.Members")
    .ToListAsync();
// throws exception

Exception message: System.InvalidOperationException : The property 'Students' is not a navigation property of entity type 'Person'. The 'Include(string)' method can only be used with a '.' separated list of navigation property names.
Stack trace:
           at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.<IncludeNavigations>b__41_0(IncludeResultOperator includeResultOperator)
           at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
           at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
           at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
           at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__3.MoveNext()
           at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList()
           at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
           at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel)
           at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
           at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
           at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
           at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
           at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
           at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
        /home/caleb/Projects/caleb/Pomelo.EntityFrameworkCore.MySql/test/Pomelo.EntityFrameworkCore.MySql.PerfTests/Tests/Models/DiscriminatorTest.cs(96,0): at Pomelo.EntityFrameworkCore.MySql.PerfTests.Tests.Models.DiscriminatorTest.<TestDiscriminator>d__2.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

Adding an always true WHERE clause to the LINQ query makes it work fine though:

```csharp
var teachers = await db.People.OfType<PersonTeacher>()
    .Where(m => true)
    .Include("Family.Members")
    .Include("Students.Family.Members")
    .ToListAsync();
// this works fine
```

### Further technical details

EF Core version: 1.1.0-preview1
Operating system: Ubuntu 16.04

**Comment by maumar** [comment]
This has been fixed in 93ecfeca38c45cfc3081756e0a65920db19b42a0 which will be available in 1.2 release
