### ISSUE TITLE
EF Core 1.1 .ToString() translation causes exception

### ISSUE THREAD

**Issue by dotnetshadow** [aspnet/EntityFramework#7048]
### Steps to reproduce
Create a basic asp.net application for one of the controllers just insert the query code below with the model provided. As soon as the query is run the exception takes place

### The issue
The following query works in .net core **1.0.1** but doesn't work in **1.1**

**Model**
```
 public class Supplier
    {
        [Key]        
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [EmailAddress]        
        public string Email { get; set; }
        
    }
```

**Query**
```
var supplierList = _context.Suppliers.OrderBy(x => x.Name).Select(x => new SelectListItem
{
   Text = x.Name,
   Value = x.Id.ToString()
}).ToList();
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
NotSupportedException: TryExpression is not supported as a child expression when accessing a member on type 'System.Guid' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression.

System.NotSupportedException: TryExpression is not supported as a child expression when accessing a member on type 'System.Guid' because it is a value type. Construct the tree so the TryExpression is not nested inside of this expression.

   at System.Linq.Expressions.Compiler.StackSpiller.RequireNotRefInstance(Expression instance)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.MemberAssignmentRewriter..ctor(MemberAssignment binding, StackSpiller spiller, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.BindingRewriter.Create(MemberBinding binding, StackSpiller spiller, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberInitExpression(Expression expr, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)

   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)

   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)

   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)

   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)

   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)

   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)

   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)

   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()

   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)

   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)

   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)

   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()

   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at CarTracker.Controllers.AccountController.<Register>d__10.MoveNext() in D:\Programming\Projects\Personal\CarTracker\src\CarTracker\Controllers\AccountController.cs:line 122

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResourceFilter>d__22.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__20.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.VisualStudio.Web.BrowserLink.Runtime.BrowserLinkMiddleware.<ExecuteWithFilter>d__7.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.<Invoke>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.<Invoke>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

### Further technical details

EF Core version: 
Microsoft.EntityFrameworkCore.SqlServer": "1.1.0
Operating system: Windows 10 x64
Visual Studio version: VS 2015 Ultimate
SQL: LocalDb 2016

Other details about my project setup:
ASP.NET core 1.1 application

**Comment by anpete** [comment]
@dotnetshadow Thanks for reporting. I'm still investigating, but it looks like the following workaround might work:
```c#
var supplierList = _context.Suppliers.OrderBy(x => x.Name).Select(x => new SelectListItem
{
    Value = x.Id.ToString(), // flip the order of these properties
    Text = x.Name
}).ToList();
```
Can you confirm it this works?

**Comment by amirfahmideh** [comment]
I have a same issue when trying to get ToString() or GetHashCode() just after  updating to 1.1
```
 return result.Select(p => new SearchResultItem
            {
                Description = p.Description,
                Title = $"{p.Title} ({p.TitleEN})",
                Action = "Product",
                Controller = "Guide",
                SourceType = Models.Enums.SearchResultItemType.Product,
                RouteParameter = new Dictionary<string, string>(){
                    {"productID", p.ProductID.ToString()}},
                HashCode =  p.ProductID.GetHashCode()
            }).ToList<SearchResultItem>();
```

**Comment by anpete** [comment]
Possible issue in corefx ([#13864](https://github.com/dotnet/corefx/issues/13864))

**Comment by dotnetshadow** [comment]
@anpete I tried your suggestion but it didn't work

**Comment by blackbelt080** [comment]
I was looking at it and you need to pass the string as a literal or iNumerable perhaps.

**Comment by divega** [comment]
@anpete was the fix pushed to the 1.1.1 branch? should this be open waiting approval?

**Comment by anpete** [comment]
Yes, re-opened.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by divega** [comment]
@anpete closing again since this is approved and the fix is in. please reopen if necessary.

**Comment by smitpatel** [comment]
✅ Verified

**Comment by toddtsic** [comment]
I'm still getting error:

Critical part of linq query (T1Score is type: int?):

`strT1Score = (s.T1Score != null) ? s.T1Score.ToString() : "?"`

From project.json:

`"Microsoft.AspNetCore.Mvc.Core": "1.1.1",`

**Comment by SirwanAfifi** [comment]
I also get the same error:
```
public IList<SelectListDto> GetMatchSections(Guid matchId)
{
	return Items.Where(x => x.MatchId == matchId).Include(s => s.Section).Select(s => new SelectListDto
	{
		Text = s.Section.Name,
		Value = s.Section.Id.ToString(),
	}).ToList();
}
```

**Comment by smitpatel** [comment]
@toddtsic - You need EF packages to be 1.1.1. MVC patches have been bit ahead in versioning. EF patches are still not released on nuget. They will be there soon.

**Comment by Eilon** [comment]
Yup, within a week or two they'll be on NuGet.org.
