### ISSUE TITLE
Bizarre InvalidCastException error

### ISSUE THREAD

**Issue by jeffbromberger** [aspnet/EntityFramework#7070]
I'm doing a query with some Include directives to pull in related entities and then build a list of a different type of object:

 `
```
    // this is the object I'm trying to build a list of...
    public class AlertListDTO
    {
        public long Id { get; set; }
        public string Field1 { get; set; }
        public string Company { get; set; }
        public string Hostname { get; set; }
        public DateTime ReportedTime { get; set; }
    }
```
`

This is the query that causes the exception... 
        
```
`                var alertList = databaseStore.Alerts
                                .Include(a => a.Client)
                                .Include(a => a.Entity)
                                .Include(a => a.Company)
                                .AsNoTracking()
                                .Select(a => new AlertListDTO()
                                {
                                    Field1 = a.Entity.Field1,
                                    Company = a.Company.Name,
                                    Hostname = a.Client.Hostname,
                                }).ToList();
`

```
I have spent hours and hours trying to figure out what is wrong, as I am completely unable to decipher the exception stack shown below.  What I have found after a painful amount of trial and error, which makes no sense to me, is that if I change the lines:

```
                                    Field1 = a.Entity.Field1,
                                    Company = a.Company.Name,

```
to

```
                                    Company = a.Company.Name,
                                    Field1 = a.Entity.Field1,

```
then everything works!  To be clear, all I am doing is changing the order of those two lines, no changes to the lines themselves.  This goes against everything I think I know about C#, programming, and life in general lol.  There *has* to be something else going on here but I am completely unable to see it.

```
Exception message:
Stack trace:
{System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.Expression`1[System.Func`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[CloudApi.Models.Alert,System.Collections.Generic.IEnumerable`1[CloudApi.Models.Client]],CloudApi.Models.Client],System.Int64]]' to type 'System.Linq.Expressions.ConstantExpression'.
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.QueryFlattener.Flatten(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeJoinClause(JoinClause joinClause, QueryModel queryModel, Int32 index, Action baseVisitAction, MethodInfo operatorToFlatten, Boolean outerJoin)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitGroupJoinClause(GroupJoinClause groupJoinClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.Clauses.GroupJoinClause.Accept(IQueryModelVisitor visitor, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at CloudApi.Controllers.AlertsController.Index(Int32 version, String companyId) in AlertsController.cs:line 48}
```

### Further technical details

```
`{
    "dependencies": {
        "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
        "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
        "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",
        "Microsoft.Extensions.Configuration.Json": "1.0.0",
        "Microsoft.Extensions.Logging": "1.0.0",
        "Microsoft.Extensions.Logging.Console": "1.0.0",
        "Microsoft.Extensions.Logging.Debug": "1.0.0",
        "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
        "Microsoft.ApplicationInsights.AspNetCore": "1.0.2",
        "Microsoft.AspNetCore.Mvc": "1.0.1",
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
        "Microsoft.NETCore.App": "1.0.1",
        "Microsoft.EntityFrameworkCore": "1.0.1",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final",
        "Microsoft.AspNetCore.Diagnostics": "1.0.0",
        "System.IdentityModel.Tokens.Jwt": "5.0.1-pre-310121323",
        "Microsoft.AspNetCore.Authentication.JwtBearer": "1.0.0",
        "Microsoft.AspNetCore.Cors": "1.0.0",
        "Microsoft.Extensions.Caching.Memory": "1.0.0",
        "SapientGuardian.EntityFrameworkCore.MySql": "7.1.14",
        "AWSSDK.Core": "3.3.5",
        "AWSSDK.SimpleEmail": "3.3.1.1",
        "AWSSDK.CognitoIdentity": "3.3.0.3",
        "AWSSDK.CognitoIdentityProvider": "3.3.2",
        "AWSSDK.Extensions.NETCore.Setup": "3.3.0.1"
    },

    "tools": {
        "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
        "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
    },

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "dotnet5.6",
                "portable-net45+win8"
            ]
        }
    },

    "runtimes": {
        "win10-x64": { }
    },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

}
`

```
Visual Studio 2015 Pro Update 3
Windows 10 x64

All models and database context config can be found here:

https://dl.dropboxusercontent.com/u/32742882/cast-exception.zip

**Comment by maumar** [comment]
@jeffbromberger could you also share your model? Specifically code listing for all the entities and the contents of OnModelCreating method on the DbContext

**Comment by jeffbromberger** [comment]
@maumar  I have simplified the models as much as I could to still repro the issue.  I updated the first post with the new naming and also a link to a zip with the model files and the database config routine.

**Comment by jeffbromberger** [comment]
@rowanmiller  can I take it from the bug label that you were able to repro with my models or at least are not needing anything additional from me at this time?

**Comment by rowanmiller** [comment]
@jeffbromberger correct, we'll reach out if we need anything else.

**Comment by maumar** [comment]
@jeffbromberger try updating to the latest version of EF Core (1.1). The bug is fixed and we produce the following SQL:

```
SELECT [a].[Id], [a].[ClientId], [a].[CompanyId], [a].[CreatedTime], [a].[EntityId], [a].[RowVersion], [a.Client].[Id], [a.Client].[CompanyId], [a.Client].[CreatedTime], [a.Client].[Hostname], [a.Client].[RowVersion], [a.Entity].[Id], [a.Entity].[CreatedTime], [a.Entity].[Field1], [a.Entity].[RowVersion], [a.Entity].[UpdatedTime], [a.Company].[Name]
FROM [Alerts] AS [a]
LEFT JOIN [Clients] AS [a.Client] ON [a].[ClientId] = [a.Client].[Id]
INNER JOIN [Companies] AS [a.Company] ON [a].[CompanyId] = [a.Company].[Id]
LEFT JOIN [Entities] AS [a.Entity] ON [a].[EntityId] = [a.Entity].[Id]
ORDER BY [a].[ClientId], [a].[EntityId]
```
