### ISSUE TITLE
Evaluation warnings and invalid SQL generated (1.2.0-preview1)

### ISSUE THREAD

**Issue by kierenj** [aspnet/EntityFramework#7102]
### Steps to reproduce
Same model as #6937, #6938.  Using latest 1.2 preview (`1.2.0-preview1-22736`).

Query setup:

```c#
            var searchQuery = _context.Set<Widget>().AsQueryable().Where(b => !b.Retired.HasValue);
            searchQuery = searchQuery.Where(b => b.Type == null || !b.Type.Retired.HasValue);
```

**Note: this issue ONLY occurs when the second line is present, i.e. when performing filtering on the `Type` relationship.**

Calling `.Count()` or `.ToArray()` when debugging on this works fine, to get total results.

Then we add an `OrderBy`, `Skip` and `Take`:

```c#
searchQuery = searchQuery.OrderByDescending(b => b.Added).Skip(0).Take(5);
```

Again we can `.ToArray()` in the debugger to view results just fine.   But then we add the final projection:

```c#
            var projected = searchQuery.Select(b => new
            {
                w.Id,
                Manufacturer = w.ManufacturedIdentity.Manufacturer.Name,
                w.ManufacturedIdentity.BrandName,
                w.ManufacturedIdentity.RangeName,
                w.ManufacturedIdentity.ProductName,
                w.ManufacturedIdentity.ProductRef,
                Colours = w.Colours.Select(c => c.Colour).Where(c => !c.Retired.HasValue).Select(c => c.Name),
                Shape = w.Shape.Name,
                Texture = w.Texture.Name,
                Type = w.Type.Name,
                Source = w.Source.Name,
                ImageIds = w.Uses.SelectMany(u => u.ImageLinks).Where(l => !l.Image.Retired.HasValue).Select(l => l.ImageId)
            });
```

Now when we try to materialise the query, approx. 24 warnings about expressions which cannot be evaluated.  Full text in a gist here: https://gist.github.com/kierenj/06c6b4d5502161c13fb9223e4919ccfe .

Bit of a pain, but still, workable, so long as the next bit works.  Unfortunately not:

### The issue

1. Warnings about evaluation, as in gist above
2. Exceptions for each follow-up query:

```
info: Microsoft.EntityFrameworkCore.Storage.IRelationalCommandBuilderFactory[1]
      Executed DbCommand (32ms) [Parameters=[@__p_0='?', @__p_1='?'], CommandType='Text', CommandTimeout='30']
      SELECT [t].[Id], [t].[Added], [t].[ListOrder], [t].[Modified], [t].[Name], [t].[Retired], [t].[SourceId], [t].[TypeId], [t].[TextureId], [t].[ShapeId]
      FROM (
          SELECT [b.Type1].[Id], [b.Type1].[Added], [b.Type1].[ListOrder], [b.Type1].[Modified], [b.Type1].[Name], [b.Type1].[Retired]
          FROM [Widget] AS [b0]
          LEFT JOIN [WidgetType] AS [b.Type1] ON [b0].[TypeId] = [b.Type1].[Id]
          WHERE [b0].[Retired] IS NULL AND ([b0].[TypeId] IS NULL OR [b.Type1].[Retired] IS NULL)
          ORDER BY [b0].[Added] DESC, [b0].[TypeId]
          OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
      ) AS [t]
      ORDER BY [t].[Added] DESC, [t].[TypeId]
fail: Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory[1]
      An exception occurred in the database while iterating the results of a query.
      System.Data.SqlClient.SqlException: Invalid column name 'SourceId'.
      Invalid column name 'TypeId'.
      Invalid column name 'TextureId'.
      Invalid column name 'ShapeId'.
      Invalid column name 'TypeId'.
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at System.Data.SqlClient.SqlDataReader.get_MetaData()
         at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
         at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
         at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
         at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
         at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
         at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_GroupJoin>d__26`4.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
         at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
         at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
         at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
         at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
         at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
         at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
         at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
         at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
         at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
         at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
         at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
         at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
      ClientConnectionId:dd1b2a2f-4da4-4f48-8ac7-940d8d3f859b
      Error Number:207,State:1,Class:16
System.Data.SqlClient.SqlException: Invalid column name 'SourceId'.
Invalid column name 'TypeId'.
Invalid column name 'TextureId'.
Invalid column name 'ShapeId'.
Invalid column name 'TypeId'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_GroupJoin>d__26`4.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
   at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
   at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
   at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
   at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
   at System.Linq.Enumerable.<GroupJoinIterator>d__73`4.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__165`3.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
ClientConnectionId:dd1b2a2f-4da4-4f48-8ac7-940d8d3f859b
Error Number:207,State:1,Class:16
```

### Further technical details

EF Core version: `1.2.0-preview1-22736`
Operating system: Win10
Visual Studio version: VS2015 / n/a (commandline too)

Other details about my project setup:

**Comment by maumar** [comment]
This works in the current bits. Now we produce the following sql:

```sql
SELECT TOP(@__p_1) [i].[Id]
FROM [WidgetImages] AS [i]
WHERE EXISTS (
    SELECT 1
    FROM [ImageWidgetUsageLinks] AS [b]
    INNER JOIN [WidgetUsages] AS [b.WidgetUsage] ON [b].[WidgetUsageId] = [b.WidgetUsage].[Id]
    INNER JOIN [Widgets] AS [b.WidgetUsage.Widget] ON [b.WidgetUsage].[WidgetId] = [b.WidgetUsage.Widget].[Id]
    LEFT JOIN [WidgetTextures] AS [b.WidgetUsage.Widget.Texture] ON [b.WidgetUsage.Widget].[TextureId] = [b.WidgetUsage.Widget.Texture].[Id]
    WHERE ([i].[Id] = [b].[ImageId]) AND [b.WidgetUsage.Widget.Texture].[Id] NOT IN (...))
```

**Comment by maumar** [comment]
This works in current bits. We produce the following queries:

main:
```sql
SELECT [b].[Id], [b.ManufacturedIdentity.Manufacturer].[Name], [b.ManufacturedIdentity].[BrandName], [b.ManufacturedIdentity].[RangeName], [b.ManufacturedIdentity].[ProductName], [b.ManufacturedIdentity].[ProductRef], [b.Shape].[Name], [b.Texture].[Name], [b.Type].[Name], [b.Source].[Name]
FROM [Widgets] AS [b]
LEFT JOIN [Source] AS [b.Source] ON [b].[SourceId] = [b.Source].[Id]
LEFT JOIN [WidgetTextures] AS [b.Texture] ON [b].[TextureId] = [b.Texture].[Id]
LEFT JOIN [Shape] AS [b.Shape] ON [b].[ShapeId] = [b.Shape].[Id]
LEFT JOIN [ManufacturedIdentity] AS [b.ManufacturedIdentity] ON [b].[ManufacturedIdentityId] = [b.ManufacturedIdentity].[Id]
LEFT JOIN [Manufacturer] AS [b.ManufacturedIdentity.Manufacturer] ON [b.ManufacturedIdentity].[ManufacturerId] = [b.ManufacturedIdentity.Manufacturer].[Id]
LEFT JOIN [WidgetTypes] AS [b.Type] ON [b].[TypeId] = [b.Type].[Id]
WHERE [b].[Retired] IS NULL AND ([b].[TypeId] IS NULL OR [b.Type].[Retired] IS NULL)
ORDER BY [b].[Added] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```

N+1 query for colors:

```sql
                    SELECT [c.Colour].[Name]
                    FROM [WidgetColours] AS [c]
                    INNER JOIN [Colour] AS [c.Colour] ON [c].[ColourId] = [c.Colour].[Id]
                    WHERE [c.Colour].[Retired] IS NULL AND (@_outer_Id = [c].[WidgetId])
```

N+1 query for ImageIds:

```sql
                    SELECT [u.ImageLinks].[ImageId]
                    FROM [WidgetUsages] AS [u]
                    INNER JOIN [ImageWidgetUsageLinks] AS [u.ImageLinks] ON [u].[Id] = [u.ImageLinks].[WidgetUsageId]
                    INNER JOIN [WidgetImages] AS [u.ImageLinks.Image] ON [u.ImageLinks].[ImageId] = [u.ImageLinks.Image].[Id]
                    WHERE [u.ImageLinks.Image].[Retired] IS NULL AND (@_outer_Id1 = [u].[WidgetId])
```

**Comment by maumar** [comment]
The models in those other bugs were incomplete. I tried to fill in the blanks, so the model may not be exactly correct. Used the following:

```cs
    public class MyContext : DbContext
    {
        public DbSet<WidgetType> WidgetTypes { get; set; }
        public DbSet<WidgetImage> WidgetImages { get; set; }
        public DbSet<ImageWidgetUsageLink> ImageWidgetUsageLinks { get; set; }
        public DbSet<WidgetUsage> WidgetUsages { get; set; }
        public DbSet<Widget> Widgets { get; set; }
        public DbSet<WidgetTexture> WidgetTextures { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=.;Database=Repro7102;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ImageWidgetUsageLink>().HasKey(l => new { l.ImageId, l.WidgetUsageId });
            modelBuilder.Entity<ImageWidgetUsageLink>().HasOne(l => l.Image).WithMany(i => i.UsedWidgets).IsRequired(true).HasForeignKey(l => l.ImageId);
            modelBuilder.Entity<ImageWidgetUsageLink>().HasOne(l => l.WidgetUsage).WithMany(u => u.ImageLinks).IsRequired(true).HasForeignKey(l => l.WidgetUsageId);

            modelBuilder.Entity<WidgetUsage>().HasOne(u => u.Widget).WithMany(b => b.Uses).IsRequired(true);
            modelBuilder.Entity<Widget>().HasOne(b => b.Texture).WithMany(c => c.Widgets).IsRequired(false);

            modelBuilder.Entity<WidgetColours>().HasKey(k => new {k.WidgetId, k.ColourId});
            modelBuilder.Entity<WidgetColours>().HasOne(l => l.Colour).WithMany(i => i.Widgets).IsRequired(true).HasForeignKey(l => l.ColourId);
            modelBuilder.Entity<WidgetColours>().HasOne(l => l.Widget).WithMany(u => u.Colours).IsRequired(true).HasForeignKey(l => l.WidgetId);
        }
    }

    public class WidgetImage
    {
        public Guid Id { get; set; }

        public bool? Retired { get; set; }

        public List<ImageWidgetUsageLink> UsedWidgets { get; set; }
    }

    public class ImageWidgetUsageLink
    {
        public Guid ImageId { get; set; }
        public WidgetImage Image { get; set; }
        public Guid WidgetUsageId { get; set; }
        public WidgetUsage WidgetUsage { get; set; }
    }

    public class WidgetUsage
    {
        public Guid Id { get; set; }
        public Widget Widget { get; set; }
        public List<ImageWidgetUsageLink> ImageLinks { get; set; }
    }

    public class Widget
    {
        public Guid Id { get; set; }
        public WidgetTexture Texture { get; set; }
        public List<WidgetUsage> Uses { get; set; }

        public WidgetType Type { get; set; }

        public DateTime Added { get; set; }

        public bool? Retired { get; set; }

        public Source Source { get; set; }
        public Shape Shape { get; set; }

        public List<WidgetColours> Colours { get; set; }

        public ManufacturedIdentity ManufacturedIdentity { get; set; }
    }

    public class WidgetTexture
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public List<Widget> Widgets { get; set; }
    }

    public class WidgetType
    {
        public Guid Id { get; set; }
        public bool? Retired { get; set; }
        public string Name { get; set; }
    }

    public class ManufacturedIdentity
    {
        public Guid Id { get; set; }
        public Manufacturer Manufacturer { get; set; }

        public string BrandName { get; set; }
        public string RangeName { get; set; }
        public string ProductName { get; set; }
        public string ProductRef { get; set; }
    }

    public class Manufacturer
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

    public class Source
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

    public class Shape
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
    }

    public class WidgetColours
    {
        public Guid WidgetId { get; set; }
        public Guid ColourId { get; set; }
        public Widget Widget { get; set; }
        public Colour Colour { get; set; }
    }

    public class Colour
    {
        public Guid Id { get; set; }
        public string Name { get; set; }

        public bool? Retired { get; set; }

        public List<WidgetColours> Widgets { get; set; }
    }
```
