### ISSUE TITLE
"dotnet ef dbcontext list --json" throws error: Input string was not in a correct format.

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/EntityFramework#7273]
When I execute 
dotnet ef dbcontext list it returns the list of db contexts.

but when I execute 
dotnet ef dbcontext list --json, I get this error
Input string was not in a correct format.

### Steps to reproduce
Repro:
C:\Users\vramak\Documents\Visual Studio 2017\Projects\WebApplication65\src\WebApplication65>dotnet ef dbcontext list --j
son
Input string was not in a correct format.

### Further technical details
```EF Core version: (found in project.json or packages.config)
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.0.0-msbuild2-final" />
```
Database Provider: (e.g. Microsoft.EntityFrameworkCore.SqlServer)
Operating system: 
IDE: VS 2017 
dotnet version
1.0.0-preview5-004275

**Comment by bricelam** [comment]
Use the builds from the [feature-work](https://dotnet.myget.org/gallery/aspnetcore-feature-work) feed. These are from the `feature/msbuild` branch and contain the latest MSBuild-enabled bits.

**Comment by vijayrkn** [comment]
Updated to the above feed. Still get the same error. Error details:

![image](https://cloud.githubusercontent.com/assets/3981619/21336880/551a1910-c61d-11e6-8c00-c76fde768469.png)


C:\Users\vramak\Documents\Visual Studio 2017\Projects\WebApplication65\src\WebApplication65>dotnet ef dbcontext list --j
son
```[
System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.AnsiTextWriter.WriteLine(String format, Object[] args)
   at Microsoft.EntityFrameworkCore.Tools.Reporter.WriteLine(String value)
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextListCommand.ReportJsonResults(IReadOnlyList`1 contextTypes)
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextListCommand.Execute()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)
Input string was not in a correct format.
```

**Comment by bricelam** [comment]
Fixed in  aspnet/EntityFramework.Tools@0852cfd0218051eeb420de322e76fd022c02b864
