### ISSUE TITLE
Upcast-Concat throws ArgumentException

### ISSUE THREAD

**Issue by azabluda** [aspnet/EntityFramework#7280]
`Concat` of two upcasted collections fails with `ArgumentException`.

```
Exception message:
System.ArgumentException
Expression of type 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Storage.ValueBuffer]' cannot be used for parameter of type 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Inheritance.Kiwi]' of method 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Inheritance.Kiwi] Concat[Kiwi](System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Inheritance.Kiwi], System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Specification.Tests.TestModels.Inheritance.Kiwi])'

Stack trace:
   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0, Expression arg1)
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleSetOperation(EntityQueryModelVisitor entityQueryModelVisitor, Expression secondSource, MethodInfo setMethodInfo) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 331
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleConcat(EntityQueryModelVisitor entityQueryModelVisitor, ConcatResultOperator concatResultOperator) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 133
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.<>c.<.cctor>b__30_4(EntityQueryModelVisitor v, ResultOperatorBase r, QueryModel __) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 33
   at Microsoft.EntityFrameworkCore.Query.ResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\ResultOperatorHandler.cs:line 78
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandlerContext.EvalOnClient(Boolean requiresClientResultOperator) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs:line 71
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalResultOperatorHandler.HandleResultOperator(EntityQueryModelVisitor entityQueryModelVisitor, ResultOperatorBase resultOperator, QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\Internal\RelationalResultOperatorHandler.cs:line 168
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 1077
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitResultOperator(ResultOperatorBase resultOperator, QueryModel queryModel, Int32 index) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs:line 1187
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 721
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Relational\Query\RelationalQueryModelVisitor.cs:line 373
   at Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryModelVisitor.VisitQueryModel(QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.SqlServer\Query\Internal\SqlServerQueryModelVisitor.cs:line 92
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\EntityQueryModelVisitor.cs:line 259
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Storage\Database.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 218
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0() in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 171
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\CompiledQueryCache.cs:line 68
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\CompiledQueryCache.cs:line 45
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 169
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs:line 99
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\EntityQueryProvider.cs:line 57
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Specification.Tests.InheritanceTestBase`1.Can_concat_kiwis_and_eagles_as_birds() in D:\EntityFramework\src\Microsoft.EntityFrameworkCore.Specification.Tests\InheritanceTestBase.cs:line 282
```

### Steps to reproduce
Add the following test to `Microsoft.EntityFrameworkCore.Specification.Tests.InheritanceTestBase<TFixture>` and run it against SqlServer or InMemory database

```c#
        [Fact]
        public virtual void Can_concat_kiwis_and_eagles_as_birds()
        {
            using (var context = CreateContext())
            {
                var kiwis = context.Set<Kiwi>()
                    .Where(x => true); // dummy Where condition, see https://github.com/aspnet/EntityFramework/issues/7279

                var eagles = context.Set<Eagle>()
                    .Where(x => true); // dummy Where condition, see https://github.com/aspnet/EntityFramework/issues/7279

                var concat = kiwis.Cast<Bird>().Concat(eagles).ToList(); // <<< ArgumentException

                Assert.Equal(2, concat.Count);
            }
        }
```
Note that `.Where(x => true)` clauses are only necessary because of #7279.

### Further technical details
EF Core version: 1.1.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer, Microsoft.EntityFrameworkCore.InMemory
Operating system: Windows 7 Professional SP1
IDE: Visual Studio 2015

**Comment by Wombatush** [comment]
I observing the same issue with .Union(...)
