### ISSUE TITLE
ef.exe scaffold with simple assembly name throws with path not legal

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFramework#7400]
Run:

> ef.x86.exe dbcontext scaffold "Data Source=mydb.db" Microsoft.EntityFrameworkCore.Sqlite --assembly EFTest.exe

Gives:

> System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at Microsoft.EntityFrameworkCore.Tools.OperationExecutorBase..ctor(String assembly, String startupAssembly, String projectDir, String contentRootPath, String dataDirectory, String rootNamespace, String environment)
   at Microsoft.EntityFrameworkCore.Tools.AppDomainOperationExecutor..ctor(String assembly, String startupAssembly, String projectDir, String contentRootPath, String dataDirectory, String rootNamespace, String environment)
   at Microsoft.EntityFrameworkCore.Tools.Commands.ProjectCommandBase.CreateExecutor()
   at Microsoft.EntityFrameworkCore.Tools.Commands.DbContextScaffoldCommand.Execute()
   at Microsoft.EntityFrameworkCore.Tools.Commands.CommandBase.<>c__DisplayClass0_0.<Configure>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.EntityFrameworkCore.Tools.Program.Main(String[] args)

Assembly EFTest is in the local directory. Running this gets past the error:

> ef.x86.exe dbcontext scaffold "Data Source=mydb.db" Microsoft.EntityFrameworkCore.Sqlite --assembly .\EFTest.exe

**Comment by bricelam** [comment]
I wonder if we should also allow just `EFTest`.
