### ISSUE TITLE
Query : invalid cast for queries with nullable bool and coalesce

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#7452]
```
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var p1 = new Person { Name = "Eo", IsGold = false };
                var p2 = new Person { Name = "Virginia", IsGold = true };
                var p3 = new Person { Name = "Darrow", IsGold = null };

                ctx.People.AddRange(p1, p2, p3);
                ctx.SaveChanges();
            }

            using (var ctx = new MyContext())
            {
                ctx.People.Select(p => p.IsGold ?? false).ToList();
            }
        }
    }


    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Repro7452;Integrated Security=SSPI;");
        }
    }

    public class Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public bool? IsGold { get; set; }
    }
```

exception:

System.InvalidCastException: Specified cast is not valid.
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in D:\git\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\LinqOperatorProvider.cs:line 145

We generate the following query plan:

```
TRACKED: False
(QueryContext queryContext) => IEnumerable<bool> _Select(
    source: IEnumerable<ValueBuffer> _ShapedQuery(
        queryContext: queryContext, 
        shaperCommandContext: SelectExpression: 
            SELECT COALESCE([p].[IsGold], 0) AS [Coalesce]
            FROM [People] AS [p]
        , 
        shaper: ValueBufferShaper
    )
    , 
    selector: (ValueBuffer p) => (bool) object p.get_Item(0)
)
```

Problem is that COALESCE([p].[IsGold], 0) comes back as int and we are expecting bool - we should probably compensate in SQL

```sql
SELECT SQL_VARIANT_PROPERTY(IsGold, 'BaseType') FROM People   -- comes back as bit
SELECT SQL_VARIANT_PROPERTY(COALESCE (IsGold, 0), 'BaseType') FROM People -- comes back as int
```

**Comment by maumar** [comment]
fixed in bc1cf84ece5d98d97b4caa8392c47ef4c21104f9
