### ISSUE TITLE
ModelBuilding: Non-primitive properties cannot be configured to use supported store type

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#7488]
```c#
public class Blog
{
    public int Id { get; set; }

    public BigInteger Big { get; set; }
}
```
Using SqlServer, of course above doesn't work out of the box. It throws following exception.
```
Unhandled Exception: System.InvalidOperationException: The property 'Blog.Big' is of type 'BigInteger' which is not supported by current database provider. Either change the property CLR type or manually configure the database type for it.
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyMappingValidationConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCallSite.Invoke(ServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.get_DatabaseCreator()
   at Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureDeleted()
   at EFSampleApp.Program.Main(String[] args)
```
As the exception message said to configure database type manually, following code added to `OnModelCreating`
`modelBuilder.Entity<Blog>().Property(e => e.Big).HasColumnType("bigint");`

It still throws the same exception. Either exception message is incorrect or there is bug in validation.EF Core version: 1.0.1 & 1.1.0 both shows the same error
Database Provider: SqlServer/Sqlite
Operating system: Win10
IDE: VS2015

**Comment by ajcvickers** [comment]
@smitpatel The message is misleading. There is no way to map a CLR type that is not supported by the database provider just by changing the store type that is used.
