### ISSUE TITLE
Tools: Finding runtime 1.2 compatible tools?

### ISSUE THREAD

**Issue by ErikEJ** [aspnet/EntityFramework#7492]
When installing the EF PMC tools, I am unable to find a Tools Nuget package that works with 1.2-preview.

I was expecting 1.2 compatible tools to be available on the aspnetcore-dev feed...

Get this error:

PM>  Add-Migration MyFirstMigration 
System.TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String builderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
**Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=1.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.**

### Steps to reproduce
Following the instructions here: https://github.com/ErikEJ/EntityFramework.SqlServerCompact/wiki/Using-EF-Core-with-SQL-Server-Compact-in-Traditional-.NET-Applications-(daily-builds) 

### Further technical details
EF Core version: 1.2.0-preview1-23167
Database Provider: SqlServerCompact4
Operating system: Win 10
IDE: Visual Studio 2015 Update 3

**Comment by ErikEJ** [comment]
Fixed by running this before installing the Tools package: 

  Install-Package Microsoft.EntityFrameworkCore.Design -Pre

**Comment by bricelam** [comment]
Yep. We need to update the  NuGet package dependency to 1.2.0. It is currently hard coded to 1.1.0 because of the custom way we have to pack.

**Comment by ErikEJ** [comment]
Too bad... But thanks!

**Comment by bricelam** [comment]
Fixed in aspnet/EntityFramework.Tools#54
