### ISSUE TITLE
Where() on derived property fails with undefined property on base class exception

### ISSUE THREAD

**Issue by rmja** [aspnet/EntityFramework#7499]
Consider the following model:
```
public class Message
{
        public int Id { get; private set; }

        public MessageSender Sender { get; private set; }

        public ICollection<MessageRecipient> Recipients { get; private set; }
}
```
`MessageSender` and `MessageRecipient` are abstract classes that have different implementation depending on their kind.

To get the "inbox" I can issue the following query:
```
db.Messages.Where(message =>
                message.Recipients.OfType<UserMessageRecipient>().Any(x => x.UserId == userId) ||
                message.Recipients.OfType<EmailMessageRecipient>().Any(x => x.Email == email))
```

However, to get the "outbox" where the query is run on the Sender property, I cannot 
```
db.Messages.Where(message =>
                (message.Sender is UserMessageSender && ((UserMessageSender)message.Sender).UserId == userId) ||
                (message.Sender is EmailMessageSender && ((EmailMessageSender )message.Sender).Email == email))
```

The following exception is thrown:
```
Exception thrown: 'System.ArgumentException' in mscorlib.dll

Additional information: Property 'System.String UserId' is not defined for type 'Messaging.Models.MessageSender'

   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass20_0.<VisitMember>b__2(Expression e)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.RewriteNavigationsIntoJoins(QuerySourceReferenceExpression outerQuerySourceReferenceExpression, IEnumerable`1 navigations, Type propertyType, Func`2 propertyCreator, Func`2 conditionalAccessPropertyCreator)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.<>c__DisplayClass20_0.<VisitMember>b__0(IEnumerable`1 ps, IQuerySource qs)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindPropertyExpressionCore[TResult](Expression propertyExpression, IQuerySource querySource, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.BindNavigationPathPropertyExpression[TResult](Expression propertyExpression, Func`3 propertyBinder)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitMember(MemberExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitBinary(BinaryExpression node)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.VisitConditional(ConditionalExpression node)
   at Remotion.Linq.Clauses.WhereClause.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.NavigationRewritingQueryModelVisitor.VisitWhereClause(WhereClause whereClause, QueryModel queryModel, Int32 index)
   at Remotion.Linq.QueryModelVisitorBase.VisitBodyClauses(ObservableCollection`1 bodyClauses, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.NavigationRewritingExpressionVisitor.Rewrite(QueryModel queryModel, QueryModel parentQueryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.System.Collections.Generic.IAsyncEnumerable<TResult>.GetEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__129`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__130`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

```

### Further technical details
EF Core version: 1.1.0
Database Provider: SqlServer
Operating system: Windows 10
IDE: Visual Studio 2015

**Comment by smitpatel** [comment]
Navigation rewrite ignores the conversion applied onto navigation. Sample test is in https://github.com/aspnet/EntityFramework/tree/propertyonderivedtype7499

Passing to @maumar

**Comment by maumar** [comment]
working on a fix now

**Comment by maumar** [comment]
fixed in c6a0602deb525e85e91ce069066b165ff57fe8fe

**Comment by smitpatel** [comment]
@maumar - Please file a bug for clean up too.

**Comment by SebaVDPInfra** [comment]
We found a workaround for this issue.
We used "as" instead of casting and it worked fine.

`
b.Messages.Where(message =>
                (message.Sender is UserMessageSender && (message.Sender as UserMessageSender).UserId == userId) ||
                (message.Sender is EmailMessageSender && (message.Sender as EmailMessageSender).Email == email))`
