### ISSUE TITLE
Test: Concurrency issue in Can_use_self_referencing_overlapping_FK_PK

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#7531]
Disabled test Can_use_self_referencing_overlapping_FK_PK
stacktrace
```
xUnit.net .NET CLI test runner (64-bit Desktop .NET win10-x64)
  Discovering: Microsoft.EntityFrameworkCore.Tests
  Discovered:  Microsoft.EntityFrameworkCore.Tests
  Starting:    Microsoft.EntityFrameworkCore.Tests
    Microsoft.EntityFrameworkCore.Tests.ModelBuilderGenericRelationshipTypeTest+GenericOneToOneType.Can_use_self_referencing_overlapping_FK_PK [FAIL]
      System.InvalidOperationException : Sequence contains no elements
      Stack Trace:
           at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
           at lambda_method(Closure , QueryContext )
        D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs(149,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc)
        D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\QueryCompiler.cs(102,0): at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
        D:\EntityFramework\src\Microsoft.EntityFrameworkCore\Query\Internal\EntityQueryProvider.cs(57,0): at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
        ModelBuilderTest\OneToOneTestBase.cs(3680,0): at Microsoft.EntityFrameworkCore.Tests.ModelBuilderTest.OneToOneTestBase.Can_use_self_referencing_overlapping_FK_PK()
  Finished:    Microsoft.EntityFrameworkCore.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.EntityFrameworkCore.Tests  Total: 4475, Errors: 0, Failed: 1, Skipped: 0, Time: 45.886s
SUMMARY: Total: 2 targets, Passed: 1, Failed: 1.
```

**Comment by divega** [comment]
Similar stack trace coming from:

`ChangeTrackerTest.Shadow_properties_are_not_included_in_update_unless_value_explicitly_set`
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_0`1.<CompileQueryCore>b__0(QueryContext qc) in /Users/asplab/Documents/buildAgent/work/2b0c8ce712895332/EntityFramework/src/Microsoft.EntityFrameworkCore/Query/Internal/QueryCompiler.cs:line 149
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source, Expression`1 predicate)
   at Microsoft.EntityFrameworkCore.Tests.ChangeTracking.ChangeTrackerTest.AssertValuesSaved(Int32 id, Int32 someInt, String someString)
   at Microsoft.EntityFrameworkCore.Tests.ChangeTracking.ChangeTrackerTest.Shadow_properties_are_not_included_in_update_unless_value_explicitly_set() in /Users/asplab/Documents/buildAgent/work/2b0c8ce712895332/EntityFramework/test/Microsoft.EntityFrameworkCore.Tests/ChangeTracking/ChangeTrackerTest.cs:line 972

**Comment by smitpatel** [comment]
Offensive commit is probably 1402bf6e6c5ade887bd45b55c57bf330d495f14f
I ran EFCore.Tests in loop of 20. A commit before that it all passes. With above commit included, the test fails at least once in iteration.
