### ISSUE TITLE
ExecutionStrategyExtensions.ExecuteInTransactionAsync null reference exception

### ISSUE THREAD

**Issue by clement911** [aspnet/EntityFramework#7795]
My app seems to have experienced some weird transient issue while trying to save changes to sql azure. This error occurred multiple times in a brief amount of time (a few seconds).
Usually it all works fine.

A couple minutes later it was followed a by a bunch of "DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s)", which don't make sense because I know it was an simple 1 row insert.

Could it be cause by a transient reconfiguration within sql azure?
If so, I would expect a more meaningful error message...

```
Failed to process webhook: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__13`2.<<ExecuteInTransactionAsync>b__13_1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__33`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__33`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<ExecuteImplementationAsync>d__33`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Wish.Core.XDbContext.<SaveChangesAsync>d__14.MoveNext() in C:\Dev\BetterReports\Wish.Core\Persistence\XDbContext.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NitroCharts.Web2.DataManager.<TryProcessWebHookNotificationsAsync>d__13.MoveNext() in C:\Dev\BetterReports\NitroCharts.Web2\_misc\DataCollection\Common\DataManager.cs:line 99
```

EF Core version: 1.1.0 
Database Provider: Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows (Azure app service)
IDE: VS 2015

**Comment by clement911** [comment]
I'm aware of the single thread limitation of DbContext. I definitely don't use the same instance in parallel. Or at least not intentionally.
Unfortunately I'm not able to reproduce and I've seen that happen only once (well mulitple times during a short period of time)

**Comment by clement911** [comment]
It hasn't happened since so feel free to close, but it may a bug that just rarely happens...

**Comment by ajcvickers** [comment]
@AndriySvyryd Can you take a quick look at the code and check for anything obvious that would cause a null ref exception? If you can't find anything, then probably close as no-repro unless you want to investigate more.

**Comment by AndriySvyryd** [comment]
I didn't see anything in our code that could cause the exception, however I did notice that the `IExecutionStrategy` extension methods don't have checks for null parameters, so I'll keep this open to fix this.

**Comment by clement911** [comment]
FYI this happened again yesterday. Again it looks like it may have been some sort of transient weird state over a couple of minutes. In the same period I see concurrency exceptions and other exceptions like the following:

```
Error from Microsoft.EntityFrameworkCore.Query.Internal.SqlServerQueryCompilationContextFactory: An exception occurred in the database while iterating the results of a query. System.InvalidOperationException: Invalid operation. The connection is closed.

at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
at System.Data.SqlClient.TdsParserStateObject.TryPeekByte(Byte& value)
at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
at System.Data.SqlClient.SqlDataReader.get_MetaData()
at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

**Comment by AndriySvyryd** [comment]
@clement911 Are you sharing the same connection between multiple instances of DbContext?

**Comment by clement911** [comment]
No I don't pass in the connection, so it should be owned/handled by DbContext directly if I understand correctly...

**Comment by AndriySvyryd** [comment]
@clement911 That's correct. The exceptions you shared usually indicate that a DbContext instance is being used concurrently from multiple threads. Double-check whether this might be the case.
