### ISSUE TITLE
build and unit test running issue

### ISSUE THREAD

**Issue by pmiddleton** [aspnet/EntityFramework#7993]
I just started running into problems yesterday when I pulled the latest code from dev.  I am running into the following errors.  I have tried re-cloning the repo, and I have also tried setting up a clean VM - neither solved the issues.

Is anyone else seeing these?

When I try to build from the command line I am getting this error.  

	[xUnit.net 00:00:45.0037271]   Finished:    Microsoft.EntityFrameworkCore.Benchmarks.EF6
	Failed   CreateAndDisposeUnusedContext(collector: NullMetricCollector { MemoryDelta = 0, TimeElapsed = 0 }, cold: True, count: 1)
	Error Message:
	 System.TypeInitializationException : The type initializer for 'Microsoft.EntityFrameworkCore.Benchmarks.Models.AdventureWorks.TestHelpers.AdventureWorksFixtureBase' threw an exception.
	---- System.IO.FileLoadException : Could not load file or assembly 'System.IO.FileSystem, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	Stack Trace:

	Server stack trace:
	   at Microsoft.EntityFrameworkCore.Benchmarks.Models.AdventureWorks.TestHelpers.AdventureWorksFixtureBase.get_ConnectionString()
	   at Microsoft.EntityFrameworkCore.Benchmarks.EF6.Models.AdventureWorks.AdventureWorksFixture.CreateContext() in C:\code\github\wtf\EntityFramework\test\EFCore.Benchmarks.EF6\Models\AdventureWorks\AdventureWorksFixture.cs:line 12
	   at Microsoft.EntityFrameworkCore.Benchmarks.EF6.InitializationTests.ColdStartEnabledTests.CreateAndDisposeUnusedContext(IMetricCollector collector, Int32 count) in C:\code\github\wtf\EntityFramework\test\EFCore.Benchmarks.EF6\InitializationTests.cs:line 81
	   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
	   at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)

	Exception rethrown at [0]:
	   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
	   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
	   at Microsoft.EntityFrameworkCore.Benchmarks.EF6.InitializationTests.ColdStartEnabledTests.CreateAndDisposeUnusedContext(IMetricCollector collector, Int32 count)
	   at Microsoft.EntityFrameworkCore.Benchmarks.EF6.InitializationTests.<>c__DisplayClass0_0.<CreateAndDisposeUnusedContext>b__0(ColdStartEnabledTests c) in C:\code\github\wtf\EntityFramework\test\EFCore.Benchmarks.EF6\InitializationTests.cs:line 22
	   at Microsoft.EntityFrameworkCore.Benchmarks.EF6.InitializationTests.RunColdStartEnabledTest(Boolean cold, Action`1 test) in C:\code\github\wtf\EntityFramework\test\EFCore.Benchmarks.EF6\InitializationTests.cs:line 64
	   at Microsoft.EntityFrameworkCore.Benchmarks.EF6.InitializationTests.CreateAndDisposeUnusedContext(IMetricCollector collector, Boolean cold, Int32 count) in C:\code\github\wtf\EntityFramework\test\EFCore.Benchmarks.EF6\InitializationTests.cs:line 22
	----- Inner Stack Trace -----
	   at Microsoft.Extensions.Configuration.FileConfigurationSource.ResolveFileProvider()
	   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.<>c__DisplayClass3_0.<AddJsonFile>b__0(JsonConfigurationSource s)
	   at Microsoft.Extensions.Configuration.ConfigurationExtensions.Add[TSource](IConfigurationBuilder builder, Action`1 configureSource)
	   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, IFileProvider provider, String path, Boolean optional, Boolean reloadOnChange)
	   at Microsoft.Extensions.Configuration.JsonConfigurationExtensions.AddJsonFile(IConfigurationBuilder builder, String path)
	   at Microsoft.EntityFrameworkCore.Benchmarks.BenchmarkConfig.<>c.<.cctor>b__24_0()
	   at System.Lazy`1.CreateValue()
	   at System.Lazy`1.LazyInitValue()
	   at System.Lazy`1.get_Value()
	   at Microsoft.EntityFrameworkCore.Benchmarks.BenchmarkConfig.get_Instance()
	   at Microsoft.EntityFrameworkCore.Benchmarks.Models.AdventureWorks.TestHelpers.AdventureWorksFixtureBase..cctor()

When I try to run unit tests with TestDriven.Net from the test project EFCore.SqlServer.FunctionalTests I get the following.

	Test '' failed: Could not load file or assembly 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	System.IO.FileLoadException: Could not load file or assembly 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	File name: 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
	
	Server stack trace:
	at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
	at System.Reflection.RuntimeAssembly.GetExportedTypes()
	at System.Reflection.Assembly.get_ExportedTypes()
	at Xunit.Sdk.ReflectionAssemblyInfo.GetTypes(Boolean includePrivateTypes)
	at Xunit.Sdk.TestCollectionFactoryHelper.GetTestCollectionDefinitions(IAssemblyInfo assemblyInfo, IMessageSink diagnosticMessageSink)
	at Xunit.Sdk.CollectionPerClassTestCollectionFactory..ctor(ITestAssembly testAssembly, IMessageSink diagnosticMessageSink)
	at Xunit.Sdk.ExtensibilityPointFactory.GetXunitTestCollectionFactory(IMessageSink diagnosticMessageSink, IAttributeInfo collectionBehaviorAttribute, ITestAssembly testAssembly)
	at Xunit.Sdk.XunitTestFrameworkDiscoverer..ctor(IAssemblyInfo assemblyInfo, ISourceInformationProvider sourceProvider, IMessageSink diagnosticMessageSink, IXunitTestCollectionFactory collectionFactory)
	at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo)
	at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo)
	at Xunit.Sdk.TestFrameworkProxy.GetDiscoverer(IAssemblyInfo assembly)
	at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
	at System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage(IMessage msg)
	
	Exception rethrown at [0]:
	at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
	at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
	at Xunit.Abstractions.ITestFramework.GetDiscoverer(IAssemblyInfo assembly)
	at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk)
	at Xunit.Runner.TdNet.TdNetRunnerHelper..ctor(Assembly assembly, ITestListener testListener)
	at Xunit.Runner.TdNet.TdNetRunner.CreateHelper(ITestListener testListener, Assembly assembly)
	at Xunit.Runner.TdNet.TdNetRunner.RunAssembly(ITestListener testListener, Assembly assembly)
	at TestDriven.TestRunner.AdaptorTestRunner.Run(ITestListener testListener, ITraceListener traceListener, String assemblyPath, String testPath)
	at TestDriven.TestRunner.ThreadTestRunner.Runner.Run()

I have looked at the assemblies dependency trees, and the versions of the two assemblies which are failing to load are not referenced.  Both have a newer version referenced.  I don't see why the previous version is trying to be loaded.

Does anyone have any ideas what is going on?  Maybe an issue with KoreBuild?

**Comment by smitpatel** [comment]
We are also facing the same issue. Build is currently in broken state.

**Comment by smitpatel** [comment]
@pmiddleton - Build should be working now. Can you verify and close this issue if it is working fine?

**Comment by pmiddleton** [comment]
Both issues have been resolved.  Closing issue.
