### ISSUE TITLE
Nav rewrite: EF.Property navs not rewritten correctly

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFramework#8068]
Using EF.Property instead of a member access can result in different behavior during nav rewrite.

E.g.

```c#
  var customers
        = context.Set<Customer>()
              .Select(c => _Include(c, new [] { (object)EF.Property<ICollection<Order>>(c, "Orders") }))
              .ToList();
```
will generate:
```
'from Customer c in DbSet<Order>
  where Property([c], "CustomerID") == Property([c], "CustomerID")
  select object IncludeSqlServerTest._Include(
      customer: [c], 
      collections: new object[]{ (object) DbSet<Order> }
   )'
```
which will then cause:
```
System.ArgumentNullException : Value cannot be null.
Parameter name: querySource
	at Microsoft.EntityFrameworkCore.Utilities.Check.NotNull[T](T value, String parameterName)
	at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.AddQuery(IQuerySource querySource, SelectExpression selectExpression)
	at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalEntityQueryableExpressionVisitor.VisitEntityQueryable(Type elementType)
	at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.EntityQueryableExpressionVisitor.VisitConstant(ConstantExpression constantExpression)
```
When using a member access instead, the correct QM is produced:
```
'from Customer c in DbSet<Customer>
  select object IncludeSqlServerTest._Include(
      customer: [c], 
      collections: new object[]{ (object) ICollection<Order> MaterializeCollectionNavigation(
              navigation: Navigation: Customer.Orders (<Orders>k__BackingField, ICollection<Order>) Collection ToDependent Order Inverse: Customer 0 -1 1 -1 -1, 
              elements: 
                  from Order o in DbSet<Order>
                  where Property([c], "CustomerID") == Property([o], "CustomerID")
                  select [o]
          )
           }
    )
  '
```

**Comment by ajcvickers** [comment]
Backlog because we don't have shadow navs yet.

**Comment by maumar** [comment]
Bringing back to 2.0 as it turns out this is needed for write-only nav properties

**Comment by maumar** [comment]
This is now fixed, most likely as a side effect of collection navigation changes, closing

**Comment by smitpatel** [comment]
@maumar - Re-enable skipped test in one of the future PRs and close this issue once done.

**Comment by maumar** [comment]
tests enabled in dd1583074a522c875a82d082d455d4ed2beeb18a
