### ISSUE TITLE
Investigate netcoreapp2.0 failures

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFramework#8157]
Some tests started failing after upgrading to netcoreapp2.0. We should investigate the root cause and file appropriate issues on our dependencies.

* EFCore.InMemory.FunctionalTests
  * ComplexNavigationsQueryInMemoryTest
    - [ ] Optional_navigation_projected_into_DTO
* EFCore.Sqlite.FunctionalTests
  * ComplexNavigationsQuerySqliteTest
    - [ ] Optional_navigation_projected_into_DTO
* EFCore.SqlServer.FunctionalTests
  * ComplexNavigationsQuerySqlServerTest
    - [ ] Optional_navigation_projected_into_DTO
  * DbContextPoolingTest
    - [x] State_manager_is_reset
  * QuerySqlServerTest
    - [x] Cache_key_contexts_are_detached

**Comment by bricelam** [comment]
The last two tests may just be making invalid assumptions about the implementation of `GC.Collect()`

**Comment by ajcvickers** [comment]
@ajcvickers will investigate bottom two
@maumar to investigate others

**Comment by bricelam** [comment]
Found a few more after upgrading the specification assemblies to netcoreapp2.0:

* EFCore.Sqlite.FunctionalTests
  * QuerySqliteTest
    - [ ] TrimEnd_in_predicate
    - [ ] TrimStart_in_predicate
* EFCore.SqlServer.FunctionalTests
  * QuerySqlServerTest
    - [ ] TrimEnd_in_predicate
    - [ ] TrimStart_in_predicate

cc @smitpatel

**Comment by maumar** [comment]
more failing tests:

- [ ] Select_GroupBy_SelectMany
- [ ] Select_nested_collection_count_using_DTO
- [ ] Select_DTO_distinct_translated_to_server
- [ ] Select_DTO_constructor_distinct_translated_to_server
- [ ] Select_DTO_with_member_init_distinct_translated_to_server
- [ ] Select_DTO_with_member_init_distinct_in_subquery_used_in_projection_translated_to_server

all failing with the same underlying issue:

```
System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
Stack Trace:
	at System.String.Substring(Int32 startIndex, Int32 length)
	at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
	at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
	at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
	at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
	at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(Type type, AggregateSymbol agg)
	at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
	at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
	at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
	at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
	at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
	at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
	at Microsoft.CSharp.RuntimeBinder.CSharpConvertBinder.FallbackConvert(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
	at System.Dynamic.DynamicMetaObject.BindConvert(ConvertBinder binder)
	at System.Dynamic.ConvertBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
	at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
	at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
	at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
	at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
	at System.Linq.EnumerableSorter`1.ComputeMap(TElement[] elements, Int32 count)
	at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
	at System.Linq.OrderedEnumerable`1.ToList()
	at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by smitpatel** [comment]
Rest of tests here are being tracked in #8962. It seems bigger issue in .netcoreapp2.0 rather than the way test is designed.
Closing this as changes required to tests are done.
