### ISSUE TITLE
Cannot insert entity into DB using attach and EntityState.Added

### ISSUE THREAD

**Issue by dopare** [aspnet/EntityFramework#8264]
I am getting following exception when trying to insert entity by attaching and changing its state.

```
Microsoft.EntityFrameworkCore.DbUpdateException occurred
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=Microsoft.EntityFrameworkCore.Relational
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at EFCoreTest.Program.Main() in C:\Users\Dopare\documents\visual studio 2017\Projects\EFCoreTest\EFCoreTest\Program.cs:line 22

Inner Exception 1:
SqlException: Cannot insert explicit value for identity column in table 'Persons' when IDENTITY_INSERT is set to OFF.
```

### Steps to reproduce
[Sample repo](https://github.com/dopare/EFCoreTest)

```c#
using (var db = new AppDbContext())
{
    var person = new Person
    {
        FirstName = "FirstName",
        LastName = "LastName",
        BirthDate = DateTime.Now
    };

    db.Persons.Attach(person);
    db.Entry(person).State = EntityState.Added;

    db.SaveChanges();
}
```

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 x64
IDE: (e.g. Visual Studio 2015)

**Comment by ajcvickers** [comment]
@dopare Attaching the entity means that the entity already exists in the database. This means that no key generation is done--because the key must already have had a value assigned to be saved int the database. On the other hand, if Add is called, then it means that the entity is new and has not yet been saved to the database. In this case key generation will kick in, ultimately using the Identity column in the database

In this case, because the entity was first Attached, and then later changed to Added, it is not getting key generation. However, we are considering changing this so that even if the entity is first Attached, then later when it is made Added it will get the same key generation that would have happened if it was made Added in the first place.
