### ISSUE TITLE
Query on self referenced object

### ISSUE THREAD

**Issue by dvdobrovolskiy** [aspnet/EntityFramework#8484]
With model like this
```
    public class ControlledObject
    {
        [Key]
        [Display(Name = "Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid ControlledObjectId { get; set; }

        [Display(Name = "Название объекта")]
        public string Title { get; set; }

        [Display(Name = "Родительский объект")]
        public ControlledObject Parent { get; set; }

        [Display(Name = "Порядок сортировки")]
        public int Order { get; set; }

        [Display(Name = "Выбран")]
        public bool Checked { get; set; }

        [NotMapped]
        public bool hasChildren { get; set; }
    }
```
I want to calculate hasChildren in query but I get error whet trying
```
_context.ControlledObjects.Select(s => new ControlledObject
            {
                Checked = s.Checked,
                ControlledObjectId = s.ControlledObjectId,
                hasChildren = (_context.ControlledObjects.Where(w=>w.Parent == s).ToList().Count() > 0),
                Order = s.Order,
                Parent = s.Parent,
                Title = s.Title,
            }).OrderBy(o => o.Order)
```

Message	"The binary operator GreaterThan is not defined for the types 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[TNPK.Data.ControlledObject,System.Collections.Generic.IEnumerable`1[TNPK.Data.ControlledObject]]]' and 'System.Int32'."	string

```
_context.ControlledObjects.Select(s => new ControlledObject
            {
                Checked = s.Checked,
                ControlledObjectId = s.ControlledObjectId,
                hasChildren = _context.ControlledObjects.Any(a=>a.Parent == s),
                Order = s.Order,
                Parent = s.Parent,
                Title = s.Title,
            }).OrderBy(o => o.Order);
```
also failure with Message = "Argument types do not match"

**Comment by maumar** [comment]
@dvdobrovolskiy which version of EF Core are you using? I tried this scenario on current bits and it seems to be working fine.

For the first query, if you remove the "ToList" in the hasChildren column, we produce:

```sql
SELECT [s.Parent].[ControlledObjectId], [s.Parent].[Checked], [s.Parent].[Order], [s.Parent].[ParentControlledObjectId], [s.Parent].[Title], [s].[Checked] AS [Checked0], [s].[ControlledObjectId] AS [ControlledObjectId0], CASE
	WHEN (
		SELECT COUNT(*)
		FROM [ControlledObjects] AS [w]
		WHERE [w].[ParentControlledObjectId] = [s].[ControlledObjectId]
	) > 0
	THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
END AS [hasChildren], [s].[Order] AS [Order0], [s].[Title] AS [Title0]
FROM [ControlledObjects] AS [s]
LEFT JOIN [ControlledObjects] AS [s.Parent] ON [s].[ParentControlledObjectId] = [s.Parent].[ControlledObjectId]
ORDER BY [Order0]
```

the second query works out of the box, and produces:

```sql
SELECT [s.Parent].[ControlledObjectId], [s.Parent].[Checked], [s.Parent].[Order], [s.Parent].[ParentControlledObjectId], [s.Parent].[Title], [s].[Checked] AS [Checked0], [s].[ControlledObjectId] AS [ControlledObjectId0], (
	SELECT CASE
		WHEN EXISTS (
			SELECT 1
			FROM [ControlledObjects] AS [a]
			WHERE [a].[ParentControlledObjectId] = [s].[ControlledObjectId])
		THEN CAST(1 AS BIT) ELSE CAST(0 AS BIT)
	END
) AS [hasChildren], [s].[Order] AS [Order0], [s].[Title] AS [Title0]
FROM [ControlledObjects] AS [s]
LEFT JOIN [ControlledObjects] AS [s.Parent] ON [s].[ParentControlledObjectId] = [s.Parent].[ControlledObjectId]
ORDER BY [Order0]
```

However, the first query with the ToList call throws the following (from Relinq parsing code):

System.NotSupportedException: Could not parse expression 'value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Repro8484.ControlledObject]).Where(w => (w.Parent == s)).ToList()': This overload of the method 'System.Linq.Enumerable.ToList' is currently not supported.
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.GetNodeType(MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Visit(Expression expression)
   at Remotion.Linq.Parsing.ExpressionVisitors.SubQueryFindingExpressionVisitor.Process(Expression expressionTree, INodeTypeProvider nodeTypeProvider)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.ProcessArgumentExpression(Expression argumentExpression)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Remotion.Linq.Parsing.Structure.MethodCallExpressionParser.Parse(String associatedIdentifier, IExpressionNode source, IEnumerable`1 arguments, MethodCallExpression expressionToParse)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseMethodCallExpression(MethodCallExpression methodCallExpression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseNode(Expression expression, String associatedIdentifier)
   at Remotion.Linq.Parsing.Structure.ExpressionTreeParser.ParseTree(Expression expressionTree)
   at Remotion.Linq.Parsing.Structure.QueryParser.GetParsedQuery(Expression expressionTreeRoot)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType) in C:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 123
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_0`1.<Execute>b__0() in C:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 102
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\git\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 69
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\git\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 44
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\git\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\git\EntityFramework\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 62
   at Remotion.Linq.QueryableBase`1.GetEnumerator()

**Comment by dvdobrovolskiy** [comment]
1.1.2
Sorry. I added to list in case it might resolve situation or change behaviour 

this query generates error
```
            var result= _context.ControlledObjects.Select(s => new ControlledObject
            {
                Checked = s.Checked,
                ControlledObjectId = s.ControlledObjectId,
                hasChildren = (_context.ControlledObjects.Where(w => w.Parent == s).Count() > 0),
                Order = s.Order,
                Parent = s.Parent,
                Title = s.Title,
            }).OrderBy(o => o.Order);
```

Message	"The binary operator GreaterThan is not defined for the types 'System.Collections.Generic.IEnumerable`1[Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor+TransparentIdentifier`2[TNPK.Data.ControlledObject,System.Collections.Generic.IEnumerable`1[TNPK.Data.ControlledObject]]]' and 'System.Int32'."	string

**Comment by maumar** [comment]
Closing as fixed then - this should be fixed in preview1 so upgrading to that version would be one solution. Otherwise you can try removing the GreaterThan operator and do it on the client instead:

```cs
            var result= _context.ControlledObjects.Select(s => new ControlledObject
            {
                Checked = s.Checked,
                ControlledObjectId = s.ControlledObjectId,
                childrenCount = _context.ControlledObjects.Where(w => w.Parent == s).Count(),
                Order = s.Order,
                Parent = s.Parent,
                Title = s.Title,
            }).OrderBy(o => o.Order).ToList().Select(s =>
{
               s.Checked,
                s.ControlledObjectId,
                hasChildren = s.childrenCount > 0,
                s.Order,
                s.Parent,
                s.Title,
};
```

**Comment by dvdobrovolskiy** [comment]
Got ya. tnks
