### ISSUE TITLE
Investigate flaky tests

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#8615]
Command time in `F1SqlServerFixture` had to be increased. `DataBindingSqlServerTest` failed randomly with this exception
```
System.Data.SqlClient.SqlException : Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
---- System.ComponentModel.Win32Exception : The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection) in C:\b\w\437c4411cf4e11ab\src\EFCore.Relational\Storage\Internal\RelationalCommand.cs:line 271
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues) in C:\b\w\437c4411cf4e11ab\src\EFCore.Relational\Storage\Internal\RelationalCommand.cs:line 134
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer) in C:\b\w\437c4411cf4e11ab\src\EFCore.Relational\Query\Internal\QueryingEnumerable.cs:line 132
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state) in C:\b\w\437c4411cf4e11ab\src\EFCore.SqlServer\Storage\Internal\SqlServerExecutionStrategy.cs:line 37
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext() in C:\b\w\437c4411cf4e11ab\src\EFCore.Relational\Query\Internal\QueryingEnumerable.cs:line 86
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext() in C:\b\w\437c4411cf4e11ab\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 174
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext() in C:\b\w\437c4411cf4e11ab\src\EFCore\Query\Internal\LinqOperatorProvider.cs:line 138
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load[TSource](IQueryable`1 source) in C:\b\w\437c4411cf4e11ab\src\EFCore\EntityFrameworkQueryableExtensions.cs:line 2578
   at Microsoft.EntityFrameworkCore.DatabindingTestBase`2.LocalView_is_initialized_with_entities_from_the_context() in C:\b\w\437c4411cf4e11ab\src\EFCore.Specification.Tests\DatabindingTestBase.cs:line 413
----- Inner Stack Trace -----
```

Disabled test SqlServerDatabaseCreatorEnsureDeletedTest.EnsuredDeletedAsync_noop_when_database_doesnt_exist
Exception
```
System.Data.SqlClient.SqlException : A connection was successfully established with the server, but then an error occurred during the login process. (provider: Named Pipes Provider, error: 0 - No process is on the other end of the pipe.)
---- System.ComponentModel.Win32Exception : No process is on the other end of the pipe
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.<OpenAsync>d__34.MoveNext() in C:\BuildAgent\work\15b0c01bdac8ff3d\src\EFCore.Relational\Storage\RelationalConnection.cs:line 382
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext() in C:\BuildAgent\work\15b0c01bdac8ff3d\src\EFCore.SqlServer\Storage\Internal\SqlServerDatabaseCreator.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass20_0.<<ExistsAsync>b__0>d.MoveNext() in C:\BuildAgent\work\15b0c01bdac8ff3d\src\EFCore.SqlServer\Storage\Internal\SqlServerDatabaseCreator.cs:line 167
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorEnsureDeletedTest.<EnsuredDeleted_noop_when_database_doesnt_exist_test>d__13.MoveNext() in C:\BuildAgent\work\15b0c01bdac8ff3d\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServerDatabaseCreatorEnsureDeletedTest.<EnsuredDeletedAsync_noop_when_database_doesnt_exist>d__11.MoveNext() in C:\BuildAgent\work\15b0c01bdac8ff3d\test\EFCore.SqlServer.FunctionalTests\SqlServerDatabaseCreatorTest.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
```

**Comment by smitpatel** [comment]
@AndriySvyryd - Any comment on first failure here? I had set timeout to 300. Looks like its still not sufficient for slow system like AppVeyor.

**Comment by AndriySvyryd** [comment]
@smitpatel We use 600 in other tests. 
This might be caused by a perf regression in SqlClient, we would need to compare running the tests against different builds.

**Comment by smitpatel** [comment]
I will update timeout to 600 and try.

**Comment by smitpatel** [comment]
ExistsAsync_returns_false_when_database_with_filename_doesnt_exist disabled

**Comment by smitpatel** [comment]
Can we close this issue now?
