### ISSUE TITLE
Test: Investigate Entity_equality_empty for owned entities

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFramework#8809]
It fails for OwnedQueryTestBase
```
Test 'Microsoft.EntityFrameworkCore.ComplexNavigationsOwnedQueryInMemoryTest.Entity_equality_empty' failed: System.InvalidOperationException : The EF.Property<T> method may only be used within LINQ queries.
	D:\EntityFramework\src\EFCore\EF.cs(41,0): at Microsoft.EntityFrameworkCore.EF.Property[TProperty](Object entity, String propertyName)
	at lambda_method(Closure , TransparentIdentifier`2 )
	at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
	D:\EntityFramework\src\EFCore\Query\Internal\LinqOperatorProvider.cs(138,0): at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
	at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
	at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
	D:\EntityFramework\src\EFCore.Specification.Tests\ComplexNavigationsQueryTestBase.cs(3694,0): at Microsoft.EntityFrameworkCore.ComplexNavigationsQueryTestBase`2.AssertQuery[TItem1](Func`2 efQuery, Func`2 l2oQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered)
	D:\EntityFramework\src\EFCore.Specification.Tests\ComplexNavigationsQueryTestBase.cs(3682,0): at Microsoft.EntityFrameworkCore.ComplexNavigationsQueryTestBase`2.AssertQuery[TItem1](Func`2 query, Func`2 elementSorter, Action`2 elementAsserter, Boolean verifyOrdered)
	D:\EntityFramework\src\EFCore.Specification.Tests\ComplexNavigationsQueryTestBase.cs(46,0): at Microsoft.EntityFrameworkCore.ComplexNavigationsQueryTestBase`2.Entity_equality_empty()
```

**Comment by AndriySvyryd** [comment]
That test uses a free-hanging instance of a dependent type in the query, this is not supported:
```C#
l1s => l1s.Where(l => l.OneToOne_Optional_FK == new Level2())
```

**Comment by smitpatel** [comment]
@AndriySvyryd - Can you disable it like other tests in OwnedEntityTestBase?
