### ISSUE TITLE
SQL date type being cast to datetime

### ISSUE THREAD

**Issue by ryan-w** [aspnet/EntityFramework#8894]
When using the SQL 'date' type I should be able to insert a date prior to 1753, but I receive the following exception.

```
Microsoft.EntityFrameworkCore.DbUpdateException occurred
  HResult=0x80131500
  Message=An error occurred while updating the entries. See the inner exception for details.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ConsoleApp1.Program.Main(String[] args) in C:\ConsoleApp1\Program.cs:line 14

Inner Exception 1:
SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
```

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new ApplicationContext())
            {
                var item = new Item { Date = new DateTime(1605, 1, 15) };
                db.Add(item);
                db.SaveChanges();
            }
        }
    }

    public class ApplicationContext : DbContext
    {
        public DbSet<Item> Items { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=TempDateTest;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);

            builder.Entity<Item>()
                .Property(m => m.Date)
                .ForSqlServerHasColumnType("date");
        }
    }

    public class Item
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
    }
}
```

### Further technical details
EF Core version: 1.1.2
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 8.1
IDE: Visual Studio 2017

**Comment by AndriySvyryd** [comment]
Looks like a SQLClient issue, will create a standalone repro.

**Comment by AndriySvyryd** [comment]
Filed https://github.com/dotnet/corefx/issues/21279

**Comment by ajcvickers** [comment]
@AndriySvyryd Do you think that #6025 is another manifestation of the same underlying issue?

**Comment by AndriySvyryd** [comment]
@ajcvickers  Looks like it. I'll verify that it was fixed.

**Comment by ryan-w** [comment]
@AndriySvyryd Thank you.
