### ISSUE TITLE
Query: Skip/Take followed by GroupJoin throws 'must be reducible node' exception

### ISSUE THREAD

**Issue by cex-pnaik** [aspnet/EntityFramework#8935]
My application is in .net core pointing to 1.1.1 framework. DB provider which I am using is Pomelo.EntityFrameworkCore.MySql

The query which I am trying to execute is as follows:

```
var queryEF = (from b in context.table1
                                orderby b.column1 descending
                                select new Table1
                                {
                                    column1 = b.column1,
                                });

queryEF = queryEF.Skip(3).Take(10).AsQueryable();

var query2 = (from b in queryEF
              join lb in context.table2
              on b.column1 equals lb.column1
              into tablejoin
              from blb in 
              tablejoin.DefaultIfEmpty()
              select new
              {
                 b.column1
              });

              if (query2  != null)
              {
                 foreach (var locnBranch in query2.AsEnumerable())
                 {
                 }
              }
```
The above query fails, at execution of AsEnumerable(). It throws 'Must be reducible node' error.

Exception details:

```
{System.ArgumentException: must be reducible node
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMemberExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteLambdaExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression node)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, INodeTypeProvider nodeTypeProvider, IDatabase database, ILogger logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass19_0`1.<CompileQuery>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at GetAll() in E:\Test\Repository.cs:line 291
   at Get(List`1 Keys, String operatingCompany, Boolean isTrading, Int32 firstRecord, Int32 count, String clientIPAddress, String sortBy, String sortOrder) in E:\Test\Repository.cs:line 51
   at Get(List`1 Keys, String operatingCompany, Boolean isTrading, Int32 firstRecord, Int32 count, String clientIPAddress, String sortBy, String sortOrder) in E:\BusinessServices\Service.cs:line 121
   at Get(List`1 Keys, String operatingCompany, Boolean isTrading, Int32 firstRecord, Int32 count, String clientIPAddress, String sortBy, String sortOrder) in E:\Controllers\esController.cs:line 54
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()}
```
The above query works fine, after removing skip/take from it. I tested the query in EF5 and it works without any issue, its failing only in EF core.

**Comment by smitpatel** [comment]
First of all, `query2` is not used in above code. You are creating it but not enumerating it so EF will not execute it.

Removing that part, I took rest of the code and tried to repro using 1.1.1 packages
Query used
```C#
var queryEF = (from b in context.table1
            orderby b.column1 descending
            select new Table1
            {
                column1 = b.column1,
            });

queryEF = queryEF.Skip(3).Take(10).AsQueryable();

if (queryEF != null)
{
    foreach (var locnBranch in queryEF.AsEnumerable())
    {
    }
}
```
SQL Generated
```SQL
Executed DbCommand (4ms) [Parameters=[@__p_0='3', @__p_1='10'], CommandType='Text', CommandTimeout='30']
SELECT [b].[column1]
FROM [table1] AS [b]
ORDER BY [b].[column1] DESC
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
```
Can you provide a complete repro which reproduces this issue?

**Comment by smitpatel** [comment]
Iterating over query2 gives the error.
Complete repro: (using EFCore.SqlServer 1.1.2)
```C#
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                var serviceProvider = db.GetInfrastructure();
                var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
                loggerFactory.AddConsole(LogLevel.Information);
            }

            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                using (var context = new MyContext())
                {
                    // Run queries
                    var query = context.Blogs
                        .OrderBy(b => b.Id)
                        .Select(
                            b => new Blog
                            {
                                Id = b.Id
                            })
                        .Skip(3)
                        .Take(10)
                        .GroupJoin(context.Posts, b => b.Id, p => p.BlogId, (b, ps) => new { b.Id })
                        .ToList();
                }

                Console.WriteLine("Program finished.");
            }
        }


        public class MyContext : DbContext
        {
            // Declare DBSets
            public DbSet<Blog> Blogs { get; set; }
            public DbSet<Post> Posts { get; set; }

            protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
            {
                // Select 1 provider
                optionsBuilder
                    .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;")
                    //     .UseSqlite("filename=_modelApp.db")
                    //     .UseInMemoryDatabase(databaseName: "_modelApp")
                    .EnableSensitiveDataLogging();
            }

            protected override void OnModelCreating(ModelBuilder modelBuilder)
            {
                // Configure model
            }
        }

        public class Blog
        {
            public int Id { get; set; }
            public IList<Post> Posts { get; set; }
        }

        public class Post
        {
            public int Id { get; set; }
            public int BlogId { get; set; }
            public Blog Blog { get; set; }
        }
    }
}
```

This works correctly in version EFCore 2.0.0-preview1
Generated query:
```SQL
Executed DbCommand (36ms) [Parameters=[@__p_0='3', @__p_1='10'], CommandType='Text', CommandTimeout='30']
SELECT [t].[Id], [p].[Id], [p].[BlogId]
FROM (
  SELECT [b].[Id]
  FROM [Blogs] AS [b]
  ORDER BY [b].[Id]
  OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
) AS [t]
LEFT JOIN [Posts] AS [p] ON [t].[Id] = [p].[BlogId]
ORDER BY [t].[Id]
```

**Comment by cex-pnaik** [comment]
@smitpatel My bad, I am actually iterating over query2, which throws 'Must be reducible node' exception. I have updated my question as well.

Let me test my code with EFCore 2.0.0-preview1, will update you the details.

**Comment by cex-pnaik** [comment]
@smitpatel After adding Microsoft.EntityFrameworkCore 2.0.0-preview1-final to my .net core project pointing to 1.1.1 framework, I get following exception in Program.cs.
```
System.MissingMethodException occurred
  HResult=0x80131513
  Message=Method not found: 'System.IServiceProvider Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Kiwi.BranchService.Web.Program.Main(String[] args) in Program.cs:line 16
```

**Comment by smitpatel** [comment]
That exception probably suggests package mismatch. Did you upgrade all the packages from ASP.NET Core to 2.0.0-preview1?
