### ISSUE TITLE
Asynchronous mode does not work

### ISSUE THREAD

**Issue by voronov-maxim** [aspnet/EntityFramework#8938]
Synchronous mode works, Asynchronous mode does not work

```
Exception message:
Expression of type 'System.Collections.Generic.IEnumerable`1[System.Tuple`1[System.String]]' cannot be used for return type 'System.Collections.Generic.IAsyncEnumerable`1[System.Tuple`1[System.String]]'

Stack trace:
   at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters, String paramName)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateAsyncQueryExecutor[TResult](QueryModel queryModel)
   at EfCoreBug.Program.CreateAsyncQueryExecutor[T](DbContext dbContext, Expression expression) in D:\vorona\EfCoreBug\EfCoreBug\Program.cs:line 70
   at EfCoreBug.Program.Main(String[] args) in D:\vorona\EfCoreBug\EfCoreBug\Program.cs:line 59
```

### Steps to reproduce
```c#
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Query;
using Remotion.Linq;
using Remotion.Linq.Parsing.ExpressionVisitors.Transformation;
using Remotion.Linq.Parsing.ExpressionVisitors.TreeEvaluation;
using Remotion.Linq.Parsing.Structure;
using Remotion.Linq.Parsing.Structure.ExpressionTreeProcessors;
using Remotion.Linq.Parsing.Structure.NodeTypeProviders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace EfCoreBug
{
    public sealed class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    public sealed class OrderItem
    {
        public int Id { get; set; }
        public Order Order { get; set; }
        public int OrderId { get; set; }
    }

    public sealed class OrderContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseInMemoryDatabase("test");
            base.OnConfiguring(optionsBuilder);
        }

        public DbSet<Order> Orders { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var dbContext = new OrderContext())
            {
                dbContext.Orders.Add(new Order() { Id = 1, Name = "order 1" });
                dbContext.OrderItems.Add(new OrderItem() { Id = 1, OrderId = 1 });
                dbContext.SaveChanges();

                var queryContextFactory = dbContext.GetService<IQueryContextFactory>();
                QueryContext queryContext = queryContextFactory.Create();
                IQueryable<Tuple<string>> query = dbContext.OrderItems.GroupBy(i => i.Order.Id).Select(g => new Tuple<string>(g.Max(i => i.Order.Name)));

                Func<QueryContext, IEnumerable<Tuple<string>>> executorSync = CreateQueryExecutor<Tuple<string>>(dbContext, query.Expression);
                List<Tuple<string>> resultSync = executorSync(queryContext).ToList();

                Func<QueryContext, IAsyncEnumerable<Tuple<string>>> executorAsync = CreateAsyncQueryExecutor<Tuple<string>>(dbContext, query.Expression);
                List<Tuple<string>> resultAsync = executorAsync(queryContext).ToList().GetAwaiter().GetResult();
            }
        }

        private sealed class ApiCompilationFilter : EvaluatableExpressionFilterBase { }

        public static Func<QueryContext, IAsyncEnumerable<T>> CreateAsyncQueryExecutor<T>(DbContext dbContext, Expression expression)
        {
            QueryModel queryModel = CreateQueryModel(dbContext, expression);
            var queryCompilationContextFactory = dbContext.GetService<IQueryCompilationContextFactory>();
            return queryCompilationContextFactory.Create(true).CreateQueryModelVisitor().CreateAsyncQueryExecutor<T>(queryModel);
        }
        public static Func<QueryContext, IEnumerable<T>> CreateQueryExecutor<T>(DbContext dbContext, Expression expression)
        {
            QueryModel queryModel = CreateQueryModel(dbContext, expression);
            var queryCompilationContextFactory = dbContext.GetService<IQueryCompilationContextFactory>();
            return queryCompilationContextFactory.Create(false).CreateQueryModelVisitor().CreateQueryExecutor<T>(queryModel);
        }
        private static QueryModel CreateQueryModel(DbContext dbContext, Expression expression)
        {
            INodeTypeProvider nodeTypeProvider = dbContext.GetService<MethodInfoBasedNodeTypeRegistry>();
            var queryParser = new QueryParser(
                new ExpressionTreeParser(nodeTypeProvider,
                new CompoundExpressionTreeProcessor(
                    new IExpressionTreeProcessor[]
                    {
                            new PartialEvaluatingExpressionTreeProcessor(new ApiCompilationFilter()),
                            new TransformingExpressionTreeProcessor(ExpressionTransformerRegistry.CreateDefault())
                    })));
            return queryParser.GetParsedQuery(expression);
        }
    }
}
```

### Further technical details
EF Core version: 1.1.2
Database Provider: SqlServer 1.1.2, InMemory 1.1.2
Operating system: Windows 7, Windows 10
IDE: Visual Studio 2017

**Comment by anpete** [comment]
@voronov-maxim Does this repro with when using the more conventional APIs? I.e. Without manually creating the query via our low level services.

**Comment by voronov-maxim** [comment]
@anpete No, this failed the test in my program

**Comment by anpete** [comment]
@voronov-maxim Can you post that repro code? Will be easier for us to deal with.

**Comment by voronov-maxim** [comment]
https://github.com/voronov-maxim/OdataToEntity/blob/master/test/OdataToEntity.Test/Common/SelectTest.cs#L51

workaround this bug, i run test in synchronous mode

**Comment by anpete** [comment]
Pasting in the relevant code:
```c#
Expression = t => t.GroupBy(i => new { i.OrderId, i.Order.Status }).Select(g => new
                {
                    OrderId = g.Key.OrderId,
                    Order_Status = g.Key.Status,
                    avg = g.Average(i => i.Price),
                    dcnt = g.Select(i => i.Product).Distinct().Count(),
                    max = g.Max(i => i.Price),
                    max_status = g.Max(i => i.Order.Status),
                    min = g.Min(i => i.Price),
                    sum = g.Sum(i => i.Price),
                    cnt = g.Count()
                })
```
Looks like a complex GroupBy case.

**Comment by voronov-maxim** [comment]
@anpete fix in https://github.com/aspnet/EntityFramework/pull/8965/commits/f116e0d38683845e732a3e76a7a5b9441f3b75d1
