### ISSUE TITLE
Navigation collection being materialized as HashSet instead of List

### ISSUE THREAD

**Issue by roji** [aspnet/EntityFramework#9039]
I've been porting the Npgsql provider to work against the recently-released 2.0.0-preview2. After quite a bit of work I've reached a point where only 1 test is failing: QueryNavigationsNpgsqlTest.Select_collection_navigation_simple.

Given the following LINQ:

```c#
from c in context.Customers
    where c.CustomerID.StartsWith("A")
    orderby c.CustomerID
    select new { c.CustomerID, c.Orders }
```

The Orders navigation property on each customer is strangely materialized as a HashSet<Order> instead of List<Order>. I have no idea what missing thing in the Npgsql provider is causing this, any guidance would be appreciated.

**Comment by roji** [comment]
The current state of the port can be seen in https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/tree/preview2

**Comment by ajcvickers** [comment]
@roji Are you saying that SQL Server gets a List, but it your code it is a HashSet? (When not collection type is specified and EF creates the collection, then the default is HashSet, not List, but this is not provider-specific.)

**Comment by roji** [comment]
Yeah, I'm really not sure what's going on. Running this test with the Npgsql provider gives the following:

```
Failed   Npgsql.EntityFrameworkCore.PostgreSQL.FunctionalTests.QueryNavigationsNpgsqlTest.Select_collection_navigation_simple
Error Message:
 Assert.Equal() Failure
Expected: List<Order> [Order 10643, Order 10692, Order 10702, Order 10835, Order 10952, ...]
Actual:   HashSet<Order> [Order 10835, Order 11011, Order 10692, Order 10702, Order 10643, ...]
Stack Trace:
   at CallSite.Target(Closure , CallSite , Type , Object , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Npgsql.EntityFrameworkCore.PostgreSQL.FunctionalTests.QueryNavigationsNpgsqlTest.<>c.<Select_collection_navigation_simple>b__2_1(IList`1 l2oItems, IList`1 efItems) in C:\projects\Npgsql.EntityFrameworkCore.PostgreSQL\test\EFCore.PG.FunctionalTests\QueryNavigationsNpgsqlTest.cs:line 49
   at Microsoft.EntityFrameworkCore.TestHelpers.AssertResults[T](IList`1 expected, IList`1 actual, Boolean assertOrder, Action`2 asserter)
   at Microsoft.EntityFrameworkCore.QueryNavigationsTestBase`1.AssertQuery[TItem](Func`2 efQuery, Func`2 l2oQuery, Boolean assertOrder, Int32 entryCount, Action`2 asserter)
   at Microsoft.EntityFrameworkCore.QueryNavigationsTestBase`1.AssertQuery[TItem](Func`2 query, Boolean assertOrder, Int32 entryCount, Action`2 asserter)
   at Npgsql.EntityFrameworkCore.PostgreSQL.FunctionalTests.QueryNavigationsNpgsqlTest.Select_collection_navigation_simple() in C:\projects\Npgsql.EntityFrameworkCore.PostgreSQL\test\EFCore.PG.FunctionalTests\QueryNavigationsNpgsqlTest.cs:line 37
```

Running it with the SqlServer provider obviously works. As I wrote above, checking the results from the LINQ query shows that Orders is a HashSet<Order>. As you say this seems far away from anything the provider can mess around with, which is why I thought I'd talk to you guys... Any ideas?

**Comment by ajcvickers** [comment]
@roji I investigated this on SQL Server and the navigation property is materialized as a HashSet there too. 

![image](https://user-images.githubusercontent.com/1430078/27806200-0cc880fa-5fee-11e7-910c-81a06ffb11b7.png)


So the difference is in the order of entities in the collection, rather than the collection type itself. This order is not defined anyway, so it's really a test issue. @maumar is in the process of re-working these assertions anyway, but for now I'll send out a PR that should hopefully unblock you.

**Comment by roji** [comment]
Oh, I understand - I was misled by the test failure message mentioning the types.

Thanks, I'll skip the test for preview2 and reenable afterwards.
