### ISSUE TITLE
EF Core 2.0.0-preview3-26027 NullReferenceException on RelationalCommand

### ISSUE THREAD

**Issue by carlosga** [aspnet/EntityFramework#9041]
RelationalCommand throws a NullReferenceException when the underliying ADO.NET data provider returns null for their command Parameters property on disposed commands.

With the changes done on commit #9023 the Parameters collection of the DbCommand implementation maybe accessed after the command has been disposed and the connection closed, if the underliying provider is setting it to null on disposal it will throw a NullReferenceException

```
if (!readerOpen)
{
     dbCommand.Dispose();
     connection.Close();
}

**dbCommand.Parameters.Clear();**

```
Exception details:

```
System.NullReferenceException : Object reference not set to an instance of an object.
Stack Trace:
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.RelationalDatabaseCleaner.Clean(DatabaseFacade facade)
at PostgreSql.EntityFrameworkCore.Utilities.PostgreSqlDatabaseFacadeExtensions.<>c.<EnsureClean>b__0_0(DatabaseFacade database)
at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__2`1.<Execute>b__2_0(<>f__AnonymousType0`2 s)
at PostgreSql.EntityFrameworkCore.Storage.Internal.PostgreSqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState](IExecutionStrategy strategy, TState state, Action`1 operation)
at PostgreSql.EntityFrameworkCore.Utilities.PostgreSqlDatabaseFacadeExtensions.EnsureClean(DatabaseFacade databaseFacade)
at PostgreSql.EntityFrameworkCore.Utilities.PostgreSqlTestStore.Clean(String name)
at PostgreSql.EntityFrameworkCore.Utilities.PostgreSqlTestStore.CreateDatabase()
at PostgreSql.EntityFrameworkCore.Utilities.PostgreSqlTestStore.<>c__DisplayClass20_0.<CreateShared>b__0()
at Microsoft.EntityFrameworkCore.TestStore.CreateShared(String name, Action initializeDatabase)
at PostgreSql.EntityFrameworkCore.Utilities.PostgreSqlTestStore.CreateShared(Action initializeDatabase)
at PostgreSql.EntityFrameworkCore.Utilities.PostgreSqlTestStore.GetOrCreateShared(String name, Action initializeDatabase, Boolean cleanDatabase)
at PostgreSql.EntityFrameworkCore.ExecutionStrategyTest..ctor(ExecutionStrategyFixture fixture)
```

### Further technical details
EF Core version: 2.0.0-preview3-26027
Operating system: Ubuntu 17.10
IDE: Visual Studio Code

**Comment by ErikEJ** [comment]
@bricelam Looks like the SQL CE ADO.NET provider also will be hit by this, please look into it before 2.0!

**Comment by bricelam** [comment]
Found out why we clear them at all: #6249

I'm surprised we didn't hit this before; the previous code also disposed before clearing.

I'll update it to clear before disposing.
