### ISSUE TITLE
several .Includes cause InvalidOperationException

### ISSUE THREAD

**Issue by dbis01** [aspnet/EntityFramework#962]
var checks = modelBuilder.Entity<Check>();
            checks.Key(c => c.CheckId);
            checks.ManyToOne(c => c.Template).ForeignKey(c => c.TemplateId);
            checks.ManyToOne(c => c.Site).ForeignKey(c => c.SiteId);

            // get local
            IQueryable<Check> q = LocalContext.Checks
            //    .Include(c => c.Template)
                .Include(c => c.Site)
                .Where(...);
            var tt = q.ToList();

when I have both .Include() on query I get an exception (details are below). when I comment out any one of them query runs ok

System.InvalidOperationException was unhandled by user code
  HResult=-2146233079
  Message=Sequence contains more than one matching element
  Source=System.Core
  StackTrace:
       at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
       at Microsoft.Data.Entity.Relational.Query.Expressions.SelectExpression.FindTableForQuerySource(IQuerySource querySource)
       at Microsoft.Data.Entity.Relational.Query.RelationalQueryModelVisitor.IncludeReference(IQuerySource querySource, INavigation navigation)
       at Microsoft.Data.Entity.Relational.Query.RelationalQueryModelVisitor.IncludeNavigation(IQuerySource querySource, Type resultType, LambdaExpression accessorLambda, INavigation navigation)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.IncludeNavigations(QueryModel queryModel, Type resultType, ICollection`1 queryAnnotations)
       at Microsoft.Data.Entity.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
       at Microsoft.Data.Entity.Relational.RelationalDataStore.Query[TResult](QueryModel queryModel)
       at Microsoft.Data.Entity.Query.EntityQueryExecutor.ExecuteCollection[T](QueryModel queryModel)
       at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteCollectionQueryModel[T](QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.Clauses.StreamedData.StreamedSequenceInfo.ExecuteQueryModel(QueryModel queryModel, IQueryExecutor executor)
       at Remotion.Linq.QueryModel.Execute(IQueryExecutor executor)
       at Remotion.Linq.QueryProviderBase.Execute(Expression expression)
       at Remotion.Linq.QueryProviderBase.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
       at Remotion.Linq.QueryableBase`1.GetEnumerator()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at Dixy.Ubi.CheckLists.ContentProvider.ContentProvider.<GetChecks>d__25.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
       at Dixy.Ubi.CheckLists.ViewModels.ChecksViewModel.<ApplyFilter>d__12.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Dixy.Ubi.CheckLists.ViewModels.ChecksViewModel.<InitialLoad>d__4.MoveNext()
  InnerException:

**Comment by anpete** [comment]
Fixed
