### ISSUE TITLE
Exception for entity with two relationships to the same entity type, and no explicit foreign keys

### ISSUE THREAD

**Issue by maumar** [aspnet/EntityFramework#967]
Consider the following:

```
 public class Person
    {
        public int Id { get; set; }
        public Animal Pet { get; set; }
        public Animal BestFriend { get; set; }
    }

    public class Animal
    {
        public int IdProperty { get; set; }
        public string Sound { get; set; }
    }
    
    public class MyContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        public DbSet<Animal> Animals { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>().OneToOne(p => p.Pet);
            modelBuilder.Entity<Person>().OneToOne(p => p.BestFriend);
        }

        protected override void OnConfiguring(DbContextOptions options)
        {
            options.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=ReproDb;Trusted_Connection=True;MultipleActiveResultSets=true");
        }
    }

            using (var ctx = new MyContext())
            {
                var dog = new Animal { Sound = "Woof" };
                var man = new Person { Pet = dog, BestFriend = dog };
                ctx.People.Add(man);
                ctx.Animals.Add(dog);
                ctx.SaveChanges();
            }
```

this throws:

System.InvalidOperationException: The foreign key 'PersonId' cannot be added to the entity type 'Repro.Animal' because a foreign key on the same properties already exists.
   at Microsoft.Data.Entity.Metadata.EntityType.AddForeignKey(IReadOnlyList`1 properties, Key referencedKey)
   at Microsoft.Data.Entity.Metadata.ModelConventions.ForeignKeyConvention.FindOrCreateForeignKey(EntityType principalType, EntityType dependentType, String navigationToPrincipal, String navigationToDependent, IReadOnlyList`1 foreignKeyProperties, IReadOnlyList`1 referencedProperties, Boolean isUnique)
   at Microsoft.Data.Entity.Metadata.ModelConventions.ForeignKeyConvention.FindOrCreateForeignKey(EntityType principalType, EntityType dependentType, String navigationToPrincipal, String navigationToDependent, Boolean isUnqiue)
   at Microsoft.Data.Entity.Metadata.Internal.InternalEntityBuilder.BuildRelationship(EntityType principalEntityType, EntityType dependentEntityType, String navNameToPrincipal, String navNameToDependent, Boolean oneToOne, ConfigurationSource configurationSource)
   at Microsoft.Data.Entity.Metadata.Internal.InternalEntityBuilder.BuildRelationship(Type principalType, Type dependentType, String navNameToPrincipal, String navNameToDependent, Boolean oneToOne, ConfigurationSource configurationSource)
   at Microsoft.Data.Entity.Metadata.ModelBuilder.EntityBuilder`1.OneToOne[TRelatedEntity](Expression`1 reference, Expression`1 inverse)
   at Include3.MyContext.OnModelCreating(ModelBuilder modelBuilder) in c:\Users\maumar\documents\visual studio 2015\Projects\Include3\src\Include3\Program.cs:li
ne 31
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.CreateModel(DbContext context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.<>c__DisplayClass0
.<GetModel>b__1(Type k)
   at Microsoft.Data.Entity.Utilities.ThreadSafeDictionaryCache`2.GetOrAdd(TKeykey, Func`2 factory)
   at Microsoft.Data.Entity.Infrastructure.DefaultModelSource.GetModel(DbContext context, IModelBuilderFactory modelBuilderFactory)
   at Microsoft.Data.Entity.Infrastructure.DbContextConfiguration.<Initialize>b__1()
   at Microsoft.Data.Entity.Utilities.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Infrastructure.DbContextConfiguration.get_Model()
   at Microsoft.Data.Entity.ChangeTracking.StateManager.get_Model()
   at Microsoft.Data.Entity.ChangeTracking.StateManager.GetOrCreateEntry(Objectentity)
   at Microsoft.Data.Entity.DbContext.Add[TEntity](TEntity entity)
   at Microsoft.Data.Entity.DbSet`1.Add(TEntity entity)

**Comment by divega** [comment]
@AndriySvyryd and I think this is probably already fixed but we need to verify.

**Comment by AndriySvyryd** [comment]
Verified
